// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"codebase-app/internal/entity/coreentity"

	mock "github.com/stretchr/testify/mock"
)

// NewDOKUWebhookVerifier creates a new instance of DOKUWebhookVerifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDOKUWebhookVerifier(t interface {
	mock.TestingT
	Cleanup(func())
}) *DOKUWebhookVerifier {
	mock := &DOKUWebhookVerifier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// DOKUWebhookVerifier is an autogenerated mock type for the DOKUWebhookVerifier type
type DOKUWebhookVerifier struct {
	mock.Mock
}

type DOKUWebhookVerifier_Expecter struct {
	mock *mock.Mock
}

func (_m *DOKUWebhookVerifier) EXPECT() *DOKUWebhookVerifier_Expecter {
	return &DOKUWebhookVerifier_Expecter{mock: &_m.Mock}
}

// VerifyWebhookSignatureHeaders provides a mock function for the type DOKUWebhookVerifier
func (_mock *DOKUWebhookVerifier) VerifyWebhookSignatureHeaders(headers coreentity.DOKUWebhookSignatureHeaders, body []byte, targetPath string) bool {
	ret := _mock.Called(headers, body, targetPath)

	if len(ret) == 0 {
		panic("no return value specified for VerifyWebhookSignatureHeaders")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(coreentity.DOKUWebhookSignatureHeaders, []byte, string) bool); ok {
		r0 = returnFunc(headers, body, targetPath)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// DOKUWebhookVerifier_VerifyWebhookSignatureHeaders_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyWebhookSignatureHeaders'
type DOKUWebhookVerifier_VerifyWebhookSignatureHeaders_Call struct {
	*mock.Call
}

// VerifyWebhookSignatureHeaders is a helper method to define mock.On call
//   - headers coreentity.DOKUWebhookSignatureHeaders
//   - body []byte
//   - targetPath string
func (_e *DOKUWebhookVerifier_Expecter) VerifyWebhookSignatureHeaders(headers interface{}, body interface{}, targetPath interface{}) *DOKUWebhookVerifier_VerifyWebhookSignatureHeaders_Call {
	return &DOKUWebhookVerifier_VerifyWebhookSignatureHeaders_Call{Call: _e.mock.On("VerifyWebhookSignatureHeaders", headers, body, targetPath)}
}

func (_c *DOKUWebhookVerifier_VerifyWebhookSignatureHeaders_Call) Run(run func(headers coreentity.DOKUWebhookSignatureHeaders, body []byte, targetPath string)) *DOKUWebhookVerifier_VerifyWebhookSignatureHeaders_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 coreentity.DOKUWebhookSignatureHeaders
		if args[0] != nil {
			arg0 = args[0].(coreentity.DOKUWebhookSignatureHeaders)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *DOKUWebhookVerifier_VerifyWebhookSignatureHeaders_Call) Return(b bool) *DOKUWebhookVerifier_VerifyWebhookSignatureHeaders_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *DOKUWebhookVerifier_VerifyWebhookSignatureHeaders_Call) RunAndReturn(run func(headers coreentity.DOKUWebhookSignatureHeaders, body []byte, targetPath string) bool) *DOKUWebhookVerifier_VerifyWebhookSignatureHeaders_Call {
	_c.Call.Return(run)
	return _c
}
