// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMessageBusSubscriptionContext creates a new instance of MessageBusSubscriptionContext. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMessageBusSubscriptionContext(t interface {
	mock.TestingT
	Cleanup(func())
}) *MessageBusSubscriptionContext {
	mock := &MessageBusSubscriptionContext{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MessageBusSubscriptionContext is an autogenerated mock type for the MessageBusSubscriptionContext type
type MessageBusSubscriptionContext struct {
	mock.Mock
}

type MessageBusSubscriptionContext_Expecter struct {
	mock *mock.Mock
}

func (_m *MessageBusSubscriptionContext) EXPECT() *MessageBusSubscriptionContext_Expecter {
	return &MessageBusSubscriptionContext_Expecter{mock: &_m.Mock}
}

// Stop provides a mock function for the type MessageBusSubscriptionContext
func (_mock *MessageBusSubscriptionContext) Stop() {
	_mock.Called()
	return
}

// MessageBusSubscriptionContext_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type MessageBusSubscriptionContext_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
func (_e *MessageBusSubscriptionContext_Expecter) Stop() *MessageBusSubscriptionContext_Stop_Call {
	return &MessageBusSubscriptionContext_Stop_Call{Call: _e.mock.On("Stop")}
}

func (_c *MessageBusSubscriptionContext_Stop_Call) Run(run func()) *MessageBusSubscriptionContext_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MessageBusSubscriptionContext_Stop_Call) Return() *MessageBusSubscriptionContext_Stop_Call {
	_c.Call.Return()
	return _c
}

func (_c *MessageBusSubscriptionContext_Stop_Call) RunAndReturn(run func()) *MessageBusSubscriptionContext_Stop_Call {
	_c.Run(run)
	return _c
}
