// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMessagePublisher creates a new instance of MessagePublisher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMessagePublisher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MessagePublisher {
	mock := &MessagePublisher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MessagePublisher is an autogenerated mock type for the MessagePublisher type
type MessagePublisher struct {
	mock.Mock
}

type MessagePublisher_Expecter struct {
	mock *mock.Mock
}

func (_m *MessagePublisher) EXPECT() *MessagePublisher_Expecter {
	return &MessagePublisher_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MessagePublisher
func (_mock *MessagePublisher) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MessagePublisher_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MessagePublisher_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MessagePublisher_Expecter) Close() *MessagePublisher_Close_Call {
	return &MessagePublisher_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MessagePublisher_Close_Call) Run(run func()) *MessagePublisher_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MessagePublisher_Close_Call) Return(err error) *MessagePublisher_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MessagePublisher_Close_Call) RunAndReturn(run func() error) *MessagePublisher_Close_Call {
	_c.Call.Return(run)
	return _c
}

// PublishJSON provides a mock function for the type MessagePublisher
func (_mock *MessagePublisher) PublishJSON(ctx context.Context, subject string, payload any) error {
	ret := _mock.Called(ctx, subject, payload)

	if len(ret) == 0 {
		panic("no return value specified for PublishJSON")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, any) error); ok {
		r0 = returnFunc(ctx, subject, payload)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MessagePublisher_PublishJSON_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishJSON'
type MessagePublisher_PublishJSON_Call struct {
	*mock.Call
}

// PublishJSON is a helper method to define mock.On call
//   - ctx context.Context
//   - subject string
//   - payload any
func (_e *MessagePublisher_Expecter) PublishJSON(ctx interface{}, subject interface{}, payload interface{}) *MessagePublisher_PublishJSON_Call {
	return &MessagePublisher_PublishJSON_Call{Call: _e.mock.On("PublishJSON", ctx, subject, payload)}
}

func (_c *MessagePublisher_PublishJSON_Call) Run(run func(ctx context.Context, subject string, payload any)) *MessagePublisher_PublishJSON_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 any
		if args[2] != nil {
			arg2 = args[2].(any)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MessagePublisher_PublishJSON_Call) Return(err error) *MessagePublisher_PublishJSON_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MessagePublisher_PublishJSON_Call) RunAndReturn(run func(ctx context.Context, subject string, payload any) error) *MessagePublisher_PublishJSON_Call {
	_c.Call.Return(run)
	return _c
}
