// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMessageBusMessage creates a new instance of MessageBusMessage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMessageBusMessage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MessageBusMessage {
	mock := &MessageBusMessage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MessageBusMessage is an autogenerated mock type for the MessageBusMessage type
type MessageBusMessage struct {
	mock.Mock
}

type MessageBusMessage_Expecter struct {
	mock *mock.Mock
}

func (_m *MessageBusMessage) EXPECT() *MessageBusMessage_Expecter {
	return &MessageBusMessage_Expecter{mock: &_m.Mock}
}

// Ack provides a mock function for the type MessageBusMessage
func (_mock *MessageBusMessage) Ack(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Ack")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MessageBusMessage_Ack_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ack'
type MessageBusMessage_Ack_Call struct {
	*mock.Call
}

// Ack is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MessageBusMessage_Expecter) Ack(ctx interface{}) *MessageBusMessage_Ack_Call {
	return &MessageBusMessage_Ack_Call{Call: _e.mock.On("Ack", ctx)}
}

func (_c *MessageBusMessage_Ack_Call) Run(run func(ctx context.Context)) *MessageBusMessage_Ack_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MessageBusMessage_Ack_Call) Return(err error) *MessageBusMessage_Ack_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MessageBusMessage_Ack_Call) RunAndReturn(run func(ctx context.Context) error) *MessageBusMessage_Ack_Call {
	_c.Call.Return(run)
	return _c
}

// Data provides a mock function for the type MessageBusMessage
func (_mock *MessageBusMessage) Data() []byte {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Data")
	}

	var r0 []byte
	if returnFunc, ok := ret.Get(0).(func() []byte); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	return r0
}

// MessageBusMessage_Data_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Data'
type MessageBusMessage_Data_Call struct {
	*mock.Call
}

// Data is a helper method to define mock.On call
func (_e *MessageBusMessage_Expecter) Data() *MessageBusMessage_Data_Call {
	return &MessageBusMessage_Data_Call{Call: _e.mock.On("Data")}
}

func (_c *MessageBusMessage_Data_Call) Run(run func()) *MessageBusMessage_Data_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MessageBusMessage_Data_Call) Return(bytes []byte) *MessageBusMessage_Data_Call {
	_c.Call.Return(bytes)
	return _c
}

func (_c *MessageBusMessage_Data_Call) RunAndReturn(run func() []byte) *MessageBusMessage_Data_Call {
	_c.Call.Return(run)
	return _c
}

// Headers provides a mock function for the type MessageBusMessage
func (_mock *MessageBusMessage) Headers() map[string][]string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Headers")
	}

	var r0 map[string][]string
	if returnFunc, ok := ret.Get(0).(func() map[string][]string); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string][]string)
		}
	}
	return r0
}

// MessageBusMessage_Headers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Headers'
type MessageBusMessage_Headers_Call struct {
	*mock.Call
}

// Headers is a helper method to define mock.On call
func (_e *MessageBusMessage_Expecter) Headers() *MessageBusMessage_Headers_Call {
	return &MessageBusMessage_Headers_Call{Call: _e.mock.On("Headers")}
}

func (_c *MessageBusMessage_Headers_Call) Run(run func()) *MessageBusMessage_Headers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MessageBusMessage_Headers_Call) Return(stringToStrings map[string][]string) *MessageBusMessage_Headers_Call {
	_c.Call.Return(stringToStrings)
	return _c
}

func (_c *MessageBusMessage_Headers_Call) RunAndReturn(run func() map[string][]string) *MessageBusMessage_Headers_Call {
	_c.Call.Return(run)
	return _c
}

// Nak provides a mock function for the type MessageBusMessage
func (_mock *MessageBusMessage) Nak(ctx context.Context, reason string) error {
	ret := _mock.Called(ctx, reason)

	if len(ret) == 0 {
		panic("no return value specified for Nak")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, reason)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MessageBusMessage_Nak_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Nak'
type MessageBusMessage_Nak_Call struct {
	*mock.Call
}

// Nak is a helper method to define mock.On call
//   - ctx context.Context
//   - reason string
func (_e *MessageBusMessage_Expecter) Nak(ctx interface{}, reason interface{}) *MessageBusMessage_Nak_Call {
	return &MessageBusMessage_Nak_Call{Call: _e.mock.On("Nak", ctx, reason)}
}

func (_c *MessageBusMessage_Nak_Call) Run(run func(ctx context.Context, reason string)) *MessageBusMessage_Nak_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MessageBusMessage_Nak_Call) Return(err error) *MessageBusMessage_Nak_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MessageBusMessage_Nak_Call) RunAndReturn(run func(ctx context.Context, reason string) error) *MessageBusMessage_Nak_Call {
	_c.Call.Return(run)
	return _c
}

// Subject provides a mock function for the type MessageBusMessage
func (_mock *MessageBusMessage) Subject() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Subject")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MessageBusMessage_Subject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Subject'
type MessageBusMessage_Subject_Call struct {
	*mock.Call
}

// Subject is a helper method to define mock.On call
func (_e *MessageBusMessage_Expecter) Subject() *MessageBusMessage_Subject_Call {
	return &MessageBusMessage_Subject_Call{Call: _e.mock.On("Subject")}
}

func (_c *MessageBusMessage_Subject_Call) Run(run func()) *MessageBusMessage_Subject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MessageBusMessage_Subject_Call) Return(s string) *MessageBusMessage_Subject_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MessageBusMessage_Subject_Call) RunAndReturn(run func() string) *MessageBusMessage_Subject_Call {
	_c.Call.Return(run)
	return _c
}
