// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"codebase-app/internal/ports/integration"
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMessageBusSubscription creates a new instance of MessageBusSubscription. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMessageBusSubscription(t interface {
	mock.TestingT
	Cleanup(func())
}) *MessageBusSubscription {
	mock := &MessageBusSubscription{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MessageBusSubscription is an autogenerated mock type for the MessageBusSubscription type
type MessageBusSubscription struct {
	mock.Mock
}

type MessageBusSubscription_Expecter struct {
	mock *mock.Mock
}

func (_m *MessageBusSubscription) EXPECT() *MessageBusSubscription_Expecter {
	return &MessageBusSubscription_Expecter{mock: &_m.Mock}
}

// Consume provides a mock function for the type MessageBusSubscription
func (_mock *MessageBusSubscription) Consume(ctx context.Context, handler func(context.Context, integration.MessageBusMessage)) (integration.MessageBusSubscriptionContext, error) {
	ret := _mock.Called(ctx, handler)

	if len(ret) == 0 {
		panic("no return value specified for Consume")
	}

	var r0 integration.MessageBusSubscriptionContext
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, func(context.Context, integration.MessageBusMessage)) (integration.MessageBusSubscriptionContext, error)); ok {
		return returnFunc(ctx, handler)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, func(context.Context, integration.MessageBusMessage)) integration.MessageBusSubscriptionContext); ok {
		r0 = returnFunc(ctx, handler)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(integration.MessageBusSubscriptionContext)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, func(context.Context, integration.MessageBusMessage)) error); ok {
		r1 = returnFunc(ctx, handler)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MessageBusSubscription_Consume_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Consume'
type MessageBusSubscription_Consume_Call struct {
	*mock.Call
}

// Consume is a helper method to define mock.On call
//   - ctx context.Context
//   - handler func(context.Context, integration.MessageBusMessage)
func (_e *MessageBusSubscription_Expecter) Consume(ctx interface{}, handler interface{}) *MessageBusSubscription_Consume_Call {
	return &MessageBusSubscription_Consume_Call{Call: _e.mock.On("Consume", ctx, handler)}
}

func (_c *MessageBusSubscription_Consume_Call) Run(run func(ctx context.Context, handler func(context.Context, integration.MessageBusMessage))) *MessageBusSubscription_Consume_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 func(context.Context, integration.MessageBusMessage)
		if args[1] != nil {
			arg1 = args[1].(func(context.Context, integration.MessageBusMessage))
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MessageBusSubscription_Consume_Call) Return(messageBusSubscriptionContext integration.MessageBusSubscriptionContext, err error) *MessageBusSubscription_Consume_Call {
	_c.Call.Return(messageBusSubscriptionContext, err)
	return _c
}

func (_c *MessageBusSubscription_Consume_Call) RunAndReturn(run func(ctx context.Context, handler func(context.Context, integration.MessageBusMessage)) (integration.MessageBusSubscriptionContext, error)) *MessageBusSubscription_Consume_Call {
	_c.Call.Return(run)
	return _c
}
