// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"codebase-app/internal/entity/common"
	"codebase-app/internal/ports/integration"
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMessageSubscriptionManager creates a new instance of MessageSubscriptionManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMessageSubscriptionManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MessageSubscriptionManager {
	mock := &MessageSubscriptionManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MessageSubscriptionManager is an autogenerated mock type for the MessageSubscriptionManager type
type MessageSubscriptionManager struct {
	mock.Mock
}

type MessageSubscriptionManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MessageSubscriptionManager) EXPECT() *MessageSubscriptionManager_Expecter {
	return &MessageSubscriptionManager_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MessageSubscriptionManager
func (_mock *MessageSubscriptionManager) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MessageSubscriptionManager_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MessageSubscriptionManager_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MessageSubscriptionManager_Expecter) Close() *MessageSubscriptionManager_Close_Call {
	return &MessageSubscriptionManager_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MessageSubscriptionManager_Close_Call) Run(run func()) *MessageSubscriptionManager_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MessageSubscriptionManager_Close_Call) Return(err error) *MessageSubscriptionManager_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MessageSubscriptionManager_Close_Call) RunAndReturn(run func() error) *MessageSubscriptionManager_Close_Call {
	_c.Call.Return(run)
	return _c
}

// CreateSubscription provides a mock function for the type MessageSubscriptionManager
func (_mock *MessageSubscriptionManager) CreateSubscription(ctx context.Context, cfg common.MessageBusSubscriptionConfig) (integration.MessageBusSubscription, error) {
	ret := _mock.Called(ctx, cfg)

	if len(ret) == 0 {
		panic("no return value specified for CreateSubscription")
	}

	var r0 integration.MessageBusSubscription
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, common.MessageBusSubscriptionConfig) (integration.MessageBusSubscription, error)); ok {
		return returnFunc(ctx, cfg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, common.MessageBusSubscriptionConfig) integration.MessageBusSubscription); ok {
		r0 = returnFunc(ctx, cfg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(integration.MessageBusSubscription)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, common.MessageBusSubscriptionConfig) error); ok {
		r1 = returnFunc(ctx, cfg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MessageSubscriptionManager_CreateSubscription_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSubscription'
type MessageSubscriptionManager_CreateSubscription_Call struct {
	*mock.Call
}

// CreateSubscription is a helper method to define mock.On call
//   - ctx context.Context
//   - cfg common.MessageBusSubscriptionConfig
func (_e *MessageSubscriptionManager_Expecter) CreateSubscription(ctx interface{}, cfg interface{}) *MessageSubscriptionManager_CreateSubscription_Call {
	return &MessageSubscriptionManager_CreateSubscription_Call{Call: _e.mock.On("CreateSubscription", ctx, cfg)}
}

func (_c *MessageSubscriptionManager_CreateSubscription_Call) Run(run func(ctx context.Context, cfg common.MessageBusSubscriptionConfig)) *MessageSubscriptionManager_CreateSubscription_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 common.MessageBusSubscriptionConfig
		if args[1] != nil {
			arg1 = args[1].(common.MessageBusSubscriptionConfig)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MessageSubscriptionManager_CreateSubscription_Call) Return(messageBusSubscription integration.MessageBusSubscription, err error) *MessageSubscriptionManager_CreateSubscription_Call {
	_c.Call.Return(messageBusSubscription, err)
	return _c
}

func (_c *MessageSubscriptionManager_CreateSubscription_Call) RunAndReturn(run func(ctx context.Context, cfg common.MessageBusSubscriptionConfig) (integration.MessageBusSubscription, error)) *MessageSubscriptionManager_CreateSubscription_Call {
	_c.Call.Return(run)
	return _c
}
