// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"codebase-app/internal/entity/coreentity"
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewAttendanceRepository creates a new instance of AttendanceRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAttendanceRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *AttendanceRepository {
	mock := &AttendanceRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// AttendanceRepository is an autogenerated mock type for the AttendanceRepository type
type AttendanceRepository struct {
	mock.Mock
}

type AttendanceRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *AttendanceRepository) EXPECT() *AttendanceRepository_Expecter {
	return &AttendanceRepository_Expecter{mock: &_m.Mock}
}

// CreateAttendanceLog provides a mock function for the type AttendanceRepository
func (_mock *AttendanceRepository) CreateAttendanceLog(ctx context.Context, data coreentity.AttendanceLog) (*coreentity.AttendanceLog, error) {
	ret := _mock.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for CreateAttendanceLog")
	}

	var r0 *coreentity.AttendanceLog
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.AttendanceLog) (*coreentity.AttendanceLog, error)); ok {
		return returnFunc(ctx, data)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.AttendanceLog) *coreentity.AttendanceLog); ok {
		r0 = returnFunc(ctx, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*coreentity.AttendanceLog)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, coreentity.AttendanceLog) error); ok {
		r1 = returnFunc(ctx, data)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AttendanceRepository_CreateAttendanceLog_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAttendanceLog'
type AttendanceRepository_CreateAttendanceLog_Call struct {
	*mock.Call
}

// CreateAttendanceLog is a helper method to define mock.On call
//   - ctx context.Context
//   - data coreentity.AttendanceLog
func (_e *AttendanceRepository_Expecter) CreateAttendanceLog(ctx interface{}, data interface{}) *AttendanceRepository_CreateAttendanceLog_Call {
	return &AttendanceRepository_CreateAttendanceLog_Call{Call: _e.mock.On("CreateAttendanceLog", ctx, data)}
}

func (_c *AttendanceRepository_CreateAttendanceLog_Call) Run(run func(ctx context.Context, data coreentity.AttendanceLog)) *AttendanceRepository_CreateAttendanceLog_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 coreentity.AttendanceLog
		if args[1] != nil {
			arg1 = args[1].(coreentity.AttendanceLog)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AttendanceRepository_CreateAttendanceLog_Call) Return(attendanceLog *coreentity.AttendanceLog, err error) *AttendanceRepository_CreateAttendanceLog_Call {
	_c.Call.Return(attendanceLog, err)
	return _c
}

func (_c *AttendanceRepository_CreateAttendanceLog_Call) RunAndReturn(run func(ctx context.Context, data coreentity.AttendanceLog) (*coreentity.AttendanceLog, error)) *AttendanceRepository_CreateAttendanceLog_Call {
	_c.Call.Return(run)
	return _c
}

// ExistsAttendanceByTypeOnDate provides a mock function for the type AttendanceRepository
func (_mock *AttendanceRepository) ExistsAttendanceByTypeOnDate(ctx context.Context, tenantID string, employeeID string, attendanceDate string, attendanceType string) (bool, error) {
	ret := _mock.Called(ctx, tenantID, employeeID, attendanceDate, attendanceType)

	if len(ret) == 0 {
		panic("no return value specified for ExistsAttendanceByTypeOnDate")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string) (bool, error)); ok {
		return returnFunc(ctx, tenantID, employeeID, attendanceDate, attendanceType)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string) bool); ok {
		r0 = returnFunc(ctx, tenantID, employeeID, attendanceDate, attendanceType)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string, string) error); ok {
		r1 = returnFunc(ctx, tenantID, employeeID, attendanceDate, attendanceType)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AttendanceRepository_ExistsAttendanceByTypeOnDate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExistsAttendanceByTypeOnDate'
type AttendanceRepository_ExistsAttendanceByTypeOnDate_Call struct {
	*mock.Call
}

// ExistsAttendanceByTypeOnDate is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID string
//   - employeeID string
//   - attendanceDate string
//   - attendanceType string
func (_e *AttendanceRepository_Expecter) ExistsAttendanceByTypeOnDate(ctx interface{}, tenantID interface{}, employeeID interface{}, attendanceDate interface{}, attendanceType interface{}) *AttendanceRepository_ExistsAttendanceByTypeOnDate_Call {
	return &AttendanceRepository_ExistsAttendanceByTypeOnDate_Call{Call: _e.mock.On("ExistsAttendanceByTypeOnDate", ctx, tenantID, employeeID, attendanceDate, attendanceType)}
}

func (_c *AttendanceRepository_ExistsAttendanceByTypeOnDate_Call) Run(run func(ctx context.Context, tenantID string, employeeID string, attendanceDate string, attendanceType string)) *AttendanceRepository_ExistsAttendanceByTypeOnDate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *AttendanceRepository_ExistsAttendanceByTypeOnDate_Call) Return(b bool, err error) *AttendanceRepository_ExistsAttendanceByTypeOnDate_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *AttendanceRepository_ExistsAttendanceByTypeOnDate_Call) RunAndReturn(run func(ctx context.Context, tenantID string, employeeID string, attendanceDate string, attendanceType string) (bool, error)) *AttendanceRepository_ExistsAttendanceByTypeOnDate_Call {
	_c.Call.Return(run)
	return _c
}

// GetAttendanceLog provides a mock function for the type AttendanceRepository
func (_mock *AttendanceRepository) GetAttendanceLog(ctx context.Context, filter coreentity.AttendanceLogDetailFilter) (*coreentity.AttendanceLog, error) {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetAttendanceLog")
	}

	var r0 *coreentity.AttendanceLog
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.AttendanceLogDetailFilter) (*coreentity.AttendanceLog, error)); ok {
		return returnFunc(ctx, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.AttendanceLogDetailFilter) *coreentity.AttendanceLog); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*coreentity.AttendanceLog)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, coreentity.AttendanceLogDetailFilter) error); ok {
		r1 = returnFunc(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AttendanceRepository_GetAttendanceLog_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAttendanceLog'
type AttendanceRepository_GetAttendanceLog_Call struct {
	*mock.Call
}

// GetAttendanceLog is a helper method to define mock.On call
//   - ctx context.Context
//   - filter coreentity.AttendanceLogDetailFilter
func (_e *AttendanceRepository_Expecter) GetAttendanceLog(ctx interface{}, filter interface{}) *AttendanceRepository_GetAttendanceLog_Call {
	return &AttendanceRepository_GetAttendanceLog_Call{Call: _e.mock.On("GetAttendanceLog", ctx, filter)}
}

func (_c *AttendanceRepository_GetAttendanceLog_Call) Run(run func(ctx context.Context, filter coreentity.AttendanceLogDetailFilter)) *AttendanceRepository_GetAttendanceLog_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 coreentity.AttendanceLogDetailFilter
		if args[1] != nil {
			arg1 = args[1].(coreentity.AttendanceLogDetailFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AttendanceRepository_GetAttendanceLog_Call) Return(attendanceLog *coreentity.AttendanceLog, err error) *AttendanceRepository_GetAttendanceLog_Call {
	_c.Call.Return(attendanceLog, err)
	return _c
}

func (_c *AttendanceRepository_GetAttendanceLog_Call) RunAndReturn(run func(ctx context.Context, filter coreentity.AttendanceLogDetailFilter) (*coreentity.AttendanceLog, error)) *AttendanceRepository_GetAttendanceLog_Call {
	_c.Call.Return(run)
	return _c
}

// GetAttendanceLogs provides a mock function for the type AttendanceRepository
func (_mock *AttendanceRepository) GetAttendanceLogs(ctx context.Context, filter coreentity.AttendanceLogListFilter) ([]coreentity.AttendanceLog, int, error) {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetAttendanceLogs")
	}

	var r0 []coreentity.AttendanceLog
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.AttendanceLogListFilter) ([]coreentity.AttendanceLog, int, error)); ok {
		return returnFunc(ctx, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.AttendanceLogListFilter) []coreentity.AttendanceLog); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]coreentity.AttendanceLog)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, coreentity.AttendanceLogListFilter) int); ok {
		r1 = returnFunc(ctx, filter)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, coreentity.AttendanceLogListFilter) error); ok {
		r2 = returnFunc(ctx, filter)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// AttendanceRepository_GetAttendanceLogs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAttendanceLogs'
type AttendanceRepository_GetAttendanceLogs_Call struct {
	*mock.Call
}

// GetAttendanceLogs is a helper method to define mock.On call
//   - ctx context.Context
//   - filter coreentity.AttendanceLogListFilter
func (_e *AttendanceRepository_Expecter) GetAttendanceLogs(ctx interface{}, filter interface{}) *AttendanceRepository_GetAttendanceLogs_Call {
	return &AttendanceRepository_GetAttendanceLogs_Call{Call: _e.mock.On("GetAttendanceLogs", ctx, filter)}
}

func (_c *AttendanceRepository_GetAttendanceLogs_Call) Run(run func(ctx context.Context, filter coreentity.AttendanceLogListFilter)) *AttendanceRepository_GetAttendanceLogs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 coreentity.AttendanceLogListFilter
		if args[1] != nil {
			arg1 = args[1].(coreentity.AttendanceLogListFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AttendanceRepository_GetAttendanceLogs_Call) Return(attendanceLogs []coreentity.AttendanceLog, n int, err error) *AttendanceRepository_GetAttendanceLogs_Call {
	_c.Call.Return(attendanceLogs, n, err)
	return _c
}

func (_c *AttendanceRepository_GetAttendanceLogs_Call) RunAndReturn(run func(ctx context.Context, filter coreentity.AttendanceLogListFilter) ([]coreentity.AttendanceLog, int, error)) *AttendanceRepository_GetAttendanceLogs_Call {
	_c.Call.Return(run)
	return _c
}

// GetAttendanceLogsAll provides a mock function for the type AttendanceRepository
func (_mock *AttendanceRepository) GetAttendanceLogsAll(ctx context.Context, filter coreentity.AttendanceLogListFilter) ([]coreentity.AttendanceLog, error) {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetAttendanceLogsAll")
	}

	var r0 []coreentity.AttendanceLog
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.AttendanceLogListFilter) ([]coreentity.AttendanceLog, error)); ok {
		return returnFunc(ctx, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.AttendanceLogListFilter) []coreentity.AttendanceLog); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]coreentity.AttendanceLog)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, coreentity.AttendanceLogListFilter) error); ok {
		r1 = returnFunc(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AttendanceRepository_GetAttendanceLogsAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAttendanceLogsAll'
type AttendanceRepository_GetAttendanceLogsAll_Call struct {
	*mock.Call
}

// GetAttendanceLogsAll is a helper method to define mock.On call
//   - ctx context.Context
//   - filter coreentity.AttendanceLogListFilter
func (_e *AttendanceRepository_Expecter) GetAttendanceLogsAll(ctx interface{}, filter interface{}) *AttendanceRepository_GetAttendanceLogsAll_Call {
	return &AttendanceRepository_GetAttendanceLogsAll_Call{Call: _e.mock.On("GetAttendanceLogsAll", ctx, filter)}
}

func (_c *AttendanceRepository_GetAttendanceLogsAll_Call) Run(run func(ctx context.Context, filter coreentity.AttendanceLogListFilter)) *AttendanceRepository_GetAttendanceLogsAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 coreentity.AttendanceLogListFilter
		if args[1] != nil {
			arg1 = args[1].(coreentity.AttendanceLogListFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AttendanceRepository_GetAttendanceLogsAll_Call) Return(attendanceLogs []coreentity.AttendanceLog, err error) *AttendanceRepository_GetAttendanceLogsAll_Call {
	_c.Call.Return(attendanceLogs, err)
	return _c
}

func (_c *AttendanceRepository_GetAttendanceLogsAll_Call) RunAndReturn(run func(ctx context.Context, filter coreentity.AttendanceLogListFilter) ([]coreentity.AttendanceLog, error)) *AttendanceRepository_GetAttendanceLogsAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetEmployeeByUserID provides a mock function for the type AttendanceRepository
func (_mock *AttendanceRepository) GetEmployeeByUserID(ctx context.Context, tenantID string, userID string) (*coreentity.Employee, error) {
	ret := _mock.Called(ctx, tenantID, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetEmployeeByUserID")
	}

	var r0 *coreentity.Employee
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*coreentity.Employee, error)); ok {
		return returnFunc(ctx, tenantID, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *coreentity.Employee); ok {
		r0 = returnFunc(ctx, tenantID, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*coreentity.Employee)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, tenantID, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AttendanceRepository_GetEmployeeByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEmployeeByUserID'
type AttendanceRepository_GetEmployeeByUserID_Call struct {
	*mock.Call
}

// GetEmployeeByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID string
//   - userID string
func (_e *AttendanceRepository_Expecter) GetEmployeeByUserID(ctx interface{}, tenantID interface{}, userID interface{}) *AttendanceRepository_GetEmployeeByUserID_Call {
	return &AttendanceRepository_GetEmployeeByUserID_Call{Call: _e.mock.On("GetEmployeeByUserID", ctx, tenantID, userID)}
}

func (_c *AttendanceRepository_GetEmployeeByUserID_Call) Run(run func(ctx context.Context, tenantID string, userID string)) *AttendanceRepository_GetEmployeeByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *AttendanceRepository_GetEmployeeByUserID_Call) Return(employee *coreentity.Employee, err error) *AttendanceRepository_GetEmployeeByUserID_Call {
	_c.Call.Return(employee, err)
	return _c
}

func (_c *AttendanceRepository_GetEmployeeByUserID_Call) RunAndReturn(run func(ctx context.Context, tenantID string, userID string) (*coreentity.Employee, error)) *AttendanceRepository_GetEmployeeByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// GetOwnerAttendanceDashboardExceptions provides a mock function for the type AttendanceRepository
func (_mock *AttendanceRepository) GetOwnerAttendanceDashboardExceptions(ctx context.Context, filter coreentity.OwnerAttendanceDashboardFilter) ([]coreentity.OwnerAttendanceDashboardException, error) {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetOwnerAttendanceDashboardExceptions")
	}

	var r0 []coreentity.OwnerAttendanceDashboardException
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.OwnerAttendanceDashboardFilter) ([]coreentity.OwnerAttendanceDashboardException, error)); ok {
		return returnFunc(ctx, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.OwnerAttendanceDashboardFilter) []coreentity.OwnerAttendanceDashboardException); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]coreentity.OwnerAttendanceDashboardException)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, coreentity.OwnerAttendanceDashboardFilter) error); ok {
		r1 = returnFunc(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AttendanceRepository_GetOwnerAttendanceDashboardExceptions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOwnerAttendanceDashboardExceptions'
type AttendanceRepository_GetOwnerAttendanceDashboardExceptions_Call struct {
	*mock.Call
}

// GetOwnerAttendanceDashboardExceptions is a helper method to define mock.On call
//   - ctx context.Context
//   - filter coreentity.OwnerAttendanceDashboardFilter
func (_e *AttendanceRepository_Expecter) GetOwnerAttendanceDashboardExceptions(ctx interface{}, filter interface{}) *AttendanceRepository_GetOwnerAttendanceDashboardExceptions_Call {
	return &AttendanceRepository_GetOwnerAttendanceDashboardExceptions_Call{Call: _e.mock.On("GetOwnerAttendanceDashboardExceptions", ctx, filter)}
}

func (_c *AttendanceRepository_GetOwnerAttendanceDashboardExceptions_Call) Run(run func(ctx context.Context, filter coreentity.OwnerAttendanceDashboardFilter)) *AttendanceRepository_GetOwnerAttendanceDashboardExceptions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 coreentity.OwnerAttendanceDashboardFilter
		if args[1] != nil {
			arg1 = args[1].(coreentity.OwnerAttendanceDashboardFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AttendanceRepository_GetOwnerAttendanceDashboardExceptions_Call) Return(ownerAttendanceDashboardExceptions []coreentity.OwnerAttendanceDashboardException, err error) *AttendanceRepository_GetOwnerAttendanceDashboardExceptions_Call {
	_c.Call.Return(ownerAttendanceDashboardExceptions, err)
	return _c
}

func (_c *AttendanceRepository_GetOwnerAttendanceDashboardExceptions_Call) RunAndReturn(run func(ctx context.Context, filter coreentity.OwnerAttendanceDashboardFilter) ([]coreentity.OwnerAttendanceDashboardException, error)) *AttendanceRepository_GetOwnerAttendanceDashboardExceptions_Call {
	_c.Call.Return(run)
	return _c
}

// GetOwnerAttendanceDashboardSummary provides a mock function for the type AttendanceRepository
func (_mock *AttendanceRepository) GetOwnerAttendanceDashboardSummary(ctx context.Context, filter coreentity.OwnerAttendanceDashboardFilter) (*coreentity.OwnerAttendanceDashboardSummary, error) {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetOwnerAttendanceDashboardSummary")
	}

	var r0 *coreentity.OwnerAttendanceDashboardSummary
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.OwnerAttendanceDashboardFilter) (*coreentity.OwnerAttendanceDashboardSummary, error)); ok {
		return returnFunc(ctx, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.OwnerAttendanceDashboardFilter) *coreentity.OwnerAttendanceDashboardSummary); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*coreentity.OwnerAttendanceDashboardSummary)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, coreentity.OwnerAttendanceDashboardFilter) error); ok {
		r1 = returnFunc(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AttendanceRepository_GetOwnerAttendanceDashboardSummary_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOwnerAttendanceDashboardSummary'
type AttendanceRepository_GetOwnerAttendanceDashboardSummary_Call struct {
	*mock.Call
}

// GetOwnerAttendanceDashboardSummary is a helper method to define mock.On call
//   - ctx context.Context
//   - filter coreentity.OwnerAttendanceDashboardFilter
func (_e *AttendanceRepository_Expecter) GetOwnerAttendanceDashboardSummary(ctx interface{}, filter interface{}) *AttendanceRepository_GetOwnerAttendanceDashboardSummary_Call {
	return &AttendanceRepository_GetOwnerAttendanceDashboardSummary_Call{Call: _e.mock.On("GetOwnerAttendanceDashboardSummary", ctx, filter)}
}

func (_c *AttendanceRepository_GetOwnerAttendanceDashboardSummary_Call) Run(run func(ctx context.Context, filter coreentity.OwnerAttendanceDashboardFilter)) *AttendanceRepository_GetOwnerAttendanceDashboardSummary_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 coreentity.OwnerAttendanceDashboardFilter
		if args[1] != nil {
			arg1 = args[1].(coreentity.OwnerAttendanceDashboardFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AttendanceRepository_GetOwnerAttendanceDashboardSummary_Call) Return(ownerAttendanceDashboardSummary *coreentity.OwnerAttendanceDashboardSummary, err error) *AttendanceRepository_GetOwnerAttendanceDashboardSummary_Call {
	_c.Call.Return(ownerAttendanceDashboardSummary, err)
	return _c
}

func (_c *AttendanceRepository_GetOwnerAttendanceDashboardSummary_Call) RunAndReturn(run func(ctx context.Context, filter coreentity.OwnerAttendanceDashboardFilter) (*coreentity.OwnerAttendanceDashboardSummary, error)) *AttendanceRepository_GetOwnerAttendanceDashboardSummary_Call {
	_c.Call.Return(run)
	return _c
}

// GetOwnerAttendanceDashboardTrend provides a mock function for the type AttendanceRepository
func (_mock *AttendanceRepository) GetOwnerAttendanceDashboardTrend(ctx context.Context, filter coreentity.OwnerAttendanceDashboardFilter) ([]coreentity.OwnerAttendanceDashboardDailyTrend, error) {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetOwnerAttendanceDashboardTrend")
	}

	var r0 []coreentity.OwnerAttendanceDashboardDailyTrend
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.OwnerAttendanceDashboardFilter) ([]coreentity.OwnerAttendanceDashboardDailyTrend, error)); ok {
		return returnFunc(ctx, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.OwnerAttendanceDashboardFilter) []coreentity.OwnerAttendanceDashboardDailyTrend); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]coreentity.OwnerAttendanceDashboardDailyTrend)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, coreentity.OwnerAttendanceDashboardFilter) error); ok {
		r1 = returnFunc(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AttendanceRepository_GetOwnerAttendanceDashboardTrend_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOwnerAttendanceDashboardTrend'
type AttendanceRepository_GetOwnerAttendanceDashboardTrend_Call struct {
	*mock.Call
}

// GetOwnerAttendanceDashboardTrend is a helper method to define mock.On call
//   - ctx context.Context
//   - filter coreentity.OwnerAttendanceDashboardFilter
func (_e *AttendanceRepository_Expecter) GetOwnerAttendanceDashboardTrend(ctx interface{}, filter interface{}) *AttendanceRepository_GetOwnerAttendanceDashboardTrend_Call {
	return &AttendanceRepository_GetOwnerAttendanceDashboardTrend_Call{Call: _e.mock.On("GetOwnerAttendanceDashboardTrend", ctx, filter)}
}

func (_c *AttendanceRepository_GetOwnerAttendanceDashboardTrend_Call) Run(run func(ctx context.Context, filter coreentity.OwnerAttendanceDashboardFilter)) *AttendanceRepository_GetOwnerAttendanceDashboardTrend_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 coreentity.OwnerAttendanceDashboardFilter
		if args[1] != nil {
			arg1 = args[1].(coreentity.OwnerAttendanceDashboardFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AttendanceRepository_GetOwnerAttendanceDashboardTrend_Call) Return(ownerAttendanceDashboardDailyTrends []coreentity.OwnerAttendanceDashboardDailyTrend, err error) *AttendanceRepository_GetOwnerAttendanceDashboardTrend_Call {
	_c.Call.Return(ownerAttendanceDashboardDailyTrends, err)
	return _c
}

func (_c *AttendanceRepository_GetOwnerAttendanceDashboardTrend_Call) RunAndReturn(run func(ctx context.Context, filter coreentity.OwnerAttendanceDashboardFilter) ([]coreentity.OwnerAttendanceDashboardDailyTrend, error)) *AttendanceRepository_GetOwnerAttendanceDashboardTrend_Call {
	_c.Call.Return(run)
	return _c
}

// GetWorkLocation provides a mock function for the type AttendanceRepository
func (_mock *AttendanceRepository) GetWorkLocation(ctx context.Context, filter coreentity.WorkLocation) (*coreentity.WorkLocation, error) {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetWorkLocation")
	}

	var r0 *coreentity.WorkLocation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.WorkLocation) (*coreentity.WorkLocation, error)); ok {
		return returnFunc(ctx, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.WorkLocation) *coreentity.WorkLocation); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*coreentity.WorkLocation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, coreentity.WorkLocation) error); ok {
		r1 = returnFunc(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AttendanceRepository_GetWorkLocation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWorkLocation'
type AttendanceRepository_GetWorkLocation_Call struct {
	*mock.Call
}

// GetWorkLocation is a helper method to define mock.On call
//   - ctx context.Context
//   - filter coreentity.WorkLocation
func (_e *AttendanceRepository_Expecter) GetWorkLocation(ctx interface{}, filter interface{}) *AttendanceRepository_GetWorkLocation_Call {
	return &AttendanceRepository_GetWorkLocation_Call{Call: _e.mock.On("GetWorkLocation", ctx, filter)}
}

func (_c *AttendanceRepository_GetWorkLocation_Call) Run(run func(ctx context.Context, filter coreentity.WorkLocation)) *AttendanceRepository_GetWorkLocation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 coreentity.WorkLocation
		if args[1] != nil {
			arg1 = args[1].(coreentity.WorkLocation)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AttendanceRepository_GetWorkLocation_Call) Return(workLocation *coreentity.WorkLocation, err error) *AttendanceRepository_GetWorkLocation_Call {
	_c.Call.Return(workLocation, err)
	return _c
}

func (_c *AttendanceRepository_GetWorkLocation_Call) RunAndReturn(run func(ctx context.Context, filter coreentity.WorkLocation) (*coreentity.WorkLocation, error)) *AttendanceRepository_GetWorkLocation_Call {
	_c.Call.Return(run)
	return _c
}

// GetWorkShift provides a mock function for the type AttendanceRepository
func (_mock *AttendanceRepository) GetWorkShift(ctx context.Context, filter coreentity.WorkShift) (*coreentity.WorkShift, error) {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetWorkShift")
	}

	var r0 *coreentity.WorkShift
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.WorkShift) (*coreentity.WorkShift, error)); ok {
		return returnFunc(ctx, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.WorkShift) *coreentity.WorkShift); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*coreentity.WorkShift)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, coreentity.WorkShift) error); ok {
		r1 = returnFunc(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AttendanceRepository_GetWorkShift_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWorkShift'
type AttendanceRepository_GetWorkShift_Call struct {
	*mock.Call
}

// GetWorkShift is a helper method to define mock.On call
//   - ctx context.Context
//   - filter coreentity.WorkShift
func (_e *AttendanceRepository_Expecter) GetWorkShift(ctx interface{}, filter interface{}) *AttendanceRepository_GetWorkShift_Call {
	return &AttendanceRepository_GetWorkShift_Call{Call: _e.mock.On("GetWorkShift", ctx, filter)}
}

func (_c *AttendanceRepository_GetWorkShift_Call) Run(run func(ctx context.Context, filter coreentity.WorkShift)) *AttendanceRepository_GetWorkShift_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 coreentity.WorkShift
		if args[1] != nil {
			arg1 = args[1].(coreentity.WorkShift)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AttendanceRepository_GetWorkShift_Call) Return(workShift *coreentity.WorkShift, err error) *AttendanceRepository_GetWorkShift_Call {
	_c.Call.Return(workShift, err)
	return _c
}

func (_c *AttendanceRepository_GetWorkShift_Call) RunAndReturn(run func(ctx context.Context, filter coreentity.WorkShift) (*coreentity.WorkShift, error)) *AttendanceRepository_GetWorkShift_Call {
	_c.Call.Return(run)
	return _c
}
