// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"codebase-app/internal/entity/coreentity"
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewCompanyRepository creates a new instance of CompanyRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCompanyRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *CompanyRepository {
	mock := &CompanyRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// CompanyRepository is an autogenerated mock type for the CompanyRepository type
type CompanyRepository struct {
	mock.Mock
}

type CompanyRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *CompanyRepository) EXPECT() *CompanyRepository_Expecter {
	return &CompanyRepository_Expecter{mock: &_m.Mock}
}

// CountCompaniesByTenant provides a mock function for the type CompanyRepository
func (_mock *CompanyRepository) CountCompaniesByTenant(ctx context.Context, tenantID string) (int64, error) {
	ret := _mock.Called(ctx, tenantID)

	if len(ret) == 0 {
		panic("no return value specified for CountCompaniesByTenant")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (int64, error)); ok {
		return returnFunc(ctx, tenantID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) int64); ok {
		r0 = returnFunc(ctx, tenantID)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, tenantID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CompanyRepository_CountCompaniesByTenant_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountCompaniesByTenant'
type CompanyRepository_CountCompaniesByTenant_Call struct {
	*mock.Call
}

// CountCompaniesByTenant is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID string
func (_e *CompanyRepository_Expecter) CountCompaniesByTenant(ctx interface{}, tenantID interface{}) *CompanyRepository_CountCompaniesByTenant_Call {
	return &CompanyRepository_CountCompaniesByTenant_Call{Call: _e.mock.On("CountCompaniesByTenant", ctx, tenantID)}
}

func (_c *CompanyRepository_CountCompaniesByTenant_Call) Run(run func(ctx context.Context, tenantID string)) *CompanyRepository_CountCompaniesByTenant_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CompanyRepository_CountCompaniesByTenant_Call) Return(n int64, err error) *CompanyRepository_CountCompaniesByTenant_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *CompanyRepository_CountCompaniesByTenant_Call) RunAndReturn(run func(ctx context.Context, tenantID string) (int64, error)) *CompanyRepository_CountCompaniesByTenant_Call {
	_c.Call.Return(run)
	return _c
}

// CreateCompany provides a mock function for the type CompanyRepository
func (_mock *CompanyRepository) CreateCompany(ctx context.Context, data coreentity.Company) (*coreentity.Company, error) {
	ret := _mock.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for CreateCompany")
	}

	var r0 *coreentity.Company
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.Company) (*coreentity.Company, error)); ok {
		return returnFunc(ctx, data)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.Company) *coreentity.Company); ok {
		r0 = returnFunc(ctx, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*coreentity.Company)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, coreentity.Company) error); ok {
		r1 = returnFunc(ctx, data)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CompanyRepository_CreateCompany_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateCompany'
type CompanyRepository_CreateCompany_Call struct {
	*mock.Call
}

// CreateCompany is a helper method to define mock.On call
//   - ctx context.Context
//   - data coreentity.Company
func (_e *CompanyRepository_Expecter) CreateCompany(ctx interface{}, data interface{}) *CompanyRepository_CreateCompany_Call {
	return &CompanyRepository_CreateCompany_Call{Call: _e.mock.On("CreateCompany", ctx, data)}
}

func (_c *CompanyRepository_CreateCompany_Call) Run(run func(ctx context.Context, data coreentity.Company)) *CompanyRepository_CreateCompany_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 coreentity.Company
		if args[1] != nil {
			arg1 = args[1].(coreentity.Company)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CompanyRepository_CreateCompany_Call) Return(company *coreentity.Company, err error) *CompanyRepository_CreateCompany_Call {
	_c.Call.Return(company, err)
	return _c
}

func (_c *CompanyRepository_CreateCompany_Call) RunAndReturn(run func(ctx context.Context, data coreentity.Company) (*coreentity.Company, error)) *CompanyRepository_CreateCompany_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteCompany provides a mock function for the type CompanyRepository
func (_mock *CompanyRepository) DeleteCompany(ctx context.Context, filter coreentity.CompanyDeleteFilter) error {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCompany")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.CompanyDeleteFilter) error); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// CompanyRepository_DeleteCompany_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteCompany'
type CompanyRepository_DeleteCompany_Call struct {
	*mock.Call
}

// DeleteCompany is a helper method to define mock.On call
//   - ctx context.Context
//   - filter coreentity.CompanyDeleteFilter
func (_e *CompanyRepository_Expecter) DeleteCompany(ctx interface{}, filter interface{}) *CompanyRepository_DeleteCompany_Call {
	return &CompanyRepository_DeleteCompany_Call{Call: _e.mock.On("DeleteCompany", ctx, filter)}
}

func (_c *CompanyRepository_DeleteCompany_Call) Run(run func(ctx context.Context, filter coreentity.CompanyDeleteFilter)) *CompanyRepository_DeleteCompany_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 coreentity.CompanyDeleteFilter
		if args[1] != nil {
			arg1 = args[1].(coreentity.CompanyDeleteFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CompanyRepository_DeleteCompany_Call) Return(err error) *CompanyRepository_DeleteCompany_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *CompanyRepository_DeleteCompany_Call) RunAndReturn(run func(ctx context.Context, filter coreentity.CompanyDeleteFilter) error) *CompanyRepository_DeleteCompany_Call {
	_c.Call.Return(run)
	return _c
}

// ExistsCompanyByCode provides a mock function for the type CompanyRepository
func (_mock *CompanyRepository) ExistsCompanyByCode(ctx context.Context, tenantID string, code string, excludeID string) (bool, error) {
	ret := _mock.Called(ctx, tenantID, code, excludeID)

	if len(ret) == 0 {
		panic("no return value specified for ExistsCompanyByCode")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) (bool, error)); ok {
		return returnFunc(ctx, tenantID, code, excludeID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) bool); ok {
		r0 = returnFunc(ctx, tenantID, code, excludeID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = returnFunc(ctx, tenantID, code, excludeID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CompanyRepository_ExistsCompanyByCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExistsCompanyByCode'
type CompanyRepository_ExistsCompanyByCode_Call struct {
	*mock.Call
}

// ExistsCompanyByCode is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID string
//   - code string
//   - excludeID string
func (_e *CompanyRepository_Expecter) ExistsCompanyByCode(ctx interface{}, tenantID interface{}, code interface{}, excludeID interface{}) *CompanyRepository_ExistsCompanyByCode_Call {
	return &CompanyRepository_ExistsCompanyByCode_Call{Call: _e.mock.On("ExistsCompanyByCode", ctx, tenantID, code, excludeID)}
}

func (_c *CompanyRepository_ExistsCompanyByCode_Call) Run(run func(ctx context.Context, tenantID string, code string, excludeID string)) *CompanyRepository_ExistsCompanyByCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *CompanyRepository_ExistsCompanyByCode_Call) Return(b bool, err error) *CompanyRepository_ExistsCompanyByCode_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *CompanyRepository_ExistsCompanyByCode_Call) RunAndReturn(run func(ctx context.Context, tenantID string, code string, excludeID string) (bool, error)) *CompanyRepository_ExistsCompanyByCode_Call {
	_c.Call.Return(run)
	return _c
}

// GetCompanies provides a mock function for the type CompanyRepository
func (_mock *CompanyRepository) GetCompanies(ctx context.Context, filter coreentity.CompanyListFilter) ([]coreentity.Company, int, error) {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetCompanies")
	}

	var r0 []coreentity.Company
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.CompanyListFilter) ([]coreentity.Company, int, error)); ok {
		return returnFunc(ctx, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.CompanyListFilter) []coreentity.Company); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]coreentity.Company)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, coreentity.CompanyListFilter) int); ok {
		r1 = returnFunc(ctx, filter)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, coreentity.CompanyListFilter) error); ok {
		r2 = returnFunc(ctx, filter)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// CompanyRepository_GetCompanies_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCompanies'
type CompanyRepository_GetCompanies_Call struct {
	*mock.Call
}

// GetCompanies is a helper method to define mock.On call
//   - ctx context.Context
//   - filter coreentity.CompanyListFilter
func (_e *CompanyRepository_Expecter) GetCompanies(ctx interface{}, filter interface{}) *CompanyRepository_GetCompanies_Call {
	return &CompanyRepository_GetCompanies_Call{Call: _e.mock.On("GetCompanies", ctx, filter)}
}

func (_c *CompanyRepository_GetCompanies_Call) Run(run func(ctx context.Context, filter coreentity.CompanyListFilter)) *CompanyRepository_GetCompanies_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 coreentity.CompanyListFilter
		if args[1] != nil {
			arg1 = args[1].(coreentity.CompanyListFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CompanyRepository_GetCompanies_Call) Return(companys []coreentity.Company, n int, err error) *CompanyRepository_GetCompanies_Call {
	_c.Call.Return(companys, n, err)
	return _c
}

func (_c *CompanyRepository_GetCompanies_Call) RunAndReturn(run func(ctx context.Context, filter coreentity.CompanyListFilter) ([]coreentity.Company, int, error)) *CompanyRepository_GetCompanies_Call {
	_c.Call.Return(run)
	return _c
}

// GetCompany provides a mock function for the type CompanyRepository
func (_mock *CompanyRepository) GetCompany(ctx context.Context, filter coreentity.Company) (*coreentity.Company, error) {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetCompany")
	}

	var r0 *coreentity.Company
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.Company) (*coreentity.Company, error)); ok {
		return returnFunc(ctx, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.Company) *coreentity.Company); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*coreentity.Company)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, coreentity.Company) error); ok {
		r1 = returnFunc(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CompanyRepository_GetCompany_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCompany'
type CompanyRepository_GetCompany_Call struct {
	*mock.Call
}

// GetCompany is a helper method to define mock.On call
//   - ctx context.Context
//   - filter coreentity.Company
func (_e *CompanyRepository_Expecter) GetCompany(ctx interface{}, filter interface{}) *CompanyRepository_GetCompany_Call {
	return &CompanyRepository_GetCompany_Call{Call: _e.mock.On("GetCompany", ctx, filter)}
}

func (_c *CompanyRepository_GetCompany_Call) Run(run func(ctx context.Context, filter coreentity.Company)) *CompanyRepository_GetCompany_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 coreentity.Company
		if args[1] != nil {
			arg1 = args[1].(coreentity.Company)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CompanyRepository_GetCompany_Call) Return(company *coreentity.Company, err error) *CompanyRepository_GetCompany_Call {
	_c.Call.Return(company, err)
	return _c
}

func (_c *CompanyRepository_GetCompany_Call) RunAndReturn(run func(ctx context.Context, filter coreentity.Company) (*coreentity.Company, error)) *CompanyRepository_GetCompany_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateCompany provides a mock function for the type CompanyRepository
func (_mock *CompanyRepository) UpdateCompany(ctx context.Context, data coreentity.Company) error {
	ret := _mock.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCompany")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.Company) error); ok {
		r0 = returnFunc(ctx, data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// CompanyRepository_UpdateCompany_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateCompany'
type CompanyRepository_UpdateCompany_Call struct {
	*mock.Call
}

// UpdateCompany is a helper method to define mock.On call
//   - ctx context.Context
//   - data coreentity.Company
func (_e *CompanyRepository_Expecter) UpdateCompany(ctx interface{}, data interface{}) *CompanyRepository_UpdateCompany_Call {
	return &CompanyRepository_UpdateCompany_Call{Call: _e.mock.On("UpdateCompany", ctx, data)}
}

func (_c *CompanyRepository_UpdateCompany_Call) Run(run func(ctx context.Context, data coreentity.Company)) *CompanyRepository_UpdateCompany_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 coreentity.Company
		if args[1] != nil {
			arg1 = args[1].(coreentity.Company)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CompanyRepository_UpdateCompany_Call) Return(err error) *CompanyRepository_UpdateCompany_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *CompanyRepository_UpdateCompany_Call) RunAndReturn(run func(ctx context.Context, data coreentity.Company) error) *CompanyRepository_UpdateCompany_Call {
	_c.Call.Return(run)
	return _c
}
