// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"codebase-app/internal/entity/coreentity"
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewEmployeeRepository creates a new instance of EmployeeRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEmployeeRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *EmployeeRepository {
	mock := &EmployeeRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// EmployeeRepository is an autogenerated mock type for the EmployeeRepository type
type EmployeeRepository struct {
	mock.Mock
}

type EmployeeRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *EmployeeRepository) EXPECT() *EmployeeRepository_Expecter {
	return &EmployeeRepository_Expecter{mock: &_m.Mock}
}

// AssignUser provides a mock function for the type EmployeeRepository
func (_mock *EmployeeRepository) AssignUser(ctx context.Context, tenantID string, employeeID string, userID string) error {
	ret := _mock.Called(ctx, tenantID, employeeID, userID)

	if len(ret) == 0 {
		panic("no return value specified for AssignUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = returnFunc(ctx, tenantID, employeeID, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// EmployeeRepository_AssignUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AssignUser'
type EmployeeRepository_AssignUser_Call struct {
	*mock.Call
}

// AssignUser is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID string
//   - employeeID string
//   - userID string
func (_e *EmployeeRepository_Expecter) AssignUser(ctx interface{}, tenantID interface{}, employeeID interface{}, userID interface{}) *EmployeeRepository_AssignUser_Call {
	return &EmployeeRepository_AssignUser_Call{Call: _e.mock.On("AssignUser", ctx, tenantID, employeeID, userID)}
}

func (_c *EmployeeRepository_AssignUser_Call) Run(run func(ctx context.Context, tenantID string, employeeID string, userID string)) *EmployeeRepository_AssignUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *EmployeeRepository_AssignUser_Call) Return(err error) *EmployeeRepository_AssignUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *EmployeeRepository_AssignUser_Call) RunAndReturn(run func(ctx context.Context, tenantID string, employeeID string, userID string) error) *EmployeeRepository_AssignUser_Call {
	_c.Call.Return(run)
	return _c
}

// CreateEmployee provides a mock function for the type EmployeeRepository
func (_mock *EmployeeRepository) CreateEmployee(ctx context.Context, data coreentity.Employee) (*coreentity.Employee, error) {
	ret := _mock.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for CreateEmployee")
	}

	var r0 *coreentity.Employee
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.Employee) (*coreentity.Employee, error)); ok {
		return returnFunc(ctx, data)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.Employee) *coreentity.Employee); ok {
		r0 = returnFunc(ctx, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*coreentity.Employee)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, coreentity.Employee) error); ok {
		r1 = returnFunc(ctx, data)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// EmployeeRepository_CreateEmployee_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateEmployee'
type EmployeeRepository_CreateEmployee_Call struct {
	*mock.Call
}

// CreateEmployee is a helper method to define mock.On call
//   - ctx context.Context
//   - data coreentity.Employee
func (_e *EmployeeRepository_Expecter) CreateEmployee(ctx interface{}, data interface{}) *EmployeeRepository_CreateEmployee_Call {
	return &EmployeeRepository_CreateEmployee_Call{Call: _e.mock.On("CreateEmployee", ctx, data)}
}

func (_c *EmployeeRepository_CreateEmployee_Call) Run(run func(ctx context.Context, data coreentity.Employee)) *EmployeeRepository_CreateEmployee_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 coreentity.Employee
		if args[1] != nil {
			arg1 = args[1].(coreentity.Employee)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *EmployeeRepository_CreateEmployee_Call) Return(employee *coreentity.Employee, err error) *EmployeeRepository_CreateEmployee_Call {
	_c.Call.Return(employee, err)
	return _c
}

func (_c *EmployeeRepository_CreateEmployee_Call) RunAndReturn(run func(ctx context.Context, data coreentity.Employee) (*coreentity.Employee, error)) *EmployeeRepository_CreateEmployee_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteEmployee provides a mock function for the type EmployeeRepository
func (_mock *EmployeeRepository) DeleteEmployee(ctx context.Context, filter coreentity.EmployeeDeleteFilter) error {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for DeleteEmployee")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.EmployeeDeleteFilter) error); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// EmployeeRepository_DeleteEmployee_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteEmployee'
type EmployeeRepository_DeleteEmployee_Call struct {
	*mock.Call
}

// DeleteEmployee is a helper method to define mock.On call
//   - ctx context.Context
//   - filter coreentity.EmployeeDeleteFilter
func (_e *EmployeeRepository_Expecter) DeleteEmployee(ctx interface{}, filter interface{}) *EmployeeRepository_DeleteEmployee_Call {
	return &EmployeeRepository_DeleteEmployee_Call{Call: _e.mock.On("DeleteEmployee", ctx, filter)}
}

func (_c *EmployeeRepository_DeleteEmployee_Call) Run(run func(ctx context.Context, filter coreentity.EmployeeDeleteFilter)) *EmployeeRepository_DeleteEmployee_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 coreentity.EmployeeDeleteFilter
		if args[1] != nil {
			arg1 = args[1].(coreentity.EmployeeDeleteFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *EmployeeRepository_DeleteEmployee_Call) Return(err error) *EmployeeRepository_DeleteEmployee_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *EmployeeRepository_DeleteEmployee_Call) RunAndReturn(run func(ctx context.Context, filter coreentity.EmployeeDeleteFilter) error) *EmployeeRepository_DeleteEmployee_Call {
	_c.Call.Return(run)
	return _c
}

// ExistsByEmployeeNo provides a mock function for the type EmployeeRepository
func (_mock *EmployeeRepository) ExistsByEmployeeNo(ctx context.Context, tenantID string, employeeNo string, excludeID string) (bool, error) {
	ret := _mock.Called(ctx, tenantID, employeeNo, excludeID)

	if len(ret) == 0 {
		panic("no return value specified for ExistsByEmployeeNo")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) (bool, error)); ok {
		return returnFunc(ctx, tenantID, employeeNo, excludeID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) bool); ok {
		r0 = returnFunc(ctx, tenantID, employeeNo, excludeID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = returnFunc(ctx, tenantID, employeeNo, excludeID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// EmployeeRepository_ExistsByEmployeeNo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExistsByEmployeeNo'
type EmployeeRepository_ExistsByEmployeeNo_Call struct {
	*mock.Call
}

// ExistsByEmployeeNo is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID string
//   - employeeNo string
//   - excludeID string
func (_e *EmployeeRepository_Expecter) ExistsByEmployeeNo(ctx interface{}, tenantID interface{}, employeeNo interface{}, excludeID interface{}) *EmployeeRepository_ExistsByEmployeeNo_Call {
	return &EmployeeRepository_ExistsByEmployeeNo_Call{Call: _e.mock.On("ExistsByEmployeeNo", ctx, tenantID, employeeNo, excludeID)}
}

func (_c *EmployeeRepository_ExistsByEmployeeNo_Call) Run(run func(ctx context.Context, tenantID string, employeeNo string, excludeID string)) *EmployeeRepository_ExistsByEmployeeNo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *EmployeeRepository_ExistsByEmployeeNo_Call) Return(b bool, err error) *EmployeeRepository_ExistsByEmployeeNo_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *EmployeeRepository_ExistsByEmployeeNo_Call) RunAndReturn(run func(ctx context.Context, tenantID string, employeeNo string, excludeID string) (bool, error)) *EmployeeRepository_ExistsByEmployeeNo_Call {
	_c.Call.Return(run)
	return _c
}

// GetEmployee provides a mock function for the type EmployeeRepository
func (_mock *EmployeeRepository) GetEmployee(ctx context.Context, filter coreentity.Employee) (*coreentity.Employee, error) {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetEmployee")
	}

	var r0 *coreentity.Employee
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.Employee) (*coreentity.Employee, error)); ok {
		return returnFunc(ctx, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.Employee) *coreentity.Employee); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*coreentity.Employee)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, coreentity.Employee) error); ok {
		r1 = returnFunc(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// EmployeeRepository_GetEmployee_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEmployee'
type EmployeeRepository_GetEmployee_Call struct {
	*mock.Call
}

// GetEmployee is a helper method to define mock.On call
//   - ctx context.Context
//   - filter coreentity.Employee
func (_e *EmployeeRepository_Expecter) GetEmployee(ctx interface{}, filter interface{}) *EmployeeRepository_GetEmployee_Call {
	return &EmployeeRepository_GetEmployee_Call{Call: _e.mock.On("GetEmployee", ctx, filter)}
}

func (_c *EmployeeRepository_GetEmployee_Call) Run(run func(ctx context.Context, filter coreentity.Employee)) *EmployeeRepository_GetEmployee_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 coreentity.Employee
		if args[1] != nil {
			arg1 = args[1].(coreentity.Employee)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *EmployeeRepository_GetEmployee_Call) Return(employee *coreentity.Employee, err error) *EmployeeRepository_GetEmployee_Call {
	_c.Call.Return(employee, err)
	return _c
}

func (_c *EmployeeRepository_GetEmployee_Call) RunAndReturn(run func(ctx context.Context, filter coreentity.Employee) (*coreentity.Employee, error)) *EmployeeRepository_GetEmployee_Call {
	_c.Call.Return(run)
	return _c
}

// GetEmployees provides a mock function for the type EmployeeRepository
func (_mock *EmployeeRepository) GetEmployees(ctx context.Context, filter coreentity.EmployeeListFilter) ([]coreentity.Employee, int, error) {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetEmployees")
	}

	var r0 []coreentity.Employee
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.EmployeeListFilter) ([]coreentity.Employee, int, error)); ok {
		return returnFunc(ctx, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.EmployeeListFilter) []coreentity.Employee); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]coreentity.Employee)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, coreentity.EmployeeListFilter) int); ok {
		r1 = returnFunc(ctx, filter)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, coreentity.EmployeeListFilter) error); ok {
		r2 = returnFunc(ctx, filter)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// EmployeeRepository_GetEmployees_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEmployees'
type EmployeeRepository_GetEmployees_Call struct {
	*mock.Call
}

// GetEmployees is a helper method to define mock.On call
//   - ctx context.Context
//   - filter coreentity.EmployeeListFilter
func (_e *EmployeeRepository_Expecter) GetEmployees(ctx interface{}, filter interface{}) *EmployeeRepository_GetEmployees_Call {
	return &EmployeeRepository_GetEmployees_Call{Call: _e.mock.On("GetEmployees", ctx, filter)}
}

func (_c *EmployeeRepository_GetEmployees_Call) Run(run func(ctx context.Context, filter coreentity.EmployeeListFilter)) *EmployeeRepository_GetEmployees_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 coreentity.EmployeeListFilter
		if args[1] != nil {
			arg1 = args[1].(coreentity.EmployeeListFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *EmployeeRepository_GetEmployees_Call) Return(employees []coreentity.Employee, n int, err error) *EmployeeRepository_GetEmployees_Call {
	_c.Call.Return(employees, n, err)
	return _c
}

func (_c *EmployeeRepository_GetEmployees_Call) RunAndReturn(run func(ctx context.Context, filter coreentity.EmployeeListFilter) ([]coreentity.Employee, int, error)) *EmployeeRepository_GetEmployees_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateEmployee provides a mock function for the type EmployeeRepository
func (_mock *EmployeeRepository) UpdateEmployee(ctx context.Context, data coreentity.Employee) error {
	ret := _mock.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for UpdateEmployee")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.Employee) error); ok {
		r0 = returnFunc(ctx, data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// EmployeeRepository_UpdateEmployee_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateEmployee'
type EmployeeRepository_UpdateEmployee_Call struct {
	*mock.Call
}

// UpdateEmployee is a helper method to define mock.On call
//   - ctx context.Context
//   - data coreentity.Employee
func (_e *EmployeeRepository_Expecter) UpdateEmployee(ctx interface{}, data interface{}) *EmployeeRepository_UpdateEmployee_Call {
	return &EmployeeRepository_UpdateEmployee_Call{Call: _e.mock.On("UpdateEmployee", ctx, data)}
}

func (_c *EmployeeRepository_UpdateEmployee_Call) Run(run func(ctx context.Context, data coreentity.Employee)) *EmployeeRepository_UpdateEmployee_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 coreentity.Employee
		if args[1] != nil {
			arg1 = args[1].(coreentity.Employee)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *EmployeeRepository_UpdateEmployee_Call) Return(err error) *EmployeeRepository_UpdateEmployee_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *EmployeeRepository_UpdateEmployee_Call) RunAndReturn(run func(ctx context.Context, data coreentity.Employee) error) *EmployeeRepository_UpdateEmployee_Call {
	_c.Call.Return(run)
	return _c
}
