// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"codebase-app/internal/entity/coreentity"
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewExportJobRepository creates a new instance of ExportJobRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewExportJobRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ExportJobRepository {
	mock := &ExportJobRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ExportJobRepository is an autogenerated mock type for the ExportJobRepository type
type ExportJobRepository struct {
	mock.Mock
}

type ExportJobRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *ExportJobRepository) EXPECT() *ExportJobRepository_Expecter {
	return &ExportJobRepository_Expecter{mock: &_m.Mock}
}

// ClaimPendingExportJob provides a mock function for the type ExportJobRepository
func (_mock *ExportJobRepository) ClaimPendingExportJob(ctx context.Context) (*coreentity.ExportJob, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ClaimPendingExportJob")
	}

	var r0 *coreentity.ExportJob
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*coreentity.ExportJob, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *coreentity.ExportJob); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*coreentity.ExportJob)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ExportJobRepository_ClaimPendingExportJob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClaimPendingExportJob'
type ExportJobRepository_ClaimPendingExportJob_Call struct {
	*mock.Call
}

// ClaimPendingExportJob is a helper method to define mock.On call
//   - ctx context.Context
func (_e *ExportJobRepository_Expecter) ClaimPendingExportJob(ctx interface{}) *ExportJobRepository_ClaimPendingExportJob_Call {
	return &ExportJobRepository_ClaimPendingExportJob_Call{Call: _e.mock.On("ClaimPendingExportJob", ctx)}
}

func (_c *ExportJobRepository_ClaimPendingExportJob_Call) Run(run func(ctx context.Context)) *ExportJobRepository_ClaimPendingExportJob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ExportJobRepository_ClaimPendingExportJob_Call) Return(exportJob *coreentity.ExportJob, err error) *ExportJobRepository_ClaimPendingExportJob_Call {
	_c.Call.Return(exportJob, err)
	return _c
}

func (_c *ExportJobRepository_ClaimPendingExportJob_Call) RunAndReturn(run func(ctx context.Context) (*coreentity.ExportJob, error)) *ExportJobRepository_ClaimPendingExportJob_Call {
	_c.Call.Return(run)
	return _c
}

// CreateExportJob provides a mock function for the type ExportJobRepository
func (_mock *ExportJobRepository) CreateExportJob(ctx context.Context, data coreentity.ExportJobCreate) (*coreentity.ExportJob, error) {
	ret := _mock.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for CreateExportJob")
	}

	var r0 *coreentity.ExportJob
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.ExportJobCreate) (*coreentity.ExportJob, error)); ok {
		return returnFunc(ctx, data)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.ExportJobCreate) *coreentity.ExportJob); ok {
		r0 = returnFunc(ctx, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*coreentity.ExportJob)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, coreentity.ExportJobCreate) error); ok {
		r1 = returnFunc(ctx, data)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ExportJobRepository_CreateExportJob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateExportJob'
type ExportJobRepository_CreateExportJob_Call struct {
	*mock.Call
}

// CreateExportJob is a helper method to define mock.On call
//   - ctx context.Context
//   - data coreentity.ExportJobCreate
func (_e *ExportJobRepository_Expecter) CreateExportJob(ctx interface{}, data interface{}) *ExportJobRepository_CreateExportJob_Call {
	return &ExportJobRepository_CreateExportJob_Call{Call: _e.mock.On("CreateExportJob", ctx, data)}
}

func (_c *ExportJobRepository_CreateExportJob_Call) Run(run func(ctx context.Context, data coreentity.ExportJobCreate)) *ExportJobRepository_CreateExportJob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 coreentity.ExportJobCreate
		if args[1] != nil {
			arg1 = args[1].(coreentity.ExportJobCreate)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ExportJobRepository_CreateExportJob_Call) Return(exportJob *coreentity.ExportJob, err error) *ExportJobRepository_CreateExportJob_Call {
	_c.Call.Return(exportJob, err)
	return _c
}

func (_c *ExportJobRepository_CreateExportJob_Call) RunAndReturn(run func(ctx context.Context, data coreentity.ExportJobCreate) (*coreentity.ExportJob, error)) *ExportJobRepository_CreateExportJob_Call {
	_c.Call.Return(run)
	return _c
}

// GetExportJob provides a mock function for the type ExportJobRepository
func (_mock *ExportJobRepository) GetExportJob(ctx context.Context, filter coreentity.ExportJobDetailFilter) (*coreentity.ExportJob, error) {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetExportJob")
	}

	var r0 *coreentity.ExportJob
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.ExportJobDetailFilter) (*coreentity.ExportJob, error)); ok {
		return returnFunc(ctx, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.ExportJobDetailFilter) *coreentity.ExportJob); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*coreentity.ExportJob)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, coreentity.ExportJobDetailFilter) error); ok {
		r1 = returnFunc(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ExportJobRepository_GetExportJob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetExportJob'
type ExportJobRepository_GetExportJob_Call struct {
	*mock.Call
}

// GetExportJob is a helper method to define mock.On call
//   - ctx context.Context
//   - filter coreentity.ExportJobDetailFilter
func (_e *ExportJobRepository_Expecter) GetExportJob(ctx interface{}, filter interface{}) *ExportJobRepository_GetExportJob_Call {
	return &ExportJobRepository_GetExportJob_Call{Call: _e.mock.On("GetExportJob", ctx, filter)}
}

func (_c *ExportJobRepository_GetExportJob_Call) Run(run func(ctx context.Context, filter coreentity.ExportJobDetailFilter)) *ExportJobRepository_GetExportJob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 coreentity.ExportJobDetailFilter
		if args[1] != nil {
			arg1 = args[1].(coreentity.ExportJobDetailFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ExportJobRepository_GetExportJob_Call) Return(exportJob *coreentity.ExportJob, err error) *ExportJobRepository_GetExportJob_Call {
	_c.Call.Return(exportJob, err)
	return _c
}

func (_c *ExportJobRepository_GetExportJob_Call) RunAndReturn(run func(ctx context.Context, filter coreentity.ExportJobDetailFilter) (*coreentity.ExportJob, error)) *ExportJobRepository_GetExportJob_Call {
	_c.Call.Return(run)
	return _c
}

// GetExportJobs provides a mock function for the type ExportJobRepository
func (_mock *ExportJobRepository) GetExportJobs(ctx context.Context, filter coreentity.ExportJobListFilter) ([]coreentity.ExportJob, int, error) {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetExportJobs")
	}

	var r0 []coreentity.ExportJob
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.ExportJobListFilter) ([]coreentity.ExportJob, int, error)); ok {
		return returnFunc(ctx, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.ExportJobListFilter) []coreentity.ExportJob); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]coreentity.ExportJob)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, coreentity.ExportJobListFilter) int); ok {
		r1 = returnFunc(ctx, filter)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, coreentity.ExportJobListFilter) error); ok {
		r2 = returnFunc(ctx, filter)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// ExportJobRepository_GetExportJobs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetExportJobs'
type ExportJobRepository_GetExportJobs_Call struct {
	*mock.Call
}

// GetExportJobs is a helper method to define mock.On call
//   - ctx context.Context
//   - filter coreentity.ExportJobListFilter
func (_e *ExportJobRepository_Expecter) GetExportJobs(ctx interface{}, filter interface{}) *ExportJobRepository_GetExportJobs_Call {
	return &ExportJobRepository_GetExportJobs_Call{Call: _e.mock.On("GetExportJobs", ctx, filter)}
}

func (_c *ExportJobRepository_GetExportJobs_Call) Run(run func(ctx context.Context, filter coreentity.ExportJobListFilter)) *ExportJobRepository_GetExportJobs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 coreentity.ExportJobListFilter
		if args[1] != nil {
			arg1 = args[1].(coreentity.ExportJobListFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ExportJobRepository_GetExportJobs_Call) Return(exportJobs []coreentity.ExportJob, n int, err error) *ExportJobRepository_GetExportJobs_Call {
	_c.Call.Return(exportJobs, n, err)
	return _c
}

func (_c *ExportJobRepository_GetExportJobs_Call) RunAndReturn(run func(ctx context.Context, filter coreentity.ExportJobListFilter) ([]coreentity.ExportJob, int, error)) *ExportJobRepository_GetExportJobs_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateExportJob provides a mock function for the type ExportJobRepository
func (_mock *ExportJobRepository) UpdateExportJob(ctx context.Context, data coreentity.ExportJobUpdate) error {
	ret := _mock.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for UpdateExportJob")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.ExportJobUpdate) error); ok {
		r0 = returnFunc(ctx, data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ExportJobRepository_UpdateExportJob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateExportJob'
type ExportJobRepository_UpdateExportJob_Call struct {
	*mock.Call
}

// UpdateExportJob is a helper method to define mock.On call
//   - ctx context.Context
//   - data coreentity.ExportJobUpdate
func (_e *ExportJobRepository_Expecter) UpdateExportJob(ctx interface{}, data interface{}) *ExportJobRepository_UpdateExportJob_Call {
	return &ExportJobRepository_UpdateExportJob_Call{Call: _e.mock.On("UpdateExportJob", ctx, data)}
}

func (_c *ExportJobRepository_UpdateExportJob_Call) Run(run func(ctx context.Context, data coreentity.ExportJobUpdate)) *ExportJobRepository_UpdateExportJob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 coreentity.ExportJobUpdate
		if args[1] != nil {
			arg1 = args[1].(coreentity.ExportJobUpdate)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ExportJobRepository_UpdateExportJob_Call) Return(err error) *ExportJobRepository_UpdateExportJob_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ExportJobRepository_UpdateExportJob_Call) RunAndReturn(run func(ctx context.Context, data coreentity.ExportJobUpdate) error) *ExportJobRepository_UpdateExportJob_Call {
	_c.Call.Return(run)
	return _c
}
