// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"codebase-app/internal/entity/coreentity"
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewInternalClientRepository creates a new instance of InternalClientRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInternalClientRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *InternalClientRepository {
	mock := &InternalClientRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// InternalClientRepository is an autogenerated mock type for the InternalClientRepository type
type InternalClientRepository struct {
	mock.Mock
}

type InternalClientRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *InternalClientRepository) EXPECT() *InternalClientRepository_Expecter {
	return &InternalClientRepository_Expecter{mock: &_m.Mock}
}

// GetInternalClientOwnerPermissions provides a mock function for the type InternalClientRepository
func (_mock *InternalClientRepository) GetInternalClientOwnerPermissions(ctx context.Context, clientID string) (*coreentity.InternalClientOwnerPermissions, error) {
	ret := _mock.Called(ctx, clientID)

	if len(ret) == 0 {
		panic("no return value specified for GetInternalClientOwnerPermissions")
	}

	var r0 *coreentity.InternalClientOwnerPermissions
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*coreentity.InternalClientOwnerPermissions, error)); ok {
		return returnFunc(ctx, clientID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *coreentity.InternalClientOwnerPermissions); ok {
		r0 = returnFunc(ctx, clientID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*coreentity.InternalClientOwnerPermissions)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, clientID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// InternalClientRepository_GetInternalClientOwnerPermissions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInternalClientOwnerPermissions'
type InternalClientRepository_GetInternalClientOwnerPermissions_Call struct {
	*mock.Call
}

// GetInternalClientOwnerPermissions is a helper method to define mock.On call
//   - ctx context.Context
//   - clientID string
func (_e *InternalClientRepository_Expecter) GetInternalClientOwnerPermissions(ctx interface{}, clientID interface{}) *InternalClientRepository_GetInternalClientOwnerPermissions_Call {
	return &InternalClientRepository_GetInternalClientOwnerPermissions_Call{Call: _e.mock.On("GetInternalClientOwnerPermissions", ctx, clientID)}
}

func (_c *InternalClientRepository_GetInternalClientOwnerPermissions_Call) Run(run func(ctx context.Context, clientID string)) *InternalClientRepository_GetInternalClientOwnerPermissions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *InternalClientRepository_GetInternalClientOwnerPermissions_Call) Return(internalClientOwnerPermissions *coreentity.InternalClientOwnerPermissions, err error) *InternalClientRepository_GetInternalClientOwnerPermissions_Call {
	_c.Call.Return(internalClientOwnerPermissions, err)
	return _c
}

func (_c *InternalClientRepository_GetInternalClientOwnerPermissions_Call) RunAndReturn(run func(ctx context.Context, clientID string) (*coreentity.InternalClientOwnerPermissions, error)) *InternalClientRepository_GetInternalClientOwnerPermissions_Call {
	_c.Call.Return(run)
	return _c
}

// GetInternalClients provides a mock function for the type InternalClientRepository
func (_mock *InternalClientRepository) GetInternalClients(ctx context.Context, filter coreentity.InternalClientListFilter) ([]coreentity.InternalClient, int, error) {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetInternalClients")
	}

	var r0 []coreentity.InternalClient
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.InternalClientListFilter) ([]coreentity.InternalClient, int, error)); ok {
		return returnFunc(ctx, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.InternalClientListFilter) []coreentity.InternalClient); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]coreentity.InternalClient)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, coreentity.InternalClientListFilter) int); ok {
		r1 = returnFunc(ctx, filter)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, coreentity.InternalClientListFilter) error); ok {
		r2 = returnFunc(ctx, filter)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// InternalClientRepository_GetInternalClients_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInternalClients'
type InternalClientRepository_GetInternalClients_Call struct {
	*mock.Call
}

// GetInternalClients is a helper method to define mock.On call
//   - ctx context.Context
//   - filter coreentity.InternalClientListFilter
func (_e *InternalClientRepository_Expecter) GetInternalClients(ctx interface{}, filter interface{}) *InternalClientRepository_GetInternalClients_Call {
	return &InternalClientRepository_GetInternalClients_Call{Call: _e.mock.On("GetInternalClients", ctx, filter)}
}

func (_c *InternalClientRepository_GetInternalClients_Call) Run(run func(ctx context.Context, filter coreentity.InternalClientListFilter)) *InternalClientRepository_GetInternalClients_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 coreentity.InternalClientListFilter
		if args[1] != nil {
			arg1 = args[1].(coreentity.InternalClientListFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *InternalClientRepository_GetInternalClients_Call) Return(internalClients []coreentity.InternalClient, n int, err error) *InternalClientRepository_GetInternalClients_Call {
	_c.Call.Return(internalClients, n, err)
	return _c
}

func (_c *InternalClientRepository_GetInternalClients_Call) RunAndReturn(run func(ctx context.Context, filter coreentity.InternalClientListFilter) ([]coreentity.InternalClient, int, error)) *InternalClientRepository_GetInternalClients_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateInternalClientOwnerPermissions provides a mock function for the type InternalClientRepository
func (_mock *InternalClientRepository) UpdateInternalClientOwnerPermissions(ctx context.Context, data coreentity.InternalClientOwnerPermissionUpdate) error {
	ret := _mock.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for UpdateInternalClientOwnerPermissions")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.InternalClientOwnerPermissionUpdate) error); ok {
		r0 = returnFunc(ctx, data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// InternalClientRepository_UpdateInternalClientOwnerPermissions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateInternalClientOwnerPermissions'
type InternalClientRepository_UpdateInternalClientOwnerPermissions_Call struct {
	*mock.Call
}

// UpdateInternalClientOwnerPermissions is a helper method to define mock.On call
//   - ctx context.Context
//   - data coreentity.InternalClientOwnerPermissionUpdate
func (_e *InternalClientRepository_Expecter) UpdateInternalClientOwnerPermissions(ctx interface{}, data interface{}) *InternalClientRepository_UpdateInternalClientOwnerPermissions_Call {
	return &InternalClientRepository_UpdateInternalClientOwnerPermissions_Call{Call: _e.mock.On("UpdateInternalClientOwnerPermissions", ctx, data)}
}

func (_c *InternalClientRepository_UpdateInternalClientOwnerPermissions_Call) Run(run func(ctx context.Context, data coreentity.InternalClientOwnerPermissionUpdate)) *InternalClientRepository_UpdateInternalClientOwnerPermissions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 coreentity.InternalClientOwnerPermissionUpdate
		if args[1] != nil {
			arg1 = args[1].(coreentity.InternalClientOwnerPermissionUpdate)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *InternalClientRepository_UpdateInternalClientOwnerPermissions_Call) Return(err error) *InternalClientRepository_UpdateInternalClientOwnerPermissions_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *InternalClientRepository_UpdateInternalClientOwnerPermissions_Call) RunAndReturn(run func(ctx context.Context, data coreentity.InternalClientOwnerPermissionUpdate) error) *InternalClientRepository_UpdateInternalClientOwnerPermissions_Call {
	_c.Call.Return(run)
	return _c
}
