// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"codebase-app/internal/entity/coreentity"
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewInternalUserRepository creates a new instance of InternalUserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInternalUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *InternalUserRepository {
	mock := &InternalUserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// InternalUserRepository is an autogenerated mock type for the InternalUserRepository type
type InternalUserRepository struct {
	mock.Mock
}

type InternalUserRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *InternalUserRepository) EXPECT() *InternalUserRepository_Expecter {
	return &InternalUserRepository_Expecter{mock: &_m.Mock}
}

// CreateInternalUser provides a mock function for the type InternalUserRepository
func (_mock *InternalUserRepository) CreateInternalUser(ctx context.Context, data coreentity.InternalUser) (*coreentity.InternalUser, error) {
	ret := _mock.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for CreateInternalUser")
	}

	var r0 *coreentity.InternalUser
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.InternalUser) (*coreentity.InternalUser, error)); ok {
		return returnFunc(ctx, data)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.InternalUser) *coreentity.InternalUser); ok {
		r0 = returnFunc(ctx, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*coreentity.InternalUser)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, coreentity.InternalUser) error); ok {
		r1 = returnFunc(ctx, data)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// InternalUserRepository_CreateInternalUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateInternalUser'
type InternalUserRepository_CreateInternalUser_Call struct {
	*mock.Call
}

// CreateInternalUser is a helper method to define mock.On call
//   - ctx context.Context
//   - data coreentity.InternalUser
func (_e *InternalUserRepository_Expecter) CreateInternalUser(ctx interface{}, data interface{}) *InternalUserRepository_CreateInternalUser_Call {
	return &InternalUserRepository_CreateInternalUser_Call{Call: _e.mock.On("CreateInternalUser", ctx, data)}
}

func (_c *InternalUserRepository_CreateInternalUser_Call) Run(run func(ctx context.Context, data coreentity.InternalUser)) *InternalUserRepository_CreateInternalUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 coreentity.InternalUser
		if args[1] != nil {
			arg1 = args[1].(coreentity.InternalUser)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *InternalUserRepository_CreateInternalUser_Call) Return(internalUser *coreentity.InternalUser, err error) *InternalUserRepository_CreateInternalUser_Call {
	_c.Call.Return(internalUser, err)
	return _c
}

func (_c *InternalUserRepository_CreateInternalUser_Call) RunAndReturn(run func(ctx context.Context, data coreentity.InternalUser) (*coreentity.InternalUser, error)) *InternalUserRepository_CreateInternalUser_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteInternalUser provides a mock function for the type InternalUserRepository
func (_mock *InternalUserRepository) DeleteInternalUser(ctx context.Context, filter coreentity.InternalUserDeleteFilter) error {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for DeleteInternalUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.InternalUserDeleteFilter) error); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// InternalUserRepository_DeleteInternalUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteInternalUser'
type InternalUserRepository_DeleteInternalUser_Call struct {
	*mock.Call
}

// DeleteInternalUser is a helper method to define mock.On call
//   - ctx context.Context
//   - filter coreentity.InternalUserDeleteFilter
func (_e *InternalUserRepository_Expecter) DeleteInternalUser(ctx interface{}, filter interface{}) *InternalUserRepository_DeleteInternalUser_Call {
	return &InternalUserRepository_DeleteInternalUser_Call{Call: _e.mock.On("DeleteInternalUser", ctx, filter)}
}

func (_c *InternalUserRepository_DeleteInternalUser_Call) Run(run func(ctx context.Context, filter coreentity.InternalUserDeleteFilter)) *InternalUserRepository_DeleteInternalUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 coreentity.InternalUserDeleteFilter
		if args[1] != nil {
			arg1 = args[1].(coreentity.InternalUserDeleteFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *InternalUserRepository_DeleteInternalUser_Call) Return(err error) *InternalUserRepository_DeleteInternalUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *InternalUserRepository_DeleteInternalUser_Call) RunAndReturn(run func(ctx context.Context, filter coreentity.InternalUserDeleteFilter) error) *InternalUserRepository_DeleteInternalUser_Call {
	_c.Call.Return(run)
	return _c
}

// ExistsInternalUserByEmail provides a mock function for the type InternalUserRepository
func (_mock *InternalUserRepository) ExistsInternalUserByEmail(ctx context.Context, email string, excludeID string) (bool, error) {
	ret := _mock.Called(ctx, email, excludeID)

	if len(ret) == 0 {
		panic("no return value specified for ExistsInternalUserByEmail")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (bool, error)); ok {
		return returnFunc(ctx, email, excludeID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = returnFunc(ctx, email, excludeID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, email, excludeID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// InternalUserRepository_ExistsInternalUserByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExistsInternalUserByEmail'
type InternalUserRepository_ExistsInternalUserByEmail_Call struct {
	*mock.Call
}

// ExistsInternalUserByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - excludeID string
func (_e *InternalUserRepository_Expecter) ExistsInternalUserByEmail(ctx interface{}, email interface{}, excludeID interface{}) *InternalUserRepository_ExistsInternalUserByEmail_Call {
	return &InternalUserRepository_ExistsInternalUserByEmail_Call{Call: _e.mock.On("ExistsInternalUserByEmail", ctx, email, excludeID)}
}

func (_c *InternalUserRepository_ExistsInternalUserByEmail_Call) Run(run func(ctx context.Context, email string, excludeID string)) *InternalUserRepository_ExistsInternalUserByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *InternalUserRepository_ExistsInternalUserByEmail_Call) Return(b bool, err error) *InternalUserRepository_ExistsInternalUserByEmail_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *InternalUserRepository_ExistsInternalUserByEmail_Call) RunAndReturn(run func(ctx context.Context, email string, excludeID string) (bool, error)) *InternalUserRepository_ExistsInternalUserByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// FindActiveInternalUserByEmail provides a mock function for the type InternalUserRepository
func (_mock *InternalUserRepository) FindActiveInternalUserByEmail(ctx context.Context, email string) (*coreentity.InternalUser, error) {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for FindActiveInternalUserByEmail")
	}

	var r0 *coreentity.InternalUser
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*coreentity.InternalUser, error)); ok {
		return returnFunc(ctx, email)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *coreentity.InternalUser); ok {
		r0 = returnFunc(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*coreentity.InternalUser)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// InternalUserRepository_FindActiveInternalUserByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindActiveInternalUserByEmail'
type InternalUserRepository_FindActiveInternalUserByEmail_Call struct {
	*mock.Call
}

// FindActiveInternalUserByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *InternalUserRepository_Expecter) FindActiveInternalUserByEmail(ctx interface{}, email interface{}) *InternalUserRepository_FindActiveInternalUserByEmail_Call {
	return &InternalUserRepository_FindActiveInternalUserByEmail_Call{Call: _e.mock.On("FindActiveInternalUserByEmail", ctx, email)}
}

func (_c *InternalUserRepository_FindActiveInternalUserByEmail_Call) Run(run func(ctx context.Context, email string)) *InternalUserRepository_FindActiveInternalUserByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *InternalUserRepository_FindActiveInternalUserByEmail_Call) Return(internalUser *coreentity.InternalUser, err error) *InternalUserRepository_FindActiveInternalUserByEmail_Call {
	_c.Call.Return(internalUser, err)
	return _c
}

func (_c *InternalUserRepository_FindActiveInternalUserByEmail_Call) RunAndReturn(run func(ctx context.Context, email string) (*coreentity.InternalUser, error)) *InternalUserRepository_FindActiveInternalUserByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// GetInternalUser provides a mock function for the type InternalUserRepository
func (_mock *InternalUserRepository) GetInternalUser(ctx context.Context, filter coreentity.InternalUserFilter) (*coreentity.InternalUser, error) {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetInternalUser")
	}

	var r0 *coreentity.InternalUser
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.InternalUserFilter) (*coreentity.InternalUser, error)); ok {
		return returnFunc(ctx, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.InternalUserFilter) *coreentity.InternalUser); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*coreentity.InternalUser)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, coreentity.InternalUserFilter) error); ok {
		r1 = returnFunc(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// InternalUserRepository_GetInternalUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInternalUser'
type InternalUserRepository_GetInternalUser_Call struct {
	*mock.Call
}

// GetInternalUser is a helper method to define mock.On call
//   - ctx context.Context
//   - filter coreentity.InternalUserFilter
func (_e *InternalUserRepository_Expecter) GetInternalUser(ctx interface{}, filter interface{}) *InternalUserRepository_GetInternalUser_Call {
	return &InternalUserRepository_GetInternalUser_Call{Call: _e.mock.On("GetInternalUser", ctx, filter)}
}

func (_c *InternalUserRepository_GetInternalUser_Call) Run(run func(ctx context.Context, filter coreentity.InternalUserFilter)) *InternalUserRepository_GetInternalUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 coreentity.InternalUserFilter
		if args[1] != nil {
			arg1 = args[1].(coreentity.InternalUserFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *InternalUserRepository_GetInternalUser_Call) Return(internalUser *coreentity.InternalUser, err error) *InternalUserRepository_GetInternalUser_Call {
	_c.Call.Return(internalUser, err)
	return _c
}

func (_c *InternalUserRepository_GetInternalUser_Call) RunAndReturn(run func(ctx context.Context, filter coreentity.InternalUserFilter) (*coreentity.InternalUser, error)) *InternalUserRepository_GetInternalUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetInternalUsers provides a mock function for the type InternalUserRepository
func (_mock *InternalUserRepository) GetInternalUsers(ctx context.Context, filter coreentity.InternalUserListFilter) ([]coreentity.InternalUser, int, error) {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetInternalUsers")
	}

	var r0 []coreentity.InternalUser
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.InternalUserListFilter) ([]coreentity.InternalUser, int, error)); ok {
		return returnFunc(ctx, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.InternalUserListFilter) []coreentity.InternalUser); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]coreentity.InternalUser)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, coreentity.InternalUserListFilter) int); ok {
		r1 = returnFunc(ctx, filter)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, coreentity.InternalUserListFilter) error); ok {
		r2 = returnFunc(ctx, filter)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// InternalUserRepository_GetInternalUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInternalUsers'
type InternalUserRepository_GetInternalUsers_Call struct {
	*mock.Call
}

// GetInternalUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - filter coreentity.InternalUserListFilter
func (_e *InternalUserRepository_Expecter) GetInternalUsers(ctx interface{}, filter interface{}) *InternalUserRepository_GetInternalUsers_Call {
	return &InternalUserRepository_GetInternalUsers_Call{Call: _e.mock.On("GetInternalUsers", ctx, filter)}
}

func (_c *InternalUserRepository_GetInternalUsers_Call) Run(run func(ctx context.Context, filter coreentity.InternalUserListFilter)) *InternalUserRepository_GetInternalUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 coreentity.InternalUserListFilter
		if args[1] != nil {
			arg1 = args[1].(coreentity.InternalUserListFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *InternalUserRepository_GetInternalUsers_Call) Return(internalUsers []coreentity.InternalUser, n int, err error) *InternalUserRepository_GetInternalUsers_Call {
	_c.Call.Return(internalUsers, n, err)
	return _c
}

func (_c *InternalUserRepository_GetInternalUsers_Call) RunAndReturn(run func(ctx context.Context, filter coreentity.InternalUserListFilter) ([]coreentity.InternalUser, int, error)) *InternalUserRepository_GetInternalUsers_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateInternalUser provides a mock function for the type InternalUserRepository
func (_mock *InternalUserRepository) UpdateInternalUser(ctx context.Context, data coreentity.InternalUser) error {
	ret := _mock.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for UpdateInternalUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.InternalUser) error); ok {
		r0 = returnFunc(ctx, data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// InternalUserRepository_UpdateInternalUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateInternalUser'
type InternalUserRepository_UpdateInternalUser_Call struct {
	*mock.Call
}

// UpdateInternalUser is a helper method to define mock.On call
//   - ctx context.Context
//   - data coreentity.InternalUser
func (_e *InternalUserRepository_Expecter) UpdateInternalUser(ctx interface{}, data interface{}) *InternalUserRepository_UpdateInternalUser_Call {
	return &InternalUserRepository_UpdateInternalUser_Call{Call: _e.mock.On("UpdateInternalUser", ctx, data)}
}

func (_c *InternalUserRepository_UpdateInternalUser_Call) Run(run func(ctx context.Context, data coreentity.InternalUser)) *InternalUserRepository_UpdateInternalUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 coreentity.InternalUser
		if args[1] != nil {
			arg1 = args[1].(coreentity.InternalUser)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *InternalUserRepository_UpdateInternalUser_Call) Return(err error) *InternalUserRepository_UpdateInternalUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *InternalUserRepository_UpdateInternalUser_Call) RunAndReturn(run func(ctx context.Context, data coreentity.InternalUser) error) *InternalUserRepository_UpdateInternalUser_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateInternalUserLastLogin provides a mock function for the type InternalUserRepository
func (_mock *InternalUserRepository) UpdateInternalUserLastLogin(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for UpdateInternalUserLastLogin")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// InternalUserRepository_UpdateInternalUserLastLogin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateInternalUserLastLogin'
type InternalUserRepository_UpdateInternalUserLastLogin_Call struct {
	*mock.Call
}

// UpdateInternalUserLastLogin is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *InternalUserRepository_Expecter) UpdateInternalUserLastLogin(ctx interface{}, id interface{}) *InternalUserRepository_UpdateInternalUserLastLogin_Call {
	return &InternalUserRepository_UpdateInternalUserLastLogin_Call{Call: _e.mock.On("UpdateInternalUserLastLogin", ctx, id)}
}

func (_c *InternalUserRepository_UpdateInternalUserLastLogin_Call) Run(run func(ctx context.Context, id string)) *InternalUserRepository_UpdateInternalUserLastLogin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *InternalUserRepository_UpdateInternalUserLastLogin_Call) Return(err error) *InternalUserRepository_UpdateInternalUserLastLogin_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *InternalUserRepository_UpdateInternalUserLastLogin_Call) RunAndReturn(run func(ctx context.Context, id string) error) *InternalUserRepository_UpdateInternalUserLastLogin_Call {
	_c.Call.Return(run)
	return _c
}
