// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"codebase-app/internal/entity/coreentity"
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewInternalProductRepository creates a new instance of InternalProductRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInternalProductRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *InternalProductRepository {
	mock := &InternalProductRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// InternalProductRepository is an autogenerated mock type for the InternalProductRepository type
type InternalProductRepository struct {
	mock.Mock
}

type InternalProductRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *InternalProductRepository) EXPECT() *InternalProductRepository_Expecter {
	return &InternalProductRepository_Expecter{mock: &_m.Mock}
}

// CreateInternalProduct provides a mock function for the type InternalProductRepository
func (_mock *InternalProductRepository) CreateInternalProduct(ctx context.Context, data coreentity.InternalProduct) (*coreentity.InternalProduct, error) {
	ret := _mock.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for CreateInternalProduct")
	}

	var r0 *coreentity.InternalProduct
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.InternalProduct) (*coreentity.InternalProduct, error)); ok {
		return returnFunc(ctx, data)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.InternalProduct) *coreentity.InternalProduct); ok {
		r0 = returnFunc(ctx, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*coreentity.InternalProduct)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, coreentity.InternalProduct) error); ok {
		r1 = returnFunc(ctx, data)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// InternalProductRepository_CreateInternalProduct_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateInternalProduct'
type InternalProductRepository_CreateInternalProduct_Call struct {
	*mock.Call
}

// CreateInternalProduct is a helper method to define mock.On call
//   - ctx context.Context
//   - data coreentity.InternalProduct
func (_e *InternalProductRepository_Expecter) CreateInternalProduct(ctx interface{}, data interface{}) *InternalProductRepository_CreateInternalProduct_Call {
	return &InternalProductRepository_CreateInternalProduct_Call{Call: _e.mock.On("CreateInternalProduct", ctx, data)}
}

func (_c *InternalProductRepository_CreateInternalProduct_Call) Run(run func(ctx context.Context, data coreentity.InternalProduct)) *InternalProductRepository_CreateInternalProduct_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 coreentity.InternalProduct
		if args[1] != nil {
			arg1 = args[1].(coreentity.InternalProduct)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *InternalProductRepository_CreateInternalProduct_Call) Return(internalProduct *coreentity.InternalProduct, err error) *InternalProductRepository_CreateInternalProduct_Call {
	_c.Call.Return(internalProduct, err)
	return _c
}

func (_c *InternalProductRepository_CreateInternalProduct_Call) RunAndReturn(run func(ctx context.Context, data coreentity.InternalProduct) (*coreentity.InternalProduct, error)) *InternalProductRepository_CreateInternalProduct_Call {
	_c.Call.Return(run)
	return _c
}

// CreateInternalProductPrice provides a mock function for the type InternalProductRepository
func (_mock *InternalProductRepository) CreateInternalProductPrice(ctx context.Context, data coreentity.InternalProductPrice) (*coreentity.InternalProductPrice, error) {
	ret := _mock.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for CreateInternalProductPrice")
	}

	var r0 *coreentity.InternalProductPrice
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.InternalProductPrice) (*coreentity.InternalProductPrice, error)); ok {
		return returnFunc(ctx, data)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.InternalProductPrice) *coreentity.InternalProductPrice); ok {
		r0 = returnFunc(ctx, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*coreentity.InternalProductPrice)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, coreentity.InternalProductPrice) error); ok {
		r1 = returnFunc(ctx, data)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// InternalProductRepository_CreateInternalProductPrice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateInternalProductPrice'
type InternalProductRepository_CreateInternalProductPrice_Call struct {
	*mock.Call
}

// CreateInternalProductPrice is a helper method to define mock.On call
//   - ctx context.Context
//   - data coreentity.InternalProductPrice
func (_e *InternalProductRepository_Expecter) CreateInternalProductPrice(ctx interface{}, data interface{}) *InternalProductRepository_CreateInternalProductPrice_Call {
	return &InternalProductRepository_CreateInternalProductPrice_Call{Call: _e.mock.On("CreateInternalProductPrice", ctx, data)}
}

func (_c *InternalProductRepository_CreateInternalProductPrice_Call) Run(run func(ctx context.Context, data coreentity.InternalProductPrice)) *InternalProductRepository_CreateInternalProductPrice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 coreentity.InternalProductPrice
		if args[1] != nil {
			arg1 = args[1].(coreentity.InternalProductPrice)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *InternalProductRepository_CreateInternalProductPrice_Call) Return(internalProductPrice *coreentity.InternalProductPrice, err error) *InternalProductRepository_CreateInternalProductPrice_Call {
	_c.Call.Return(internalProductPrice, err)
	return _c
}

func (_c *InternalProductRepository_CreateInternalProductPrice_Call) RunAndReturn(run func(ctx context.Context, data coreentity.InternalProductPrice) (*coreentity.InternalProductPrice, error)) *InternalProductRepository_CreateInternalProductPrice_Call {
	_c.Call.Return(run)
	return _c
}

// CreateInternalProductPricing provides a mock function for the type InternalProductRepository
func (_mock *InternalProductRepository) CreateInternalProductPricing(ctx context.Context, data coreentity.InternalProductPricing) (*coreentity.InternalProductPricing, error) {
	ret := _mock.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for CreateInternalProductPricing")
	}

	var r0 *coreentity.InternalProductPricing
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.InternalProductPricing) (*coreentity.InternalProductPricing, error)); ok {
		return returnFunc(ctx, data)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.InternalProductPricing) *coreentity.InternalProductPricing); ok {
		r0 = returnFunc(ctx, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*coreentity.InternalProductPricing)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, coreentity.InternalProductPricing) error); ok {
		r1 = returnFunc(ctx, data)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// InternalProductRepository_CreateInternalProductPricing_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateInternalProductPricing'
type InternalProductRepository_CreateInternalProductPricing_Call struct {
	*mock.Call
}

// CreateInternalProductPricing is a helper method to define mock.On call
//   - ctx context.Context
//   - data coreentity.InternalProductPricing
func (_e *InternalProductRepository_Expecter) CreateInternalProductPricing(ctx interface{}, data interface{}) *InternalProductRepository_CreateInternalProductPricing_Call {
	return &InternalProductRepository_CreateInternalProductPricing_Call{Call: _e.mock.On("CreateInternalProductPricing", ctx, data)}
}

func (_c *InternalProductRepository_CreateInternalProductPricing_Call) Run(run func(ctx context.Context, data coreentity.InternalProductPricing)) *InternalProductRepository_CreateInternalProductPricing_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 coreentity.InternalProductPricing
		if args[1] != nil {
			arg1 = args[1].(coreentity.InternalProductPricing)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *InternalProductRepository_CreateInternalProductPricing_Call) Return(internalProductPricing *coreentity.InternalProductPricing, err error) *InternalProductRepository_CreateInternalProductPricing_Call {
	_c.Call.Return(internalProductPricing, err)
	return _c
}

func (_c *InternalProductRepository_CreateInternalProductPricing_Call) RunAndReturn(run func(ctx context.Context, data coreentity.InternalProductPricing) (*coreentity.InternalProductPricing, error)) *InternalProductRepository_CreateInternalProductPricing_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteInternalProduct provides a mock function for the type InternalProductRepository
func (_mock *InternalProductRepository) DeleteInternalProduct(ctx context.Context, filter coreentity.InternalProductDeleteFilter) error {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for DeleteInternalProduct")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.InternalProductDeleteFilter) error); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// InternalProductRepository_DeleteInternalProduct_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteInternalProduct'
type InternalProductRepository_DeleteInternalProduct_Call struct {
	*mock.Call
}

// DeleteInternalProduct is a helper method to define mock.On call
//   - ctx context.Context
//   - filter coreentity.InternalProductDeleteFilter
func (_e *InternalProductRepository_Expecter) DeleteInternalProduct(ctx interface{}, filter interface{}) *InternalProductRepository_DeleteInternalProduct_Call {
	return &InternalProductRepository_DeleteInternalProduct_Call{Call: _e.mock.On("DeleteInternalProduct", ctx, filter)}
}

func (_c *InternalProductRepository_DeleteInternalProduct_Call) Run(run func(ctx context.Context, filter coreentity.InternalProductDeleteFilter)) *InternalProductRepository_DeleteInternalProduct_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 coreentity.InternalProductDeleteFilter
		if args[1] != nil {
			arg1 = args[1].(coreentity.InternalProductDeleteFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *InternalProductRepository_DeleteInternalProduct_Call) Return(err error) *InternalProductRepository_DeleteInternalProduct_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *InternalProductRepository_DeleteInternalProduct_Call) RunAndReturn(run func(ctx context.Context, filter coreentity.InternalProductDeleteFilter) error) *InternalProductRepository_DeleteInternalProduct_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteInternalProductPrice provides a mock function for the type InternalProductRepository
func (_mock *InternalProductRepository) DeleteInternalProductPrice(ctx context.Context, filter coreentity.InternalProductPriceDeleteFilter) error {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for DeleteInternalProductPrice")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.InternalProductPriceDeleteFilter) error); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// InternalProductRepository_DeleteInternalProductPrice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteInternalProductPrice'
type InternalProductRepository_DeleteInternalProductPrice_Call struct {
	*mock.Call
}

// DeleteInternalProductPrice is a helper method to define mock.On call
//   - ctx context.Context
//   - filter coreentity.InternalProductPriceDeleteFilter
func (_e *InternalProductRepository_Expecter) DeleteInternalProductPrice(ctx interface{}, filter interface{}) *InternalProductRepository_DeleteInternalProductPrice_Call {
	return &InternalProductRepository_DeleteInternalProductPrice_Call{Call: _e.mock.On("DeleteInternalProductPrice", ctx, filter)}
}

func (_c *InternalProductRepository_DeleteInternalProductPrice_Call) Run(run func(ctx context.Context, filter coreentity.InternalProductPriceDeleteFilter)) *InternalProductRepository_DeleteInternalProductPrice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 coreentity.InternalProductPriceDeleteFilter
		if args[1] != nil {
			arg1 = args[1].(coreentity.InternalProductPriceDeleteFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *InternalProductRepository_DeleteInternalProductPrice_Call) Return(err error) *InternalProductRepository_DeleteInternalProductPrice_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *InternalProductRepository_DeleteInternalProductPrice_Call) RunAndReturn(run func(ctx context.Context, filter coreentity.InternalProductPriceDeleteFilter) error) *InternalProductRepository_DeleteInternalProductPrice_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteInternalProductPricing provides a mock function for the type InternalProductRepository
func (_mock *InternalProductRepository) DeleteInternalProductPricing(ctx context.Context, filter coreentity.InternalProductPricingDeleteFilter) error {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for DeleteInternalProductPricing")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.InternalProductPricingDeleteFilter) error); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// InternalProductRepository_DeleteInternalProductPricing_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteInternalProductPricing'
type InternalProductRepository_DeleteInternalProductPricing_Call struct {
	*mock.Call
}

// DeleteInternalProductPricing is a helper method to define mock.On call
//   - ctx context.Context
//   - filter coreentity.InternalProductPricingDeleteFilter
func (_e *InternalProductRepository_Expecter) DeleteInternalProductPricing(ctx interface{}, filter interface{}) *InternalProductRepository_DeleteInternalProductPricing_Call {
	return &InternalProductRepository_DeleteInternalProductPricing_Call{Call: _e.mock.On("DeleteInternalProductPricing", ctx, filter)}
}

func (_c *InternalProductRepository_DeleteInternalProductPricing_Call) Run(run func(ctx context.Context, filter coreentity.InternalProductPricingDeleteFilter)) *InternalProductRepository_DeleteInternalProductPricing_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 coreentity.InternalProductPricingDeleteFilter
		if args[1] != nil {
			arg1 = args[1].(coreentity.InternalProductPricingDeleteFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *InternalProductRepository_DeleteInternalProductPricing_Call) Return(err error) *InternalProductRepository_DeleteInternalProductPricing_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *InternalProductRepository_DeleteInternalProductPricing_Call) RunAndReturn(run func(ctx context.Context, filter coreentity.InternalProductPricingDeleteFilter) error) *InternalProductRepository_DeleteInternalProductPricing_Call {
	_c.Call.Return(run)
	return _c
}

// ExistsInternalProductByCode provides a mock function for the type InternalProductRepository
func (_mock *InternalProductRepository) ExistsInternalProductByCode(ctx context.Context, code string, excludeID string) (bool, error) {
	ret := _mock.Called(ctx, code, excludeID)

	if len(ret) == 0 {
		panic("no return value specified for ExistsInternalProductByCode")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (bool, error)); ok {
		return returnFunc(ctx, code, excludeID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = returnFunc(ctx, code, excludeID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, code, excludeID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// InternalProductRepository_ExistsInternalProductByCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExistsInternalProductByCode'
type InternalProductRepository_ExistsInternalProductByCode_Call struct {
	*mock.Call
}

// ExistsInternalProductByCode is a helper method to define mock.On call
//   - ctx context.Context
//   - code string
//   - excludeID string
func (_e *InternalProductRepository_Expecter) ExistsInternalProductByCode(ctx interface{}, code interface{}, excludeID interface{}) *InternalProductRepository_ExistsInternalProductByCode_Call {
	return &InternalProductRepository_ExistsInternalProductByCode_Call{Call: _e.mock.On("ExistsInternalProductByCode", ctx, code, excludeID)}
}

func (_c *InternalProductRepository_ExistsInternalProductByCode_Call) Run(run func(ctx context.Context, code string, excludeID string)) *InternalProductRepository_ExistsInternalProductByCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *InternalProductRepository_ExistsInternalProductByCode_Call) Return(b bool, err error) *InternalProductRepository_ExistsInternalProductByCode_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *InternalProductRepository_ExistsInternalProductByCode_Call) RunAndReturn(run func(ctx context.Context, code string, excludeID string) (bool, error)) *InternalProductRepository_ExistsInternalProductByCode_Call {
	_c.Call.Return(run)
	return _c
}

// ExistsInternalProductPricingByCode provides a mock function for the type InternalProductRepository
func (_mock *InternalProductRepository) ExistsInternalProductPricingByCode(ctx context.Context, internalProductID string, code string, excludeID string) (bool, error) {
	ret := _mock.Called(ctx, internalProductID, code, excludeID)

	if len(ret) == 0 {
		panic("no return value specified for ExistsInternalProductPricingByCode")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) (bool, error)); ok {
		return returnFunc(ctx, internalProductID, code, excludeID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) bool); ok {
		r0 = returnFunc(ctx, internalProductID, code, excludeID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = returnFunc(ctx, internalProductID, code, excludeID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// InternalProductRepository_ExistsInternalProductPricingByCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExistsInternalProductPricingByCode'
type InternalProductRepository_ExistsInternalProductPricingByCode_Call struct {
	*mock.Call
}

// ExistsInternalProductPricingByCode is a helper method to define mock.On call
//   - ctx context.Context
//   - internalProductID string
//   - code string
//   - excludeID string
func (_e *InternalProductRepository_Expecter) ExistsInternalProductPricingByCode(ctx interface{}, internalProductID interface{}, code interface{}, excludeID interface{}) *InternalProductRepository_ExistsInternalProductPricingByCode_Call {
	return &InternalProductRepository_ExistsInternalProductPricingByCode_Call{Call: _e.mock.On("ExistsInternalProductPricingByCode", ctx, internalProductID, code, excludeID)}
}

func (_c *InternalProductRepository_ExistsInternalProductPricingByCode_Call) Run(run func(ctx context.Context, internalProductID string, code string, excludeID string)) *InternalProductRepository_ExistsInternalProductPricingByCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *InternalProductRepository_ExistsInternalProductPricingByCode_Call) Return(b bool, err error) *InternalProductRepository_ExistsInternalProductPricingByCode_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *InternalProductRepository_ExistsInternalProductPricingByCode_Call) RunAndReturn(run func(ctx context.Context, internalProductID string, code string, excludeID string) (bool, error)) *InternalProductRepository_ExistsInternalProductPricingByCode_Call {
	_c.Call.Return(run)
	return _c
}

// ExistsOverlappingInternalProductPrice provides a mock function for the type InternalProductRepository
func (_mock *InternalProductRepository) ExistsOverlappingInternalProductPrice(ctx context.Context, filter coreentity.InternalProductPriceOverlapFilter) (bool, error) {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for ExistsOverlappingInternalProductPrice")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.InternalProductPriceOverlapFilter) (bool, error)); ok {
		return returnFunc(ctx, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.InternalProductPriceOverlapFilter) bool); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, coreentity.InternalProductPriceOverlapFilter) error); ok {
		r1 = returnFunc(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// InternalProductRepository_ExistsOverlappingInternalProductPrice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExistsOverlappingInternalProductPrice'
type InternalProductRepository_ExistsOverlappingInternalProductPrice_Call struct {
	*mock.Call
}

// ExistsOverlappingInternalProductPrice is a helper method to define mock.On call
//   - ctx context.Context
//   - filter coreentity.InternalProductPriceOverlapFilter
func (_e *InternalProductRepository_Expecter) ExistsOverlappingInternalProductPrice(ctx interface{}, filter interface{}) *InternalProductRepository_ExistsOverlappingInternalProductPrice_Call {
	return &InternalProductRepository_ExistsOverlappingInternalProductPrice_Call{Call: _e.mock.On("ExistsOverlappingInternalProductPrice", ctx, filter)}
}

func (_c *InternalProductRepository_ExistsOverlappingInternalProductPrice_Call) Run(run func(ctx context.Context, filter coreentity.InternalProductPriceOverlapFilter)) *InternalProductRepository_ExistsOverlappingInternalProductPrice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 coreentity.InternalProductPriceOverlapFilter
		if args[1] != nil {
			arg1 = args[1].(coreentity.InternalProductPriceOverlapFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *InternalProductRepository_ExistsOverlappingInternalProductPrice_Call) Return(b bool, err error) *InternalProductRepository_ExistsOverlappingInternalProductPrice_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *InternalProductRepository_ExistsOverlappingInternalProductPrice_Call) RunAndReturn(run func(ctx context.Context, filter coreentity.InternalProductPriceOverlapFilter) (bool, error)) *InternalProductRepository_ExistsOverlappingInternalProductPrice_Call {
	_c.Call.Return(run)
	return _c
}

// GetInternalProduct provides a mock function for the type InternalProductRepository
func (_mock *InternalProductRepository) GetInternalProduct(ctx context.Context, filter coreentity.InternalProductFilter) (*coreentity.InternalProduct, error) {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetInternalProduct")
	}

	var r0 *coreentity.InternalProduct
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.InternalProductFilter) (*coreentity.InternalProduct, error)); ok {
		return returnFunc(ctx, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.InternalProductFilter) *coreentity.InternalProduct); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*coreentity.InternalProduct)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, coreentity.InternalProductFilter) error); ok {
		r1 = returnFunc(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// InternalProductRepository_GetInternalProduct_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInternalProduct'
type InternalProductRepository_GetInternalProduct_Call struct {
	*mock.Call
}

// GetInternalProduct is a helper method to define mock.On call
//   - ctx context.Context
//   - filter coreentity.InternalProductFilter
func (_e *InternalProductRepository_Expecter) GetInternalProduct(ctx interface{}, filter interface{}) *InternalProductRepository_GetInternalProduct_Call {
	return &InternalProductRepository_GetInternalProduct_Call{Call: _e.mock.On("GetInternalProduct", ctx, filter)}
}

func (_c *InternalProductRepository_GetInternalProduct_Call) Run(run func(ctx context.Context, filter coreentity.InternalProductFilter)) *InternalProductRepository_GetInternalProduct_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 coreentity.InternalProductFilter
		if args[1] != nil {
			arg1 = args[1].(coreentity.InternalProductFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *InternalProductRepository_GetInternalProduct_Call) Return(internalProduct *coreentity.InternalProduct, err error) *InternalProductRepository_GetInternalProduct_Call {
	_c.Call.Return(internalProduct, err)
	return _c
}

func (_c *InternalProductRepository_GetInternalProduct_Call) RunAndReturn(run func(ctx context.Context, filter coreentity.InternalProductFilter) (*coreentity.InternalProduct, error)) *InternalProductRepository_GetInternalProduct_Call {
	_c.Call.Return(run)
	return _c
}

// GetInternalProductPrices provides a mock function for the type InternalProductRepository
func (_mock *InternalProductRepository) GetInternalProductPrices(ctx context.Context, filter coreentity.InternalProductPriceListFilter) ([]coreentity.InternalProductPrice, int, error) {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetInternalProductPrices")
	}

	var r0 []coreentity.InternalProductPrice
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.InternalProductPriceListFilter) ([]coreentity.InternalProductPrice, int, error)); ok {
		return returnFunc(ctx, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.InternalProductPriceListFilter) []coreentity.InternalProductPrice); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]coreentity.InternalProductPrice)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, coreentity.InternalProductPriceListFilter) int); ok {
		r1 = returnFunc(ctx, filter)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, coreentity.InternalProductPriceListFilter) error); ok {
		r2 = returnFunc(ctx, filter)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// InternalProductRepository_GetInternalProductPrices_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInternalProductPrices'
type InternalProductRepository_GetInternalProductPrices_Call struct {
	*mock.Call
}

// GetInternalProductPrices is a helper method to define mock.On call
//   - ctx context.Context
//   - filter coreentity.InternalProductPriceListFilter
func (_e *InternalProductRepository_Expecter) GetInternalProductPrices(ctx interface{}, filter interface{}) *InternalProductRepository_GetInternalProductPrices_Call {
	return &InternalProductRepository_GetInternalProductPrices_Call{Call: _e.mock.On("GetInternalProductPrices", ctx, filter)}
}

func (_c *InternalProductRepository_GetInternalProductPrices_Call) Run(run func(ctx context.Context, filter coreentity.InternalProductPriceListFilter)) *InternalProductRepository_GetInternalProductPrices_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 coreentity.InternalProductPriceListFilter
		if args[1] != nil {
			arg1 = args[1].(coreentity.InternalProductPriceListFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *InternalProductRepository_GetInternalProductPrices_Call) Return(internalProductPrices []coreentity.InternalProductPrice, n int, err error) *InternalProductRepository_GetInternalProductPrices_Call {
	_c.Call.Return(internalProductPrices, n, err)
	return _c
}

func (_c *InternalProductRepository_GetInternalProductPrices_Call) RunAndReturn(run func(ctx context.Context, filter coreentity.InternalProductPriceListFilter) ([]coreentity.InternalProductPrice, int, error)) *InternalProductRepository_GetInternalProductPrices_Call {
	_c.Call.Return(run)
	return _c
}

// GetInternalProductPricing provides a mock function for the type InternalProductRepository
func (_mock *InternalProductRepository) GetInternalProductPricing(ctx context.Context, filter coreentity.InternalProductPricingFilter) (*coreentity.InternalProductPricing, error) {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetInternalProductPricing")
	}

	var r0 *coreentity.InternalProductPricing
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.InternalProductPricingFilter) (*coreentity.InternalProductPricing, error)); ok {
		return returnFunc(ctx, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.InternalProductPricingFilter) *coreentity.InternalProductPricing); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*coreentity.InternalProductPricing)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, coreentity.InternalProductPricingFilter) error); ok {
		r1 = returnFunc(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// InternalProductRepository_GetInternalProductPricing_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInternalProductPricing'
type InternalProductRepository_GetInternalProductPricing_Call struct {
	*mock.Call
}

// GetInternalProductPricing is a helper method to define mock.On call
//   - ctx context.Context
//   - filter coreentity.InternalProductPricingFilter
func (_e *InternalProductRepository_Expecter) GetInternalProductPricing(ctx interface{}, filter interface{}) *InternalProductRepository_GetInternalProductPricing_Call {
	return &InternalProductRepository_GetInternalProductPricing_Call{Call: _e.mock.On("GetInternalProductPricing", ctx, filter)}
}

func (_c *InternalProductRepository_GetInternalProductPricing_Call) Run(run func(ctx context.Context, filter coreentity.InternalProductPricingFilter)) *InternalProductRepository_GetInternalProductPricing_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 coreentity.InternalProductPricingFilter
		if args[1] != nil {
			arg1 = args[1].(coreentity.InternalProductPricingFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *InternalProductRepository_GetInternalProductPricing_Call) Return(internalProductPricing *coreentity.InternalProductPricing, err error) *InternalProductRepository_GetInternalProductPricing_Call {
	_c.Call.Return(internalProductPricing, err)
	return _c
}

func (_c *InternalProductRepository_GetInternalProductPricing_Call) RunAndReturn(run func(ctx context.Context, filter coreentity.InternalProductPricingFilter) (*coreentity.InternalProductPricing, error)) *InternalProductRepository_GetInternalProductPricing_Call {
	_c.Call.Return(run)
	return _c
}

// GetInternalProductPricings provides a mock function for the type InternalProductRepository
func (_mock *InternalProductRepository) GetInternalProductPricings(ctx context.Context, filter coreentity.InternalProductPricingListFilter) ([]coreentity.InternalProductPricing, int, error) {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetInternalProductPricings")
	}

	var r0 []coreentity.InternalProductPricing
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.InternalProductPricingListFilter) ([]coreentity.InternalProductPricing, int, error)); ok {
		return returnFunc(ctx, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.InternalProductPricingListFilter) []coreentity.InternalProductPricing); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]coreentity.InternalProductPricing)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, coreentity.InternalProductPricingListFilter) int); ok {
		r1 = returnFunc(ctx, filter)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, coreentity.InternalProductPricingListFilter) error); ok {
		r2 = returnFunc(ctx, filter)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// InternalProductRepository_GetInternalProductPricings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInternalProductPricings'
type InternalProductRepository_GetInternalProductPricings_Call struct {
	*mock.Call
}

// GetInternalProductPricings is a helper method to define mock.On call
//   - ctx context.Context
//   - filter coreentity.InternalProductPricingListFilter
func (_e *InternalProductRepository_Expecter) GetInternalProductPricings(ctx interface{}, filter interface{}) *InternalProductRepository_GetInternalProductPricings_Call {
	return &InternalProductRepository_GetInternalProductPricings_Call{Call: _e.mock.On("GetInternalProductPricings", ctx, filter)}
}

func (_c *InternalProductRepository_GetInternalProductPricings_Call) Run(run func(ctx context.Context, filter coreentity.InternalProductPricingListFilter)) *InternalProductRepository_GetInternalProductPricings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 coreentity.InternalProductPricingListFilter
		if args[1] != nil {
			arg1 = args[1].(coreentity.InternalProductPricingListFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *InternalProductRepository_GetInternalProductPricings_Call) Return(internalProductPricings []coreentity.InternalProductPricing, n int, err error) *InternalProductRepository_GetInternalProductPricings_Call {
	_c.Call.Return(internalProductPricings, n, err)
	return _c
}

func (_c *InternalProductRepository_GetInternalProductPricings_Call) RunAndReturn(run func(ctx context.Context, filter coreentity.InternalProductPricingListFilter) ([]coreentity.InternalProductPricing, int, error)) *InternalProductRepository_GetInternalProductPricings_Call {
	_c.Call.Return(run)
	return _c
}

// GetInternalProducts provides a mock function for the type InternalProductRepository
func (_mock *InternalProductRepository) GetInternalProducts(ctx context.Context, filter coreentity.InternalProductListFilter) ([]coreentity.InternalProduct, int, error) {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetInternalProducts")
	}

	var r0 []coreentity.InternalProduct
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.InternalProductListFilter) ([]coreentity.InternalProduct, int, error)); ok {
		return returnFunc(ctx, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.InternalProductListFilter) []coreentity.InternalProduct); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]coreentity.InternalProduct)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, coreentity.InternalProductListFilter) int); ok {
		r1 = returnFunc(ctx, filter)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, coreentity.InternalProductListFilter) error); ok {
		r2 = returnFunc(ctx, filter)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// InternalProductRepository_GetInternalProducts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInternalProducts'
type InternalProductRepository_GetInternalProducts_Call struct {
	*mock.Call
}

// GetInternalProducts is a helper method to define mock.On call
//   - ctx context.Context
//   - filter coreentity.InternalProductListFilter
func (_e *InternalProductRepository_Expecter) GetInternalProducts(ctx interface{}, filter interface{}) *InternalProductRepository_GetInternalProducts_Call {
	return &InternalProductRepository_GetInternalProducts_Call{Call: _e.mock.On("GetInternalProducts", ctx, filter)}
}

func (_c *InternalProductRepository_GetInternalProducts_Call) Run(run func(ctx context.Context, filter coreentity.InternalProductListFilter)) *InternalProductRepository_GetInternalProducts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 coreentity.InternalProductListFilter
		if args[1] != nil {
			arg1 = args[1].(coreentity.InternalProductListFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *InternalProductRepository_GetInternalProducts_Call) Return(internalProducts []coreentity.InternalProduct, n int, err error) *InternalProductRepository_GetInternalProducts_Call {
	_c.Call.Return(internalProducts, n, err)
	return _c
}

func (_c *InternalProductRepository_GetInternalProducts_Call) RunAndReturn(run func(ctx context.Context, filter coreentity.InternalProductListFilter) ([]coreentity.InternalProduct, int, error)) *InternalProductRepository_GetInternalProducts_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateInternalProduct provides a mock function for the type InternalProductRepository
func (_mock *InternalProductRepository) UpdateInternalProduct(ctx context.Context, data coreentity.InternalProduct) error {
	ret := _mock.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for UpdateInternalProduct")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.InternalProduct) error); ok {
		r0 = returnFunc(ctx, data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// InternalProductRepository_UpdateInternalProduct_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateInternalProduct'
type InternalProductRepository_UpdateInternalProduct_Call struct {
	*mock.Call
}

// UpdateInternalProduct is a helper method to define mock.On call
//   - ctx context.Context
//   - data coreentity.InternalProduct
func (_e *InternalProductRepository_Expecter) UpdateInternalProduct(ctx interface{}, data interface{}) *InternalProductRepository_UpdateInternalProduct_Call {
	return &InternalProductRepository_UpdateInternalProduct_Call{Call: _e.mock.On("UpdateInternalProduct", ctx, data)}
}

func (_c *InternalProductRepository_UpdateInternalProduct_Call) Run(run func(ctx context.Context, data coreentity.InternalProduct)) *InternalProductRepository_UpdateInternalProduct_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 coreentity.InternalProduct
		if args[1] != nil {
			arg1 = args[1].(coreentity.InternalProduct)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *InternalProductRepository_UpdateInternalProduct_Call) Return(err error) *InternalProductRepository_UpdateInternalProduct_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *InternalProductRepository_UpdateInternalProduct_Call) RunAndReturn(run func(ctx context.Context, data coreentity.InternalProduct) error) *InternalProductRepository_UpdateInternalProduct_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateInternalProductPrice provides a mock function for the type InternalProductRepository
func (_mock *InternalProductRepository) UpdateInternalProductPrice(ctx context.Context, data coreentity.InternalProductPrice) error {
	ret := _mock.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for UpdateInternalProductPrice")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.InternalProductPrice) error); ok {
		r0 = returnFunc(ctx, data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// InternalProductRepository_UpdateInternalProductPrice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateInternalProductPrice'
type InternalProductRepository_UpdateInternalProductPrice_Call struct {
	*mock.Call
}

// UpdateInternalProductPrice is a helper method to define mock.On call
//   - ctx context.Context
//   - data coreentity.InternalProductPrice
func (_e *InternalProductRepository_Expecter) UpdateInternalProductPrice(ctx interface{}, data interface{}) *InternalProductRepository_UpdateInternalProductPrice_Call {
	return &InternalProductRepository_UpdateInternalProductPrice_Call{Call: _e.mock.On("UpdateInternalProductPrice", ctx, data)}
}

func (_c *InternalProductRepository_UpdateInternalProductPrice_Call) Run(run func(ctx context.Context, data coreentity.InternalProductPrice)) *InternalProductRepository_UpdateInternalProductPrice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 coreentity.InternalProductPrice
		if args[1] != nil {
			arg1 = args[1].(coreentity.InternalProductPrice)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *InternalProductRepository_UpdateInternalProductPrice_Call) Return(err error) *InternalProductRepository_UpdateInternalProductPrice_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *InternalProductRepository_UpdateInternalProductPrice_Call) RunAndReturn(run func(ctx context.Context, data coreentity.InternalProductPrice) error) *InternalProductRepository_UpdateInternalProductPrice_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateInternalProductPricing provides a mock function for the type InternalProductRepository
func (_mock *InternalProductRepository) UpdateInternalProductPricing(ctx context.Context, data coreentity.InternalProductPricing) error {
	ret := _mock.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for UpdateInternalProductPricing")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.InternalProductPricing) error); ok {
		r0 = returnFunc(ctx, data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// InternalProductRepository_UpdateInternalProductPricing_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateInternalProductPricing'
type InternalProductRepository_UpdateInternalProductPricing_Call struct {
	*mock.Call
}

// UpdateInternalProductPricing is a helper method to define mock.On call
//   - ctx context.Context
//   - data coreentity.InternalProductPricing
func (_e *InternalProductRepository_Expecter) UpdateInternalProductPricing(ctx interface{}, data interface{}) *InternalProductRepository_UpdateInternalProductPricing_Call {
	return &InternalProductRepository_UpdateInternalProductPricing_Call{Call: _e.mock.On("UpdateInternalProductPricing", ctx, data)}
}

func (_c *InternalProductRepository_UpdateInternalProductPricing_Call) Run(run func(ctx context.Context, data coreentity.InternalProductPricing)) *InternalProductRepository_UpdateInternalProductPricing_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 coreentity.InternalProductPricing
		if args[1] != nil {
			arg1 = args[1].(coreentity.InternalProductPricing)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *InternalProductRepository_UpdateInternalProductPricing_Call) Return(err error) *InternalProductRepository_UpdateInternalProductPricing_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *InternalProductRepository_UpdateInternalProductPricing_Call) RunAndReturn(run func(ctx context.Context, data coreentity.InternalProductPricing) error) *InternalProductRepository_UpdateInternalProductPricing_Call {
	_c.Call.Return(run)
	return _c
}
