// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"codebase-app/internal/entity/coreentity"
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewInternalInvoiceRepository creates a new instance of InternalInvoiceRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInternalInvoiceRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *InternalInvoiceRepository {
	mock := &InternalInvoiceRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// InternalInvoiceRepository is an autogenerated mock type for the InternalInvoiceRepository type
type InternalInvoiceRepository struct {
	mock.Mock
}

type InternalInvoiceRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *InternalInvoiceRepository) EXPECT() *InternalInvoiceRepository_Expecter {
	return &InternalInvoiceRepository_Expecter{mock: &_m.Mock}
}

// CreateInvoice provides a mock function for the type InternalInvoiceRepository
func (_mock *InternalInvoiceRepository) CreateInvoice(ctx context.Context, data coreentity.InternalInvoice) (*coreentity.InternalInvoice, error) {
	ret := _mock.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for CreateInvoice")
	}

	var r0 *coreentity.InternalInvoice
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.InternalInvoice) (*coreentity.InternalInvoice, error)); ok {
		return returnFunc(ctx, data)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.InternalInvoice) *coreentity.InternalInvoice); ok {
		r0 = returnFunc(ctx, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*coreentity.InternalInvoice)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, coreentity.InternalInvoice) error); ok {
		r1 = returnFunc(ctx, data)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// InternalInvoiceRepository_CreateInvoice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateInvoice'
type InternalInvoiceRepository_CreateInvoice_Call struct {
	*mock.Call
}

// CreateInvoice is a helper method to define mock.On call
//   - ctx context.Context
//   - data coreentity.InternalInvoice
func (_e *InternalInvoiceRepository_Expecter) CreateInvoice(ctx interface{}, data interface{}) *InternalInvoiceRepository_CreateInvoice_Call {
	return &InternalInvoiceRepository_CreateInvoice_Call{Call: _e.mock.On("CreateInvoice", ctx, data)}
}

func (_c *InternalInvoiceRepository_CreateInvoice_Call) Run(run func(ctx context.Context, data coreentity.InternalInvoice)) *InternalInvoiceRepository_CreateInvoice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 coreentity.InternalInvoice
		if args[1] != nil {
			arg1 = args[1].(coreentity.InternalInvoice)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *InternalInvoiceRepository_CreateInvoice_Call) Return(internalInvoice *coreentity.InternalInvoice, err error) *InternalInvoiceRepository_CreateInvoice_Call {
	_c.Call.Return(internalInvoice, err)
	return _c
}

func (_c *InternalInvoiceRepository_CreateInvoice_Call) RunAndReturn(run func(ctx context.Context, data coreentity.InternalInvoice) (*coreentity.InternalInvoice, error)) *InternalInvoiceRepository_CreateInvoice_Call {
	_c.Call.Return(run)
	return _c
}

// CreatePaymentAttempt provides a mock function for the type InternalInvoiceRepository
func (_mock *InternalInvoiceRepository) CreatePaymentAttempt(ctx context.Context, data coreentity.InternalPaymentAttempt) (*coreentity.InternalPaymentAttempt, error) {
	ret := _mock.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for CreatePaymentAttempt")
	}

	var r0 *coreentity.InternalPaymentAttempt
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.InternalPaymentAttempt) (*coreentity.InternalPaymentAttempt, error)); ok {
		return returnFunc(ctx, data)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.InternalPaymentAttempt) *coreentity.InternalPaymentAttempt); ok {
		r0 = returnFunc(ctx, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*coreentity.InternalPaymentAttempt)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, coreentity.InternalPaymentAttempt) error); ok {
		r1 = returnFunc(ctx, data)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// InternalInvoiceRepository_CreatePaymentAttempt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePaymentAttempt'
type InternalInvoiceRepository_CreatePaymentAttempt_Call struct {
	*mock.Call
}

// CreatePaymentAttempt is a helper method to define mock.On call
//   - ctx context.Context
//   - data coreentity.InternalPaymentAttempt
func (_e *InternalInvoiceRepository_Expecter) CreatePaymentAttempt(ctx interface{}, data interface{}) *InternalInvoiceRepository_CreatePaymentAttempt_Call {
	return &InternalInvoiceRepository_CreatePaymentAttempt_Call{Call: _e.mock.On("CreatePaymentAttempt", ctx, data)}
}

func (_c *InternalInvoiceRepository_CreatePaymentAttempt_Call) Run(run func(ctx context.Context, data coreentity.InternalPaymentAttempt)) *InternalInvoiceRepository_CreatePaymentAttempt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 coreentity.InternalPaymentAttempt
		if args[1] != nil {
			arg1 = args[1].(coreentity.InternalPaymentAttempt)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *InternalInvoiceRepository_CreatePaymentAttempt_Call) Return(internalPaymentAttempt *coreentity.InternalPaymentAttempt, err error) *InternalInvoiceRepository_CreatePaymentAttempt_Call {
	_c.Call.Return(internalPaymentAttempt, err)
	return _c
}

func (_c *InternalInvoiceRepository_CreatePaymentAttempt_Call) RunAndReturn(run func(ctx context.Context, data coreentity.InternalPaymentAttempt) (*coreentity.InternalPaymentAttempt, error)) *InternalInvoiceRepository_CreatePaymentAttempt_Call {
	_c.Call.Return(run)
	return _c
}

// CreatePaymentReceipt provides a mock function for the type InternalInvoiceRepository
func (_mock *InternalInvoiceRepository) CreatePaymentReceipt(ctx context.Context, data coreentity.InternalPaymentReceipt) (*coreentity.InternalPaymentReceipt, error) {
	ret := _mock.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for CreatePaymentReceipt")
	}

	var r0 *coreentity.InternalPaymentReceipt
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.InternalPaymentReceipt) (*coreentity.InternalPaymentReceipt, error)); ok {
		return returnFunc(ctx, data)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.InternalPaymentReceipt) *coreentity.InternalPaymentReceipt); ok {
		r0 = returnFunc(ctx, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*coreentity.InternalPaymentReceipt)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, coreentity.InternalPaymentReceipt) error); ok {
		r1 = returnFunc(ctx, data)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// InternalInvoiceRepository_CreatePaymentReceipt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePaymentReceipt'
type InternalInvoiceRepository_CreatePaymentReceipt_Call struct {
	*mock.Call
}

// CreatePaymentReceipt is a helper method to define mock.On call
//   - ctx context.Context
//   - data coreentity.InternalPaymentReceipt
func (_e *InternalInvoiceRepository_Expecter) CreatePaymentReceipt(ctx interface{}, data interface{}) *InternalInvoiceRepository_CreatePaymentReceipt_Call {
	return &InternalInvoiceRepository_CreatePaymentReceipt_Call{Call: _e.mock.On("CreatePaymentReceipt", ctx, data)}
}

func (_c *InternalInvoiceRepository_CreatePaymentReceipt_Call) Run(run func(ctx context.Context, data coreentity.InternalPaymentReceipt)) *InternalInvoiceRepository_CreatePaymentReceipt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 coreentity.InternalPaymentReceipt
		if args[1] != nil {
			arg1 = args[1].(coreentity.InternalPaymentReceipt)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *InternalInvoiceRepository_CreatePaymentReceipt_Call) Return(internalPaymentReceipt *coreentity.InternalPaymentReceipt, err error) *InternalInvoiceRepository_CreatePaymentReceipt_Call {
	_c.Call.Return(internalPaymentReceipt, err)
	return _c
}

func (_c *InternalInvoiceRepository_CreatePaymentReceipt_Call) RunAndReturn(run func(ctx context.Context, data coreentity.InternalPaymentReceipt) (*coreentity.InternalPaymentReceipt, error)) *InternalInvoiceRepository_CreatePaymentReceipt_Call {
	_c.Call.Return(run)
	return _c
}

// GetInvoice provides a mock function for the type InternalInvoiceRepository
func (_mock *InternalInvoiceRepository) GetInvoice(ctx context.Context, tenantID string, id string) (*coreentity.InternalInvoice, error) {
	ret := _mock.Called(ctx, tenantID, id)

	if len(ret) == 0 {
		panic("no return value specified for GetInvoice")
	}

	var r0 *coreentity.InternalInvoice
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*coreentity.InternalInvoice, error)); ok {
		return returnFunc(ctx, tenantID, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *coreentity.InternalInvoice); ok {
		r0 = returnFunc(ctx, tenantID, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*coreentity.InternalInvoice)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, tenantID, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// InternalInvoiceRepository_GetInvoice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInvoice'
type InternalInvoiceRepository_GetInvoice_Call struct {
	*mock.Call
}

// GetInvoice is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID string
//   - id string
func (_e *InternalInvoiceRepository_Expecter) GetInvoice(ctx interface{}, tenantID interface{}, id interface{}) *InternalInvoiceRepository_GetInvoice_Call {
	return &InternalInvoiceRepository_GetInvoice_Call{Call: _e.mock.On("GetInvoice", ctx, tenantID, id)}
}

func (_c *InternalInvoiceRepository_GetInvoice_Call) Run(run func(ctx context.Context, tenantID string, id string)) *InternalInvoiceRepository_GetInvoice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *InternalInvoiceRepository_GetInvoice_Call) Return(internalInvoice *coreentity.InternalInvoice, err error) *InternalInvoiceRepository_GetInvoice_Call {
	_c.Call.Return(internalInvoice, err)
	return _c
}

func (_c *InternalInvoiceRepository_GetInvoice_Call) RunAndReturn(run func(ctx context.Context, tenantID string, id string) (*coreentity.InternalInvoice, error)) *InternalInvoiceRepository_GetInvoice_Call {
	_c.Call.Return(run)
	return _c
}

// GetInvoiceByOrderID provides a mock function for the type InternalInvoiceRepository
func (_mock *InternalInvoiceRepository) GetInvoiceByOrderID(ctx context.Context, tenantID string, orderID string) (*coreentity.InternalInvoice, error) {
	ret := _mock.Called(ctx, tenantID, orderID)

	if len(ret) == 0 {
		panic("no return value specified for GetInvoiceByOrderID")
	}

	var r0 *coreentity.InternalInvoice
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*coreentity.InternalInvoice, error)); ok {
		return returnFunc(ctx, tenantID, orderID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *coreentity.InternalInvoice); ok {
		r0 = returnFunc(ctx, tenantID, orderID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*coreentity.InternalInvoice)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, tenantID, orderID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// InternalInvoiceRepository_GetInvoiceByOrderID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInvoiceByOrderID'
type InternalInvoiceRepository_GetInvoiceByOrderID_Call struct {
	*mock.Call
}

// GetInvoiceByOrderID is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID string
//   - orderID string
func (_e *InternalInvoiceRepository_Expecter) GetInvoiceByOrderID(ctx interface{}, tenantID interface{}, orderID interface{}) *InternalInvoiceRepository_GetInvoiceByOrderID_Call {
	return &InternalInvoiceRepository_GetInvoiceByOrderID_Call{Call: _e.mock.On("GetInvoiceByOrderID", ctx, tenantID, orderID)}
}

func (_c *InternalInvoiceRepository_GetInvoiceByOrderID_Call) Run(run func(ctx context.Context, tenantID string, orderID string)) *InternalInvoiceRepository_GetInvoiceByOrderID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *InternalInvoiceRepository_GetInvoiceByOrderID_Call) Return(internalInvoice *coreentity.InternalInvoice, err error) *InternalInvoiceRepository_GetInvoiceByOrderID_Call {
	_c.Call.Return(internalInvoice, err)
	return _c
}

func (_c *InternalInvoiceRepository_GetInvoiceByOrderID_Call) RunAndReturn(run func(ctx context.Context, tenantID string, orderID string) (*coreentity.InternalInvoice, error)) *InternalInvoiceRepository_GetInvoiceByOrderID_Call {
	_c.Call.Return(run)
	return _c
}

// GetInvoices provides a mock function for the type InternalInvoiceRepository
func (_mock *InternalInvoiceRepository) GetInvoices(ctx context.Context, filter coreentity.InternalCommerceListFilter) ([]coreentity.InternalInvoice, int, error) {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetInvoices")
	}

	var r0 []coreentity.InternalInvoice
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.InternalCommerceListFilter) ([]coreentity.InternalInvoice, int, error)); ok {
		return returnFunc(ctx, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.InternalCommerceListFilter) []coreentity.InternalInvoice); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]coreentity.InternalInvoice)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, coreentity.InternalCommerceListFilter) int); ok {
		r1 = returnFunc(ctx, filter)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, coreentity.InternalCommerceListFilter) error); ok {
		r2 = returnFunc(ctx, filter)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// InternalInvoiceRepository_GetInvoices_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInvoices'
type InternalInvoiceRepository_GetInvoices_Call struct {
	*mock.Call
}

// GetInvoices is a helper method to define mock.On call
//   - ctx context.Context
//   - filter coreentity.InternalCommerceListFilter
func (_e *InternalInvoiceRepository_Expecter) GetInvoices(ctx interface{}, filter interface{}) *InternalInvoiceRepository_GetInvoices_Call {
	return &InternalInvoiceRepository_GetInvoices_Call{Call: _e.mock.On("GetInvoices", ctx, filter)}
}

func (_c *InternalInvoiceRepository_GetInvoices_Call) Run(run func(ctx context.Context, filter coreentity.InternalCommerceListFilter)) *InternalInvoiceRepository_GetInvoices_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 coreentity.InternalCommerceListFilter
		if args[1] != nil {
			arg1 = args[1].(coreentity.InternalCommerceListFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *InternalInvoiceRepository_GetInvoices_Call) Return(internalInvoices []coreentity.InternalInvoice, n int, err error) *InternalInvoiceRepository_GetInvoices_Call {
	_c.Call.Return(internalInvoices, n, err)
	return _c
}

func (_c *InternalInvoiceRepository_GetInvoices_Call) RunAndReturn(run func(ctx context.Context, filter coreentity.InternalCommerceListFilter) ([]coreentity.InternalInvoice, int, error)) *InternalInvoiceRepository_GetInvoices_Call {
	_c.Call.Return(run)
	return _c
}

// GetLatestPaymentAttempt provides a mock function for the type InternalInvoiceRepository
func (_mock *InternalInvoiceRepository) GetLatestPaymentAttempt(ctx context.Context, tenantID string, invoiceID string) (*coreentity.InternalPaymentAttempt, error) {
	ret := _mock.Called(ctx, tenantID, invoiceID)

	if len(ret) == 0 {
		panic("no return value specified for GetLatestPaymentAttempt")
	}

	var r0 *coreentity.InternalPaymentAttempt
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*coreentity.InternalPaymentAttempt, error)); ok {
		return returnFunc(ctx, tenantID, invoiceID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *coreentity.InternalPaymentAttempt); ok {
		r0 = returnFunc(ctx, tenantID, invoiceID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*coreentity.InternalPaymentAttempt)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, tenantID, invoiceID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// InternalInvoiceRepository_GetLatestPaymentAttempt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLatestPaymentAttempt'
type InternalInvoiceRepository_GetLatestPaymentAttempt_Call struct {
	*mock.Call
}

// GetLatestPaymentAttempt is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID string
//   - invoiceID string
func (_e *InternalInvoiceRepository_Expecter) GetLatestPaymentAttempt(ctx interface{}, tenantID interface{}, invoiceID interface{}) *InternalInvoiceRepository_GetLatestPaymentAttempt_Call {
	return &InternalInvoiceRepository_GetLatestPaymentAttempt_Call{Call: _e.mock.On("GetLatestPaymentAttempt", ctx, tenantID, invoiceID)}
}

func (_c *InternalInvoiceRepository_GetLatestPaymentAttempt_Call) Run(run func(ctx context.Context, tenantID string, invoiceID string)) *InternalInvoiceRepository_GetLatestPaymentAttempt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *InternalInvoiceRepository_GetLatestPaymentAttempt_Call) Return(internalPaymentAttempt *coreentity.InternalPaymentAttempt, err error) *InternalInvoiceRepository_GetLatestPaymentAttempt_Call {
	_c.Call.Return(internalPaymentAttempt, err)
	return _c
}

func (_c *InternalInvoiceRepository_GetLatestPaymentAttempt_Call) RunAndReturn(run func(ctx context.Context, tenantID string, invoiceID string) (*coreentity.InternalPaymentAttempt, error)) *InternalInvoiceRepository_GetLatestPaymentAttempt_Call {
	_c.Call.Return(run)
	return _c
}

// GetPaymentAttempt provides a mock function for the type InternalInvoiceRepository
func (_mock *InternalInvoiceRepository) GetPaymentAttempt(ctx context.Context, tenantID string, id string) (*coreentity.InternalPaymentAttempt, error) {
	ret := _mock.Called(ctx, tenantID, id)

	if len(ret) == 0 {
		panic("no return value specified for GetPaymentAttempt")
	}

	var r0 *coreentity.InternalPaymentAttempt
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*coreentity.InternalPaymentAttempt, error)); ok {
		return returnFunc(ctx, tenantID, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *coreentity.InternalPaymentAttempt); ok {
		r0 = returnFunc(ctx, tenantID, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*coreentity.InternalPaymentAttempt)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, tenantID, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// InternalInvoiceRepository_GetPaymentAttempt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPaymentAttempt'
type InternalInvoiceRepository_GetPaymentAttempt_Call struct {
	*mock.Call
}

// GetPaymentAttempt is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID string
//   - id string
func (_e *InternalInvoiceRepository_Expecter) GetPaymentAttempt(ctx interface{}, tenantID interface{}, id interface{}) *InternalInvoiceRepository_GetPaymentAttempt_Call {
	return &InternalInvoiceRepository_GetPaymentAttempt_Call{Call: _e.mock.On("GetPaymentAttempt", ctx, tenantID, id)}
}

func (_c *InternalInvoiceRepository_GetPaymentAttempt_Call) Run(run func(ctx context.Context, tenantID string, id string)) *InternalInvoiceRepository_GetPaymentAttempt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *InternalInvoiceRepository_GetPaymentAttempt_Call) Return(internalPaymentAttempt *coreentity.InternalPaymentAttempt, err error) *InternalInvoiceRepository_GetPaymentAttempt_Call {
	_c.Call.Return(internalPaymentAttempt, err)
	return _c
}

func (_c *InternalInvoiceRepository_GetPaymentAttempt_Call) RunAndReturn(run func(ctx context.Context, tenantID string, id string) (*coreentity.InternalPaymentAttempt, error)) *InternalInvoiceRepository_GetPaymentAttempt_Call {
	_c.Call.Return(run)
	return _c
}

// GetPaymentAttempts provides a mock function for the type InternalInvoiceRepository
func (_mock *InternalInvoiceRepository) GetPaymentAttempts(ctx context.Context, tenantID string, invoiceID string) ([]coreentity.InternalPaymentAttempt, error) {
	ret := _mock.Called(ctx, tenantID, invoiceID)

	if len(ret) == 0 {
		panic("no return value specified for GetPaymentAttempts")
	}

	var r0 []coreentity.InternalPaymentAttempt
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) ([]coreentity.InternalPaymentAttempt, error)); ok {
		return returnFunc(ctx, tenantID, invoiceID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) []coreentity.InternalPaymentAttempt); ok {
		r0 = returnFunc(ctx, tenantID, invoiceID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]coreentity.InternalPaymentAttempt)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, tenantID, invoiceID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// InternalInvoiceRepository_GetPaymentAttempts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPaymentAttempts'
type InternalInvoiceRepository_GetPaymentAttempts_Call struct {
	*mock.Call
}

// GetPaymentAttempts is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID string
//   - invoiceID string
func (_e *InternalInvoiceRepository_Expecter) GetPaymentAttempts(ctx interface{}, tenantID interface{}, invoiceID interface{}) *InternalInvoiceRepository_GetPaymentAttempts_Call {
	return &InternalInvoiceRepository_GetPaymentAttempts_Call{Call: _e.mock.On("GetPaymentAttempts", ctx, tenantID, invoiceID)}
}

func (_c *InternalInvoiceRepository_GetPaymentAttempts_Call) Run(run func(ctx context.Context, tenantID string, invoiceID string)) *InternalInvoiceRepository_GetPaymentAttempts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *InternalInvoiceRepository_GetPaymentAttempts_Call) Return(internalPaymentAttempts []coreentity.InternalPaymentAttempt, err error) *InternalInvoiceRepository_GetPaymentAttempts_Call {
	_c.Call.Return(internalPaymentAttempts, err)
	return _c
}

func (_c *InternalInvoiceRepository_GetPaymentAttempts_Call) RunAndReturn(run func(ctx context.Context, tenantID string, invoiceID string) ([]coreentity.InternalPaymentAttempt, error)) *InternalInvoiceRepository_GetPaymentAttempts_Call {
	_c.Call.Return(run)
	return _c
}

// MarkInvoicePaid provides a mock function for the type InternalInvoiceRepository
func (_mock *InternalInvoiceRepository) MarkInvoicePaid(ctx context.Context, tenantID string, id string, amountPaid string) (*coreentity.InternalInvoice, error) {
	ret := _mock.Called(ctx, tenantID, id, amountPaid)

	if len(ret) == 0 {
		panic("no return value specified for MarkInvoicePaid")
	}

	var r0 *coreentity.InternalInvoice
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) (*coreentity.InternalInvoice, error)); ok {
		return returnFunc(ctx, tenantID, id, amountPaid)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) *coreentity.InternalInvoice); ok {
		r0 = returnFunc(ctx, tenantID, id, amountPaid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*coreentity.InternalInvoice)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = returnFunc(ctx, tenantID, id, amountPaid)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// InternalInvoiceRepository_MarkInvoicePaid_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkInvoicePaid'
type InternalInvoiceRepository_MarkInvoicePaid_Call struct {
	*mock.Call
}

// MarkInvoicePaid is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID string
//   - id string
//   - amountPaid string
func (_e *InternalInvoiceRepository_Expecter) MarkInvoicePaid(ctx interface{}, tenantID interface{}, id interface{}, amountPaid interface{}) *InternalInvoiceRepository_MarkInvoicePaid_Call {
	return &InternalInvoiceRepository_MarkInvoicePaid_Call{Call: _e.mock.On("MarkInvoicePaid", ctx, tenantID, id, amountPaid)}
}

func (_c *InternalInvoiceRepository_MarkInvoicePaid_Call) Run(run func(ctx context.Context, tenantID string, id string, amountPaid string)) *InternalInvoiceRepository_MarkInvoicePaid_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *InternalInvoiceRepository_MarkInvoicePaid_Call) Return(internalInvoice *coreentity.InternalInvoice, err error) *InternalInvoiceRepository_MarkInvoicePaid_Call {
	_c.Call.Return(internalInvoice, err)
	return _c
}

func (_c *InternalInvoiceRepository_MarkInvoicePaid_Call) RunAndReturn(run func(ctx context.Context, tenantID string, id string, amountPaid string) (*coreentity.InternalInvoice, error)) *InternalInvoiceRepository_MarkInvoicePaid_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePaymentAttemptGateway provides a mock function for the type InternalInvoiceRepository
func (_mock *InternalInvoiceRepository) UpdatePaymentAttemptGateway(ctx context.Context, data coreentity.InternalPaymentAttempt) (*coreentity.InternalPaymentAttempt, error) {
	ret := _mock.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePaymentAttemptGateway")
	}

	var r0 *coreentity.InternalPaymentAttempt
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.InternalPaymentAttempt) (*coreentity.InternalPaymentAttempt, error)); ok {
		return returnFunc(ctx, data)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.InternalPaymentAttempt) *coreentity.InternalPaymentAttempt); ok {
		r0 = returnFunc(ctx, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*coreentity.InternalPaymentAttempt)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, coreentity.InternalPaymentAttempt) error); ok {
		r1 = returnFunc(ctx, data)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// InternalInvoiceRepository_UpdatePaymentAttemptGateway_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePaymentAttemptGateway'
type InternalInvoiceRepository_UpdatePaymentAttemptGateway_Call struct {
	*mock.Call
}

// UpdatePaymentAttemptGateway is a helper method to define mock.On call
//   - ctx context.Context
//   - data coreentity.InternalPaymentAttempt
func (_e *InternalInvoiceRepository_Expecter) UpdatePaymentAttemptGateway(ctx interface{}, data interface{}) *InternalInvoiceRepository_UpdatePaymentAttemptGateway_Call {
	return &InternalInvoiceRepository_UpdatePaymentAttemptGateway_Call{Call: _e.mock.On("UpdatePaymentAttemptGateway", ctx, data)}
}

func (_c *InternalInvoiceRepository_UpdatePaymentAttemptGateway_Call) Run(run func(ctx context.Context, data coreentity.InternalPaymentAttempt)) *InternalInvoiceRepository_UpdatePaymentAttemptGateway_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 coreentity.InternalPaymentAttempt
		if args[1] != nil {
			arg1 = args[1].(coreentity.InternalPaymentAttempt)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *InternalInvoiceRepository_UpdatePaymentAttemptGateway_Call) Return(internalPaymentAttempt *coreentity.InternalPaymentAttempt, err error) *InternalInvoiceRepository_UpdatePaymentAttemptGateway_Call {
	_c.Call.Return(internalPaymentAttempt, err)
	return _c
}

func (_c *InternalInvoiceRepository_UpdatePaymentAttemptGateway_Call) RunAndReturn(run func(ctx context.Context, data coreentity.InternalPaymentAttempt) (*coreentity.InternalPaymentAttempt, error)) *InternalInvoiceRepository_UpdatePaymentAttemptGateway_Call {
	_c.Call.Return(run)
	return _c
}
