// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"codebase-app/internal/entity/coreentity"
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewInternalQuotationRepository creates a new instance of InternalQuotationRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInternalQuotationRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *InternalQuotationRepository {
	mock := &InternalQuotationRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// InternalQuotationRepository is an autogenerated mock type for the InternalQuotationRepository type
type InternalQuotationRepository struct {
	mock.Mock
}

type InternalQuotationRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *InternalQuotationRepository) EXPECT() *InternalQuotationRepository_Expecter {
	return &InternalQuotationRepository_Expecter{mock: &_m.Mock}
}

// ApproveQuotation provides a mock function for the type InternalQuotationRepository
func (_mock *InternalQuotationRepository) ApproveQuotation(ctx context.Context, tenantID string, id string) (*coreentity.InternalQuotation, error) {
	ret := _mock.Called(ctx, tenantID, id)

	if len(ret) == 0 {
		panic("no return value specified for ApproveQuotation")
	}

	var r0 *coreentity.InternalQuotation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*coreentity.InternalQuotation, error)); ok {
		return returnFunc(ctx, tenantID, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *coreentity.InternalQuotation); ok {
		r0 = returnFunc(ctx, tenantID, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*coreentity.InternalQuotation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, tenantID, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// InternalQuotationRepository_ApproveQuotation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ApproveQuotation'
type InternalQuotationRepository_ApproveQuotation_Call struct {
	*mock.Call
}

// ApproveQuotation is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID string
//   - id string
func (_e *InternalQuotationRepository_Expecter) ApproveQuotation(ctx interface{}, tenantID interface{}, id interface{}) *InternalQuotationRepository_ApproveQuotation_Call {
	return &InternalQuotationRepository_ApproveQuotation_Call{Call: _e.mock.On("ApproveQuotation", ctx, tenantID, id)}
}

func (_c *InternalQuotationRepository_ApproveQuotation_Call) Run(run func(ctx context.Context, tenantID string, id string)) *InternalQuotationRepository_ApproveQuotation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *InternalQuotationRepository_ApproveQuotation_Call) Return(internalQuotation *coreentity.InternalQuotation, err error) *InternalQuotationRepository_ApproveQuotation_Call {
	_c.Call.Return(internalQuotation, err)
	return _c
}

func (_c *InternalQuotationRepository_ApproveQuotation_Call) RunAndReturn(run func(ctx context.Context, tenantID string, id string) (*coreentity.InternalQuotation, error)) *InternalQuotationRepository_ApproveQuotation_Call {
	_c.Call.Return(run)
	return _c
}

// CreateQuotation provides a mock function for the type InternalQuotationRepository
func (_mock *InternalQuotationRepository) CreateQuotation(ctx context.Context, data coreentity.InternalQuotation) (*coreentity.InternalQuotation, error) {
	ret := _mock.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for CreateQuotation")
	}

	var r0 *coreentity.InternalQuotation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.InternalQuotation) (*coreentity.InternalQuotation, error)); ok {
		return returnFunc(ctx, data)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.InternalQuotation) *coreentity.InternalQuotation); ok {
		r0 = returnFunc(ctx, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*coreentity.InternalQuotation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, coreentity.InternalQuotation) error); ok {
		r1 = returnFunc(ctx, data)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// InternalQuotationRepository_CreateQuotation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateQuotation'
type InternalQuotationRepository_CreateQuotation_Call struct {
	*mock.Call
}

// CreateQuotation is a helper method to define mock.On call
//   - ctx context.Context
//   - data coreentity.InternalQuotation
func (_e *InternalQuotationRepository_Expecter) CreateQuotation(ctx interface{}, data interface{}) *InternalQuotationRepository_CreateQuotation_Call {
	return &InternalQuotationRepository_CreateQuotation_Call{Call: _e.mock.On("CreateQuotation", ctx, data)}
}

func (_c *InternalQuotationRepository_CreateQuotation_Call) Run(run func(ctx context.Context, data coreentity.InternalQuotation)) *InternalQuotationRepository_CreateQuotation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 coreentity.InternalQuotation
		if args[1] != nil {
			arg1 = args[1].(coreentity.InternalQuotation)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *InternalQuotationRepository_CreateQuotation_Call) Return(internalQuotation *coreentity.InternalQuotation, err error) *InternalQuotationRepository_CreateQuotation_Call {
	_c.Call.Return(internalQuotation, err)
	return _c
}

func (_c *InternalQuotationRepository_CreateQuotation_Call) RunAndReturn(run func(ctx context.Context, data coreentity.InternalQuotation) (*coreentity.InternalQuotation, error)) *InternalQuotationRepository_CreateQuotation_Call {
	_c.Call.Return(run)
	return _c
}

// GetQuotation provides a mock function for the type InternalQuotationRepository
func (_mock *InternalQuotationRepository) GetQuotation(ctx context.Context, tenantID string, id string) (*coreentity.InternalQuotation, error) {
	ret := _mock.Called(ctx, tenantID, id)

	if len(ret) == 0 {
		panic("no return value specified for GetQuotation")
	}

	var r0 *coreentity.InternalQuotation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*coreentity.InternalQuotation, error)); ok {
		return returnFunc(ctx, tenantID, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *coreentity.InternalQuotation); ok {
		r0 = returnFunc(ctx, tenantID, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*coreentity.InternalQuotation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, tenantID, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// InternalQuotationRepository_GetQuotation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetQuotation'
type InternalQuotationRepository_GetQuotation_Call struct {
	*mock.Call
}

// GetQuotation is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID string
//   - id string
func (_e *InternalQuotationRepository_Expecter) GetQuotation(ctx interface{}, tenantID interface{}, id interface{}) *InternalQuotationRepository_GetQuotation_Call {
	return &InternalQuotationRepository_GetQuotation_Call{Call: _e.mock.On("GetQuotation", ctx, tenantID, id)}
}

func (_c *InternalQuotationRepository_GetQuotation_Call) Run(run func(ctx context.Context, tenantID string, id string)) *InternalQuotationRepository_GetQuotation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *InternalQuotationRepository_GetQuotation_Call) Return(internalQuotation *coreentity.InternalQuotation, err error) *InternalQuotationRepository_GetQuotation_Call {
	_c.Call.Return(internalQuotation, err)
	return _c
}

func (_c *InternalQuotationRepository_GetQuotation_Call) RunAndReturn(run func(ctx context.Context, tenantID string, id string) (*coreentity.InternalQuotation, error)) *InternalQuotationRepository_GetQuotation_Call {
	_c.Call.Return(run)
	return _c
}

// GetQuotations provides a mock function for the type InternalQuotationRepository
func (_mock *InternalQuotationRepository) GetQuotations(ctx context.Context, filter coreentity.InternalCommerceListFilter) ([]coreentity.InternalQuotation, int, error) {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetQuotations")
	}

	var r0 []coreentity.InternalQuotation
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.InternalCommerceListFilter) ([]coreentity.InternalQuotation, int, error)); ok {
		return returnFunc(ctx, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.InternalCommerceListFilter) []coreentity.InternalQuotation); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]coreentity.InternalQuotation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, coreentity.InternalCommerceListFilter) int); ok {
		r1 = returnFunc(ctx, filter)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, coreentity.InternalCommerceListFilter) error); ok {
		r2 = returnFunc(ctx, filter)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// InternalQuotationRepository_GetQuotations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetQuotations'
type InternalQuotationRepository_GetQuotations_Call struct {
	*mock.Call
}

// GetQuotations is a helper method to define mock.On call
//   - ctx context.Context
//   - filter coreentity.InternalCommerceListFilter
func (_e *InternalQuotationRepository_Expecter) GetQuotations(ctx interface{}, filter interface{}) *InternalQuotationRepository_GetQuotations_Call {
	return &InternalQuotationRepository_GetQuotations_Call{Call: _e.mock.On("GetQuotations", ctx, filter)}
}

func (_c *InternalQuotationRepository_GetQuotations_Call) Run(run func(ctx context.Context, filter coreentity.InternalCommerceListFilter)) *InternalQuotationRepository_GetQuotations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 coreentity.InternalCommerceListFilter
		if args[1] != nil {
			arg1 = args[1].(coreentity.InternalCommerceListFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *InternalQuotationRepository_GetQuotations_Call) Return(internalQuotations []coreentity.InternalQuotation, n int, err error) *InternalQuotationRepository_GetQuotations_Call {
	_c.Call.Return(internalQuotations, n, err)
	return _c
}

func (_c *InternalQuotationRepository_GetQuotations_Call) RunAndReturn(run func(ctx context.Context, filter coreentity.InternalCommerceListFilter) ([]coreentity.InternalQuotation, int, error)) *InternalQuotationRepository_GetQuotations_Call {
	_c.Call.Return(run)
	return _c
}

// MarkQuotationConverted provides a mock function for the type InternalQuotationRepository
func (_mock *InternalQuotationRepository) MarkQuotationConverted(ctx context.Context, tenantID string, quotationID string, orderID string) (*coreentity.InternalQuotation, error) {
	ret := _mock.Called(ctx, tenantID, quotationID, orderID)

	if len(ret) == 0 {
		panic("no return value specified for MarkQuotationConverted")
	}

	var r0 *coreentity.InternalQuotation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) (*coreentity.InternalQuotation, error)); ok {
		return returnFunc(ctx, tenantID, quotationID, orderID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) *coreentity.InternalQuotation); ok {
		r0 = returnFunc(ctx, tenantID, quotationID, orderID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*coreentity.InternalQuotation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = returnFunc(ctx, tenantID, quotationID, orderID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// InternalQuotationRepository_MarkQuotationConverted_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkQuotationConverted'
type InternalQuotationRepository_MarkQuotationConverted_Call struct {
	*mock.Call
}

// MarkQuotationConverted is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID string
//   - quotationID string
//   - orderID string
func (_e *InternalQuotationRepository_Expecter) MarkQuotationConverted(ctx interface{}, tenantID interface{}, quotationID interface{}, orderID interface{}) *InternalQuotationRepository_MarkQuotationConverted_Call {
	return &InternalQuotationRepository_MarkQuotationConverted_Call{Call: _e.mock.On("MarkQuotationConverted", ctx, tenantID, quotationID, orderID)}
}

func (_c *InternalQuotationRepository_MarkQuotationConverted_Call) Run(run func(ctx context.Context, tenantID string, quotationID string, orderID string)) *InternalQuotationRepository_MarkQuotationConverted_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *InternalQuotationRepository_MarkQuotationConverted_Call) Return(internalQuotation *coreentity.InternalQuotation, err error) *InternalQuotationRepository_MarkQuotationConverted_Call {
	_c.Call.Return(internalQuotation, err)
	return _c
}

func (_c *InternalQuotationRepository_MarkQuotationConverted_Call) RunAndReturn(run func(ctx context.Context, tenantID string, quotationID string, orderID string) (*coreentity.InternalQuotation, error)) *InternalQuotationRepository_MarkQuotationConverted_Call {
	_c.Call.Return(run)
	return _c
}
