// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"codebase-app/internal/entity/coreentity"
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewJobPositionRepository creates a new instance of JobPositionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewJobPositionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *JobPositionRepository {
	mock := &JobPositionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// JobPositionRepository is an autogenerated mock type for the JobPositionRepository type
type JobPositionRepository struct {
	mock.Mock
}

type JobPositionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *JobPositionRepository) EXPECT() *JobPositionRepository_Expecter {
	return &JobPositionRepository_Expecter{mock: &_m.Mock}
}

// CreateJobPosition provides a mock function for the type JobPositionRepository
func (_mock *JobPositionRepository) CreateJobPosition(ctx context.Context, data coreentity.JobPosition) (*coreentity.JobPosition, error) {
	ret := _mock.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for CreateJobPosition")
	}

	var r0 *coreentity.JobPosition
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.JobPosition) (*coreentity.JobPosition, error)); ok {
		return returnFunc(ctx, data)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.JobPosition) *coreentity.JobPosition); ok {
		r0 = returnFunc(ctx, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*coreentity.JobPosition)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, coreentity.JobPosition) error); ok {
		r1 = returnFunc(ctx, data)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// JobPositionRepository_CreateJobPosition_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateJobPosition'
type JobPositionRepository_CreateJobPosition_Call struct {
	*mock.Call
}

// CreateJobPosition is a helper method to define mock.On call
//   - ctx context.Context
//   - data coreentity.JobPosition
func (_e *JobPositionRepository_Expecter) CreateJobPosition(ctx interface{}, data interface{}) *JobPositionRepository_CreateJobPosition_Call {
	return &JobPositionRepository_CreateJobPosition_Call{Call: _e.mock.On("CreateJobPosition", ctx, data)}
}

func (_c *JobPositionRepository_CreateJobPosition_Call) Run(run func(ctx context.Context, data coreentity.JobPosition)) *JobPositionRepository_CreateJobPosition_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 coreentity.JobPosition
		if args[1] != nil {
			arg1 = args[1].(coreentity.JobPosition)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *JobPositionRepository_CreateJobPosition_Call) Return(jobPosition *coreentity.JobPosition, err error) *JobPositionRepository_CreateJobPosition_Call {
	_c.Call.Return(jobPosition, err)
	return _c
}

func (_c *JobPositionRepository_CreateJobPosition_Call) RunAndReturn(run func(ctx context.Context, data coreentity.JobPosition) (*coreentity.JobPosition, error)) *JobPositionRepository_CreateJobPosition_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteJobPosition provides a mock function for the type JobPositionRepository
func (_mock *JobPositionRepository) DeleteJobPosition(ctx context.Context, filter coreentity.JobPositionDeleteFilter) error {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for DeleteJobPosition")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.JobPositionDeleteFilter) error); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// JobPositionRepository_DeleteJobPosition_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteJobPosition'
type JobPositionRepository_DeleteJobPosition_Call struct {
	*mock.Call
}

// DeleteJobPosition is a helper method to define mock.On call
//   - ctx context.Context
//   - filter coreentity.JobPositionDeleteFilter
func (_e *JobPositionRepository_Expecter) DeleteJobPosition(ctx interface{}, filter interface{}) *JobPositionRepository_DeleteJobPosition_Call {
	return &JobPositionRepository_DeleteJobPosition_Call{Call: _e.mock.On("DeleteJobPosition", ctx, filter)}
}

func (_c *JobPositionRepository_DeleteJobPosition_Call) Run(run func(ctx context.Context, filter coreentity.JobPositionDeleteFilter)) *JobPositionRepository_DeleteJobPosition_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 coreentity.JobPositionDeleteFilter
		if args[1] != nil {
			arg1 = args[1].(coreentity.JobPositionDeleteFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *JobPositionRepository_DeleteJobPosition_Call) Return(err error) *JobPositionRepository_DeleteJobPosition_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *JobPositionRepository_DeleteJobPosition_Call) RunAndReturn(run func(ctx context.Context, filter coreentity.JobPositionDeleteFilter) error) *JobPositionRepository_DeleteJobPosition_Call {
	_c.Call.Return(run)
	return _c
}

// GetJobPosition provides a mock function for the type JobPositionRepository
func (_mock *JobPositionRepository) GetJobPosition(ctx context.Context, filter coreentity.JobPosition) (*coreentity.JobPosition, error) {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetJobPosition")
	}

	var r0 *coreentity.JobPosition
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.JobPosition) (*coreentity.JobPosition, error)); ok {
		return returnFunc(ctx, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.JobPosition) *coreentity.JobPosition); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*coreentity.JobPosition)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, coreentity.JobPosition) error); ok {
		r1 = returnFunc(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// JobPositionRepository_GetJobPosition_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetJobPosition'
type JobPositionRepository_GetJobPosition_Call struct {
	*mock.Call
}

// GetJobPosition is a helper method to define mock.On call
//   - ctx context.Context
//   - filter coreentity.JobPosition
func (_e *JobPositionRepository_Expecter) GetJobPosition(ctx interface{}, filter interface{}) *JobPositionRepository_GetJobPosition_Call {
	return &JobPositionRepository_GetJobPosition_Call{Call: _e.mock.On("GetJobPosition", ctx, filter)}
}

func (_c *JobPositionRepository_GetJobPosition_Call) Run(run func(ctx context.Context, filter coreentity.JobPosition)) *JobPositionRepository_GetJobPosition_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 coreentity.JobPosition
		if args[1] != nil {
			arg1 = args[1].(coreentity.JobPosition)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *JobPositionRepository_GetJobPosition_Call) Return(jobPosition *coreentity.JobPosition, err error) *JobPositionRepository_GetJobPosition_Call {
	_c.Call.Return(jobPosition, err)
	return _c
}

func (_c *JobPositionRepository_GetJobPosition_Call) RunAndReturn(run func(ctx context.Context, filter coreentity.JobPosition) (*coreentity.JobPosition, error)) *JobPositionRepository_GetJobPosition_Call {
	_c.Call.Return(run)
	return _c
}

// GetJobPositions provides a mock function for the type JobPositionRepository
func (_mock *JobPositionRepository) GetJobPositions(ctx context.Context, filter coreentity.JobPositionListFilter) ([]coreentity.JobPosition, int, error) {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetJobPositions")
	}

	var r0 []coreentity.JobPosition
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.JobPositionListFilter) ([]coreentity.JobPosition, int, error)); ok {
		return returnFunc(ctx, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.JobPositionListFilter) []coreentity.JobPosition); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]coreentity.JobPosition)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, coreentity.JobPositionListFilter) int); ok {
		r1 = returnFunc(ctx, filter)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, coreentity.JobPositionListFilter) error); ok {
		r2 = returnFunc(ctx, filter)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// JobPositionRepository_GetJobPositions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetJobPositions'
type JobPositionRepository_GetJobPositions_Call struct {
	*mock.Call
}

// GetJobPositions is a helper method to define mock.On call
//   - ctx context.Context
//   - filter coreentity.JobPositionListFilter
func (_e *JobPositionRepository_Expecter) GetJobPositions(ctx interface{}, filter interface{}) *JobPositionRepository_GetJobPositions_Call {
	return &JobPositionRepository_GetJobPositions_Call{Call: _e.mock.On("GetJobPositions", ctx, filter)}
}

func (_c *JobPositionRepository_GetJobPositions_Call) Run(run func(ctx context.Context, filter coreentity.JobPositionListFilter)) *JobPositionRepository_GetJobPositions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 coreentity.JobPositionListFilter
		if args[1] != nil {
			arg1 = args[1].(coreentity.JobPositionListFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *JobPositionRepository_GetJobPositions_Call) Return(jobPositions []coreentity.JobPosition, n int, err error) *JobPositionRepository_GetJobPositions_Call {
	_c.Call.Return(jobPositions, n, err)
	return _c
}

func (_c *JobPositionRepository_GetJobPositions_Call) RunAndReturn(run func(ctx context.Context, filter coreentity.JobPositionListFilter) ([]coreentity.JobPosition, int, error)) *JobPositionRepository_GetJobPositions_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateJobPosition provides a mock function for the type JobPositionRepository
func (_mock *JobPositionRepository) UpdateJobPosition(ctx context.Context, data coreentity.JobPosition) error {
	ret := _mock.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for UpdateJobPosition")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.JobPosition) error); ok {
		r0 = returnFunc(ctx, data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// JobPositionRepository_UpdateJobPosition_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateJobPosition'
type JobPositionRepository_UpdateJobPosition_Call struct {
	*mock.Call
}

// UpdateJobPosition is a helper method to define mock.On call
//   - ctx context.Context
//   - data coreentity.JobPosition
func (_e *JobPositionRepository_Expecter) UpdateJobPosition(ctx interface{}, data interface{}) *JobPositionRepository_UpdateJobPosition_Call {
	return &JobPositionRepository_UpdateJobPosition_Call{Call: _e.mock.On("UpdateJobPosition", ctx, data)}
}

func (_c *JobPositionRepository_UpdateJobPosition_Call) Run(run func(ctx context.Context, data coreentity.JobPosition)) *JobPositionRepository_UpdateJobPosition_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 coreentity.JobPosition
		if args[1] != nil {
			arg1 = args[1].(coreentity.JobPosition)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *JobPositionRepository_UpdateJobPosition_Call) Return(err error) *JobPositionRepository_UpdateJobPosition_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *JobPositionRepository_UpdateJobPosition_Call) RunAndReturn(run func(ctx context.Context, data coreentity.JobPosition) error) *JobPositionRepository_UpdateJobPosition_Call {
	_c.Call.Return(run)
	return _c
}
