// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"codebase-app/internal/entity/coreentity"
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMasterRepository creates a new instance of MasterRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMasterRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MasterRepository {
	mock := &MasterRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MasterRepository is an autogenerated mock type for the MasterRepository type
type MasterRepository struct {
	mock.Mock
}

type MasterRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MasterRepository) EXPECT() *MasterRepository_Expecter {
	return &MasterRepository_Expecter{mock: &_m.Mock}
}

// CreateEmployee provides a mock function for the type MasterRepository
func (_mock *MasterRepository) CreateEmployee(ctx context.Context, data coreentity.Employee) (*coreentity.Employee, error) {
	ret := _mock.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for CreateEmployee")
	}

	var r0 *coreentity.Employee
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.Employee) (*coreentity.Employee, error)); ok {
		return returnFunc(ctx, data)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.Employee) *coreentity.Employee); ok {
		r0 = returnFunc(ctx, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*coreentity.Employee)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, coreentity.Employee) error); ok {
		r1 = returnFunc(ctx, data)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MasterRepository_CreateEmployee_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateEmployee'
type MasterRepository_CreateEmployee_Call struct {
	*mock.Call
}

// CreateEmployee is a helper method to define mock.On call
//   - ctx context.Context
//   - data coreentity.Employee
func (_e *MasterRepository_Expecter) CreateEmployee(ctx interface{}, data interface{}) *MasterRepository_CreateEmployee_Call {
	return &MasterRepository_CreateEmployee_Call{Call: _e.mock.On("CreateEmployee", ctx, data)}
}

func (_c *MasterRepository_CreateEmployee_Call) Run(run func(ctx context.Context, data coreentity.Employee)) *MasterRepository_CreateEmployee_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 coreentity.Employee
		if args[1] != nil {
			arg1 = args[1].(coreentity.Employee)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MasterRepository_CreateEmployee_Call) Return(employee *coreentity.Employee, err error) *MasterRepository_CreateEmployee_Call {
	_c.Call.Return(employee, err)
	return _c
}

func (_c *MasterRepository_CreateEmployee_Call) RunAndReturn(run func(ctx context.Context, data coreentity.Employee) (*coreentity.Employee, error)) *MasterRepository_CreateEmployee_Call {
	_c.Call.Return(run)
	return _c
}

// CreateJobPosition provides a mock function for the type MasterRepository
func (_mock *MasterRepository) CreateJobPosition(ctx context.Context, data coreentity.JobPosition) (*coreentity.JobPosition, error) {
	ret := _mock.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for CreateJobPosition")
	}

	var r0 *coreentity.JobPosition
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.JobPosition) (*coreentity.JobPosition, error)); ok {
		return returnFunc(ctx, data)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.JobPosition) *coreentity.JobPosition); ok {
		r0 = returnFunc(ctx, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*coreentity.JobPosition)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, coreentity.JobPosition) error); ok {
		r1 = returnFunc(ctx, data)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MasterRepository_CreateJobPosition_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateJobPosition'
type MasterRepository_CreateJobPosition_Call struct {
	*mock.Call
}

// CreateJobPosition is a helper method to define mock.On call
//   - ctx context.Context
//   - data coreentity.JobPosition
func (_e *MasterRepository_Expecter) CreateJobPosition(ctx interface{}, data interface{}) *MasterRepository_CreateJobPosition_Call {
	return &MasterRepository_CreateJobPosition_Call{Call: _e.mock.On("CreateJobPosition", ctx, data)}
}

func (_c *MasterRepository_CreateJobPosition_Call) Run(run func(ctx context.Context, data coreentity.JobPosition)) *MasterRepository_CreateJobPosition_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 coreentity.JobPosition
		if args[1] != nil {
			arg1 = args[1].(coreentity.JobPosition)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MasterRepository_CreateJobPosition_Call) Return(jobPosition *coreentity.JobPosition, err error) *MasterRepository_CreateJobPosition_Call {
	_c.Call.Return(jobPosition, err)
	return _c
}

func (_c *MasterRepository_CreateJobPosition_Call) RunAndReturn(run func(ctx context.Context, data coreentity.JobPosition) (*coreentity.JobPosition, error)) *MasterRepository_CreateJobPosition_Call {
	_c.Call.Return(run)
	return _c
}

// CreateOrgUnit provides a mock function for the type MasterRepository
func (_mock *MasterRepository) CreateOrgUnit(ctx context.Context, data coreentity.OrgUnit) (*coreentity.OrgUnit, error) {
	ret := _mock.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrgUnit")
	}

	var r0 *coreentity.OrgUnit
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.OrgUnit) (*coreentity.OrgUnit, error)); ok {
		return returnFunc(ctx, data)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.OrgUnit) *coreentity.OrgUnit); ok {
		r0 = returnFunc(ctx, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*coreentity.OrgUnit)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, coreentity.OrgUnit) error); ok {
		r1 = returnFunc(ctx, data)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MasterRepository_CreateOrgUnit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOrgUnit'
type MasterRepository_CreateOrgUnit_Call struct {
	*mock.Call
}

// CreateOrgUnit is a helper method to define mock.On call
//   - ctx context.Context
//   - data coreentity.OrgUnit
func (_e *MasterRepository_Expecter) CreateOrgUnit(ctx interface{}, data interface{}) *MasterRepository_CreateOrgUnit_Call {
	return &MasterRepository_CreateOrgUnit_Call{Call: _e.mock.On("CreateOrgUnit", ctx, data)}
}

func (_c *MasterRepository_CreateOrgUnit_Call) Run(run func(ctx context.Context, data coreentity.OrgUnit)) *MasterRepository_CreateOrgUnit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 coreentity.OrgUnit
		if args[1] != nil {
			arg1 = args[1].(coreentity.OrgUnit)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MasterRepository_CreateOrgUnit_Call) Return(orgUnit *coreentity.OrgUnit, err error) *MasterRepository_CreateOrgUnit_Call {
	_c.Call.Return(orgUnit, err)
	return _c
}

func (_c *MasterRepository_CreateOrgUnit_Call) RunAndReturn(run func(ctx context.Context, data coreentity.OrgUnit) (*coreentity.OrgUnit, error)) *MasterRepository_CreateOrgUnit_Call {
	_c.Call.Return(run)
	return _c
}

// CreateWorkLocation provides a mock function for the type MasterRepository
func (_mock *MasterRepository) CreateWorkLocation(ctx context.Context, data coreentity.WorkLocation) (*coreentity.WorkLocation, error) {
	ret := _mock.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for CreateWorkLocation")
	}

	var r0 *coreentity.WorkLocation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.WorkLocation) (*coreentity.WorkLocation, error)); ok {
		return returnFunc(ctx, data)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.WorkLocation) *coreentity.WorkLocation); ok {
		r0 = returnFunc(ctx, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*coreentity.WorkLocation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, coreentity.WorkLocation) error); ok {
		r1 = returnFunc(ctx, data)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MasterRepository_CreateWorkLocation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateWorkLocation'
type MasterRepository_CreateWorkLocation_Call struct {
	*mock.Call
}

// CreateWorkLocation is a helper method to define mock.On call
//   - ctx context.Context
//   - data coreentity.WorkLocation
func (_e *MasterRepository_Expecter) CreateWorkLocation(ctx interface{}, data interface{}) *MasterRepository_CreateWorkLocation_Call {
	return &MasterRepository_CreateWorkLocation_Call{Call: _e.mock.On("CreateWorkLocation", ctx, data)}
}

func (_c *MasterRepository_CreateWorkLocation_Call) Run(run func(ctx context.Context, data coreentity.WorkLocation)) *MasterRepository_CreateWorkLocation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 coreentity.WorkLocation
		if args[1] != nil {
			arg1 = args[1].(coreentity.WorkLocation)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MasterRepository_CreateWorkLocation_Call) Return(workLocation *coreentity.WorkLocation, err error) *MasterRepository_CreateWorkLocation_Call {
	_c.Call.Return(workLocation, err)
	return _c
}

func (_c *MasterRepository_CreateWorkLocation_Call) RunAndReturn(run func(ctx context.Context, data coreentity.WorkLocation) (*coreentity.WorkLocation, error)) *MasterRepository_CreateWorkLocation_Call {
	_c.Call.Return(run)
	return _c
}

// CreateWorkShift provides a mock function for the type MasterRepository
func (_mock *MasterRepository) CreateWorkShift(ctx context.Context, data coreentity.WorkShift) (*coreentity.WorkShift, error) {
	ret := _mock.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for CreateWorkShift")
	}

	var r0 *coreentity.WorkShift
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.WorkShift) (*coreentity.WorkShift, error)); ok {
		return returnFunc(ctx, data)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.WorkShift) *coreentity.WorkShift); ok {
		r0 = returnFunc(ctx, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*coreentity.WorkShift)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, coreentity.WorkShift) error); ok {
		r1 = returnFunc(ctx, data)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MasterRepository_CreateWorkShift_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateWorkShift'
type MasterRepository_CreateWorkShift_Call struct {
	*mock.Call
}

// CreateWorkShift is a helper method to define mock.On call
//   - ctx context.Context
//   - data coreentity.WorkShift
func (_e *MasterRepository_Expecter) CreateWorkShift(ctx interface{}, data interface{}) *MasterRepository_CreateWorkShift_Call {
	return &MasterRepository_CreateWorkShift_Call{Call: _e.mock.On("CreateWorkShift", ctx, data)}
}

func (_c *MasterRepository_CreateWorkShift_Call) Run(run func(ctx context.Context, data coreentity.WorkShift)) *MasterRepository_CreateWorkShift_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 coreentity.WorkShift
		if args[1] != nil {
			arg1 = args[1].(coreentity.WorkShift)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MasterRepository_CreateWorkShift_Call) Return(workShift *coreentity.WorkShift, err error) *MasterRepository_CreateWorkShift_Call {
	_c.Call.Return(workShift, err)
	return _c
}

func (_c *MasterRepository_CreateWorkShift_Call) RunAndReturn(run func(ctx context.Context, data coreentity.WorkShift) (*coreentity.WorkShift, error)) *MasterRepository_CreateWorkShift_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteEmployee provides a mock function for the type MasterRepository
func (_mock *MasterRepository) DeleteEmployee(ctx context.Context, filter coreentity.EmployeeDeleteFilter) error {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for DeleteEmployee")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.EmployeeDeleteFilter) error); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MasterRepository_DeleteEmployee_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteEmployee'
type MasterRepository_DeleteEmployee_Call struct {
	*mock.Call
}

// DeleteEmployee is a helper method to define mock.On call
//   - ctx context.Context
//   - filter coreentity.EmployeeDeleteFilter
func (_e *MasterRepository_Expecter) DeleteEmployee(ctx interface{}, filter interface{}) *MasterRepository_DeleteEmployee_Call {
	return &MasterRepository_DeleteEmployee_Call{Call: _e.mock.On("DeleteEmployee", ctx, filter)}
}

func (_c *MasterRepository_DeleteEmployee_Call) Run(run func(ctx context.Context, filter coreentity.EmployeeDeleteFilter)) *MasterRepository_DeleteEmployee_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 coreentity.EmployeeDeleteFilter
		if args[1] != nil {
			arg1 = args[1].(coreentity.EmployeeDeleteFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MasterRepository_DeleteEmployee_Call) Return(err error) *MasterRepository_DeleteEmployee_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MasterRepository_DeleteEmployee_Call) RunAndReturn(run func(ctx context.Context, filter coreentity.EmployeeDeleteFilter) error) *MasterRepository_DeleteEmployee_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteJobPosition provides a mock function for the type MasterRepository
func (_mock *MasterRepository) DeleteJobPosition(ctx context.Context, filter coreentity.JobPositionDeleteFilter) error {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for DeleteJobPosition")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.JobPositionDeleteFilter) error); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MasterRepository_DeleteJobPosition_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteJobPosition'
type MasterRepository_DeleteJobPosition_Call struct {
	*mock.Call
}

// DeleteJobPosition is a helper method to define mock.On call
//   - ctx context.Context
//   - filter coreentity.JobPositionDeleteFilter
func (_e *MasterRepository_Expecter) DeleteJobPosition(ctx interface{}, filter interface{}) *MasterRepository_DeleteJobPosition_Call {
	return &MasterRepository_DeleteJobPosition_Call{Call: _e.mock.On("DeleteJobPosition", ctx, filter)}
}

func (_c *MasterRepository_DeleteJobPosition_Call) Run(run func(ctx context.Context, filter coreentity.JobPositionDeleteFilter)) *MasterRepository_DeleteJobPosition_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 coreentity.JobPositionDeleteFilter
		if args[1] != nil {
			arg1 = args[1].(coreentity.JobPositionDeleteFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MasterRepository_DeleteJobPosition_Call) Return(err error) *MasterRepository_DeleteJobPosition_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MasterRepository_DeleteJobPosition_Call) RunAndReturn(run func(ctx context.Context, filter coreentity.JobPositionDeleteFilter) error) *MasterRepository_DeleteJobPosition_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteOrgUnit provides a mock function for the type MasterRepository
func (_mock *MasterRepository) DeleteOrgUnit(ctx context.Context, filter coreentity.OrgUnitDeleteFilter) error {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for DeleteOrgUnit")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.OrgUnitDeleteFilter) error); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MasterRepository_DeleteOrgUnit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteOrgUnit'
type MasterRepository_DeleteOrgUnit_Call struct {
	*mock.Call
}

// DeleteOrgUnit is a helper method to define mock.On call
//   - ctx context.Context
//   - filter coreentity.OrgUnitDeleteFilter
func (_e *MasterRepository_Expecter) DeleteOrgUnit(ctx interface{}, filter interface{}) *MasterRepository_DeleteOrgUnit_Call {
	return &MasterRepository_DeleteOrgUnit_Call{Call: _e.mock.On("DeleteOrgUnit", ctx, filter)}
}

func (_c *MasterRepository_DeleteOrgUnit_Call) Run(run func(ctx context.Context, filter coreentity.OrgUnitDeleteFilter)) *MasterRepository_DeleteOrgUnit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 coreentity.OrgUnitDeleteFilter
		if args[1] != nil {
			arg1 = args[1].(coreentity.OrgUnitDeleteFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MasterRepository_DeleteOrgUnit_Call) Return(err error) *MasterRepository_DeleteOrgUnit_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MasterRepository_DeleteOrgUnit_Call) RunAndReturn(run func(ctx context.Context, filter coreentity.OrgUnitDeleteFilter) error) *MasterRepository_DeleteOrgUnit_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteWorkLocation provides a mock function for the type MasterRepository
func (_mock *MasterRepository) DeleteWorkLocation(ctx context.Context, filter coreentity.WorkLocationDeleteFilter) error {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for DeleteWorkLocation")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.WorkLocationDeleteFilter) error); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MasterRepository_DeleteWorkLocation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteWorkLocation'
type MasterRepository_DeleteWorkLocation_Call struct {
	*mock.Call
}

// DeleteWorkLocation is a helper method to define mock.On call
//   - ctx context.Context
//   - filter coreentity.WorkLocationDeleteFilter
func (_e *MasterRepository_Expecter) DeleteWorkLocation(ctx interface{}, filter interface{}) *MasterRepository_DeleteWorkLocation_Call {
	return &MasterRepository_DeleteWorkLocation_Call{Call: _e.mock.On("DeleteWorkLocation", ctx, filter)}
}

func (_c *MasterRepository_DeleteWorkLocation_Call) Run(run func(ctx context.Context, filter coreentity.WorkLocationDeleteFilter)) *MasterRepository_DeleteWorkLocation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 coreentity.WorkLocationDeleteFilter
		if args[1] != nil {
			arg1 = args[1].(coreentity.WorkLocationDeleteFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MasterRepository_DeleteWorkLocation_Call) Return(err error) *MasterRepository_DeleteWorkLocation_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MasterRepository_DeleteWorkLocation_Call) RunAndReturn(run func(ctx context.Context, filter coreentity.WorkLocationDeleteFilter) error) *MasterRepository_DeleteWorkLocation_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteWorkShift provides a mock function for the type MasterRepository
func (_mock *MasterRepository) DeleteWorkShift(ctx context.Context, filter coreentity.WorkShiftDeleteFilter) error {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for DeleteWorkShift")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.WorkShiftDeleteFilter) error); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MasterRepository_DeleteWorkShift_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteWorkShift'
type MasterRepository_DeleteWorkShift_Call struct {
	*mock.Call
}

// DeleteWorkShift is a helper method to define mock.On call
//   - ctx context.Context
//   - filter coreentity.WorkShiftDeleteFilter
func (_e *MasterRepository_Expecter) DeleteWorkShift(ctx interface{}, filter interface{}) *MasterRepository_DeleteWorkShift_Call {
	return &MasterRepository_DeleteWorkShift_Call{Call: _e.mock.On("DeleteWorkShift", ctx, filter)}
}

func (_c *MasterRepository_DeleteWorkShift_Call) Run(run func(ctx context.Context, filter coreentity.WorkShiftDeleteFilter)) *MasterRepository_DeleteWorkShift_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 coreentity.WorkShiftDeleteFilter
		if args[1] != nil {
			arg1 = args[1].(coreentity.WorkShiftDeleteFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MasterRepository_DeleteWorkShift_Call) Return(err error) *MasterRepository_DeleteWorkShift_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MasterRepository_DeleteWorkShift_Call) RunAndReturn(run func(ctx context.Context, filter coreentity.WorkShiftDeleteFilter) error) *MasterRepository_DeleteWorkShift_Call {
	_c.Call.Return(run)
	return _c
}

// GetEmployee provides a mock function for the type MasterRepository
func (_mock *MasterRepository) GetEmployee(ctx context.Context, filter coreentity.Employee) (*coreentity.Employee, error) {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetEmployee")
	}

	var r0 *coreentity.Employee
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.Employee) (*coreentity.Employee, error)); ok {
		return returnFunc(ctx, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.Employee) *coreentity.Employee); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*coreentity.Employee)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, coreentity.Employee) error); ok {
		r1 = returnFunc(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MasterRepository_GetEmployee_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEmployee'
type MasterRepository_GetEmployee_Call struct {
	*mock.Call
}

// GetEmployee is a helper method to define mock.On call
//   - ctx context.Context
//   - filter coreentity.Employee
func (_e *MasterRepository_Expecter) GetEmployee(ctx interface{}, filter interface{}) *MasterRepository_GetEmployee_Call {
	return &MasterRepository_GetEmployee_Call{Call: _e.mock.On("GetEmployee", ctx, filter)}
}

func (_c *MasterRepository_GetEmployee_Call) Run(run func(ctx context.Context, filter coreentity.Employee)) *MasterRepository_GetEmployee_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 coreentity.Employee
		if args[1] != nil {
			arg1 = args[1].(coreentity.Employee)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MasterRepository_GetEmployee_Call) Return(employee *coreentity.Employee, err error) *MasterRepository_GetEmployee_Call {
	_c.Call.Return(employee, err)
	return _c
}

func (_c *MasterRepository_GetEmployee_Call) RunAndReturn(run func(ctx context.Context, filter coreentity.Employee) (*coreentity.Employee, error)) *MasterRepository_GetEmployee_Call {
	_c.Call.Return(run)
	return _c
}

// GetEmployees provides a mock function for the type MasterRepository
func (_mock *MasterRepository) GetEmployees(ctx context.Context, filter coreentity.EmployeeListFilter) ([]coreentity.Employee, int, error) {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetEmployees")
	}

	var r0 []coreentity.Employee
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.EmployeeListFilter) ([]coreentity.Employee, int, error)); ok {
		return returnFunc(ctx, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.EmployeeListFilter) []coreentity.Employee); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]coreentity.Employee)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, coreentity.EmployeeListFilter) int); ok {
		r1 = returnFunc(ctx, filter)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, coreentity.EmployeeListFilter) error); ok {
		r2 = returnFunc(ctx, filter)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MasterRepository_GetEmployees_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEmployees'
type MasterRepository_GetEmployees_Call struct {
	*mock.Call
}

// GetEmployees is a helper method to define mock.On call
//   - ctx context.Context
//   - filter coreentity.EmployeeListFilter
func (_e *MasterRepository_Expecter) GetEmployees(ctx interface{}, filter interface{}) *MasterRepository_GetEmployees_Call {
	return &MasterRepository_GetEmployees_Call{Call: _e.mock.On("GetEmployees", ctx, filter)}
}

func (_c *MasterRepository_GetEmployees_Call) Run(run func(ctx context.Context, filter coreentity.EmployeeListFilter)) *MasterRepository_GetEmployees_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 coreentity.EmployeeListFilter
		if args[1] != nil {
			arg1 = args[1].(coreentity.EmployeeListFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MasterRepository_GetEmployees_Call) Return(employees []coreentity.Employee, n int, err error) *MasterRepository_GetEmployees_Call {
	_c.Call.Return(employees, n, err)
	return _c
}

func (_c *MasterRepository_GetEmployees_Call) RunAndReturn(run func(ctx context.Context, filter coreentity.EmployeeListFilter) ([]coreentity.Employee, int, error)) *MasterRepository_GetEmployees_Call {
	_c.Call.Return(run)
	return _c
}

// GetJobPosition provides a mock function for the type MasterRepository
func (_mock *MasterRepository) GetJobPosition(ctx context.Context, filter coreentity.JobPosition) (*coreentity.JobPosition, error) {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetJobPosition")
	}

	var r0 *coreentity.JobPosition
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.JobPosition) (*coreentity.JobPosition, error)); ok {
		return returnFunc(ctx, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.JobPosition) *coreentity.JobPosition); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*coreentity.JobPosition)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, coreentity.JobPosition) error); ok {
		r1 = returnFunc(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MasterRepository_GetJobPosition_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetJobPosition'
type MasterRepository_GetJobPosition_Call struct {
	*mock.Call
}

// GetJobPosition is a helper method to define mock.On call
//   - ctx context.Context
//   - filter coreentity.JobPosition
func (_e *MasterRepository_Expecter) GetJobPosition(ctx interface{}, filter interface{}) *MasterRepository_GetJobPosition_Call {
	return &MasterRepository_GetJobPosition_Call{Call: _e.mock.On("GetJobPosition", ctx, filter)}
}

func (_c *MasterRepository_GetJobPosition_Call) Run(run func(ctx context.Context, filter coreentity.JobPosition)) *MasterRepository_GetJobPosition_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 coreentity.JobPosition
		if args[1] != nil {
			arg1 = args[1].(coreentity.JobPosition)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MasterRepository_GetJobPosition_Call) Return(jobPosition *coreentity.JobPosition, err error) *MasterRepository_GetJobPosition_Call {
	_c.Call.Return(jobPosition, err)
	return _c
}

func (_c *MasterRepository_GetJobPosition_Call) RunAndReturn(run func(ctx context.Context, filter coreentity.JobPosition) (*coreentity.JobPosition, error)) *MasterRepository_GetJobPosition_Call {
	_c.Call.Return(run)
	return _c
}

// GetJobPositions provides a mock function for the type MasterRepository
func (_mock *MasterRepository) GetJobPositions(ctx context.Context, filter coreentity.JobPositionListFilter) ([]coreentity.JobPosition, int, error) {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetJobPositions")
	}

	var r0 []coreentity.JobPosition
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.JobPositionListFilter) ([]coreentity.JobPosition, int, error)); ok {
		return returnFunc(ctx, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.JobPositionListFilter) []coreentity.JobPosition); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]coreentity.JobPosition)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, coreentity.JobPositionListFilter) int); ok {
		r1 = returnFunc(ctx, filter)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, coreentity.JobPositionListFilter) error); ok {
		r2 = returnFunc(ctx, filter)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MasterRepository_GetJobPositions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetJobPositions'
type MasterRepository_GetJobPositions_Call struct {
	*mock.Call
}

// GetJobPositions is a helper method to define mock.On call
//   - ctx context.Context
//   - filter coreentity.JobPositionListFilter
func (_e *MasterRepository_Expecter) GetJobPositions(ctx interface{}, filter interface{}) *MasterRepository_GetJobPositions_Call {
	return &MasterRepository_GetJobPositions_Call{Call: _e.mock.On("GetJobPositions", ctx, filter)}
}

func (_c *MasterRepository_GetJobPositions_Call) Run(run func(ctx context.Context, filter coreentity.JobPositionListFilter)) *MasterRepository_GetJobPositions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 coreentity.JobPositionListFilter
		if args[1] != nil {
			arg1 = args[1].(coreentity.JobPositionListFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MasterRepository_GetJobPositions_Call) Return(jobPositions []coreentity.JobPosition, n int, err error) *MasterRepository_GetJobPositions_Call {
	_c.Call.Return(jobPositions, n, err)
	return _c
}

func (_c *MasterRepository_GetJobPositions_Call) RunAndReturn(run func(ctx context.Context, filter coreentity.JobPositionListFilter) ([]coreentity.JobPosition, int, error)) *MasterRepository_GetJobPositions_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrgUnit provides a mock function for the type MasterRepository
func (_mock *MasterRepository) GetOrgUnit(ctx context.Context, filter coreentity.OrgUnit) (*coreentity.OrgUnit, error) {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetOrgUnit")
	}

	var r0 *coreentity.OrgUnit
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.OrgUnit) (*coreentity.OrgUnit, error)); ok {
		return returnFunc(ctx, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.OrgUnit) *coreentity.OrgUnit); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*coreentity.OrgUnit)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, coreentity.OrgUnit) error); ok {
		r1 = returnFunc(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MasterRepository_GetOrgUnit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrgUnit'
type MasterRepository_GetOrgUnit_Call struct {
	*mock.Call
}

// GetOrgUnit is a helper method to define mock.On call
//   - ctx context.Context
//   - filter coreentity.OrgUnit
func (_e *MasterRepository_Expecter) GetOrgUnit(ctx interface{}, filter interface{}) *MasterRepository_GetOrgUnit_Call {
	return &MasterRepository_GetOrgUnit_Call{Call: _e.mock.On("GetOrgUnit", ctx, filter)}
}

func (_c *MasterRepository_GetOrgUnit_Call) Run(run func(ctx context.Context, filter coreentity.OrgUnit)) *MasterRepository_GetOrgUnit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 coreentity.OrgUnit
		if args[1] != nil {
			arg1 = args[1].(coreentity.OrgUnit)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MasterRepository_GetOrgUnit_Call) Return(orgUnit *coreentity.OrgUnit, err error) *MasterRepository_GetOrgUnit_Call {
	_c.Call.Return(orgUnit, err)
	return _c
}

func (_c *MasterRepository_GetOrgUnit_Call) RunAndReturn(run func(ctx context.Context, filter coreentity.OrgUnit) (*coreentity.OrgUnit, error)) *MasterRepository_GetOrgUnit_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrgUnits provides a mock function for the type MasterRepository
func (_mock *MasterRepository) GetOrgUnits(ctx context.Context, filter coreentity.OrgUnitListFilter) ([]coreentity.OrgUnit, int, error) {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetOrgUnits")
	}

	var r0 []coreentity.OrgUnit
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.OrgUnitListFilter) ([]coreentity.OrgUnit, int, error)); ok {
		return returnFunc(ctx, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.OrgUnitListFilter) []coreentity.OrgUnit); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]coreentity.OrgUnit)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, coreentity.OrgUnitListFilter) int); ok {
		r1 = returnFunc(ctx, filter)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, coreentity.OrgUnitListFilter) error); ok {
		r2 = returnFunc(ctx, filter)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MasterRepository_GetOrgUnits_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrgUnits'
type MasterRepository_GetOrgUnits_Call struct {
	*mock.Call
}

// GetOrgUnits is a helper method to define mock.On call
//   - ctx context.Context
//   - filter coreentity.OrgUnitListFilter
func (_e *MasterRepository_Expecter) GetOrgUnits(ctx interface{}, filter interface{}) *MasterRepository_GetOrgUnits_Call {
	return &MasterRepository_GetOrgUnits_Call{Call: _e.mock.On("GetOrgUnits", ctx, filter)}
}

func (_c *MasterRepository_GetOrgUnits_Call) Run(run func(ctx context.Context, filter coreentity.OrgUnitListFilter)) *MasterRepository_GetOrgUnits_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 coreentity.OrgUnitListFilter
		if args[1] != nil {
			arg1 = args[1].(coreentity.OrgUnitListFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MasterRepository_GetOrgUnits_Call) Return(orgUnits []coreentity.OrgUnit, n int, err error) *MasterRepository_GetOrgUnits_Call {
	_c.Call.Return(orgUnits, n, err)
	return _c
}

func (_c *MasterRepository_GetOrgUnits_Call) RunAndReturn(run func(ctx context.Context, filter coreentity.OrgUnitListFilter) ([]coreentity.OrgUnit, int, error)) *MasterRepository_GetOrgUnits_Call {
	_c.Call.Return(run)
	return _c
}

// GetWorkLocation provides a mock function for the type MasterRepository
func (_mock *MasterRepository) GetWorkLocation(ctx context.Context, filter coreentity.WorkLocation) (*coreentity.WorkLocation, error) {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetWorkLocation")
	}

	var r0 *coreentity.WorkLocation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.WorkLocation) (*coreentity.WorkLocation, error)); ok {
		return returnFunc(ctx, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.WorkLocation) *coreentity.WorkLocation); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*coreentity.WorkLocation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, coreentity.WorkLocation) error); ok {
		r1 = returnFunc(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MasterRepository_GetWorkLocation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWorkLocation'
type MasterRepository_GetWorkLocation_Call struct {
	*mock.Call
}

// GetWorkLocation is a helper method to define mock.On call
//   - ctx context.Context
//   - filter coreentity.WorkLocation
func (_e *MasterRepository_Expecter) GetWorkLocation(ctx interface{}, filter interface{}) *MasterRepository_GetWorkLocation_Call {
	return &MasterRepository_GetWorkLocation_Call{Call: _e.mock.On("GetWorkLocation", ctx, filter)}
}

func (_c *MasterRepository_GetWorkLocation_Call) Run(run func(ctx context.Context, filter coreentity.WorkLocation)) *MasterRepository_GetWorkLocation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 coreentity.WorkLocation
		if args[1] != nil {
			arg1 = args[1].(coreentity.WorkLocation)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MasterRepository_GetWorkLocation_Call) Return(workLocation *coreentity.WorkLocation, err error) *MasterRepository_GetWorkLocation_Call {
	_c.Call.Return(workLocation, err)
	return _c
}

func (_c *MasterRepository_GetWorkLocation_Call) RunAndReturn(run func(ctx context.Context, filter coreentity.WorkLocation) (*coreentity.WorkLocation, error)) *MasterRepository_GetWorkLocation_Call {
	_c.Call.Return(run)
	return _c
}

// GetWorkLocations provides a mock function for the type MasterRepository
func (_mock *MasterRepository) GetWorkLocations(ctx context.Context, filter coreentity.WorkLocationListFilter) ([]coreentity.WorkLocation, int, error) {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetWorkLocations")
	}

	var r0 []coreentity.WorkLocation
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.WorkLocationListFilter) ([]coreentity.WorkLocation, int, error)); ok {
		return returnFunc(ctx, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.WorkLocationListFilter) []coreentity.WorkLocation); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]coreentity.WorkLocation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, coreentity.WorkLocationListFilter) int); ok {
		r1 = returnFunc(ctx, filter)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, coreentity.WorkLocationListFilter) error); ok {
		r2 = returnFunc(ctx, filter)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MasterRepository_GetWorkLocations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWorkLocations'
type MasterRepository_GetWorkLocations_Call struct {
	*mock.Call
}

// GetWorkLocations is a helper method to define mock.On call
//   - ctx context.Context
//   - filter coreentity.WorkLocationListFilter
func (_e *MasterRepository_Expecter) GetWorkLocations(ctx interface{}, filter interface{}) *MasterRepository_GetWorkLocations_Call {
	return &MasterRepository_GetWorkLocations_Call{Call: _e.mock.On("GetWorkLocations", ctx, filter)}
}

func (_c *MasterRepository_GetWorkLocations_Call) Run(run func(ctx context.Context, filter coreentity.WorkLocationListFilter)) *MasterRepository_GetWorkLocations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 coreentity.WorkLocationListFilter
		if args[1] != nil {
			arg1 = args[1].(coreentity.WorkLocationListFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MasterRepository_GetWorkLocations_Call) Return(workLocations []coreentity.WorkLocation, n int, err error) *MasterRepository_GetWorkLocations_Call {
	_c.Call.Return(workLocations, n, err)
	return _c
}

func (_c *MasterRepository_GetWorkLocations_Call) RunAndReturn(run func(ctx context.Context, filter coreentity.WorkLocationListFilter) ([]coreentity.WorkLocation, int, error)) *MasterRepository_GetWorkLocations_Call {
	_c.Call.Return(run)
	return _c
}

// GetWorkShift provides a mock function for the type MasterRepository
func (_mock *MasterRepository) GetWorkShift(ctx context.Context, filter coreentity.WorkShift) (*coreentity.WorkShift, error) {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetWorkShift")
	}

	var r0 *coreentity.WorkShift
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.WorkShift) (*coreentity.WorkShift, error)); ok {
		return returnFunc(ctx, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.WorkShift) *coreentity.WorkShift); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*coreentity.WorkShift)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, coreentity.WorkShift) error); ok {
		r1 = returnFunc(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MasterRepository_GetWorkShift_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWorkShift'
type MasterRepository_GetWorkShift_Call struct {
	*mock.Call
}

// GetWorkShift is a helper method to define mock.On call
//   - ctx context.Context
//   - filter coreentity.WorkShift
func (_e *MasterRepository_Expecter) GetWorkShift(ctx interface{}, filter interface{}) *MasterRepository_GetWorkShift_Call {
	return &MasterRepository_GetWorkShift_Call{Call: _e.mock.On("GetWorkShift", ctx, filter)}
}

func (_c *MasterRepository_GetWorkShift_Call) Run(run func(ctx context.Context, filter coreentity.WorkShift)) *MasterRepository_GetWorkShift_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 coreentity.WorkShift
		if args[1] != nil {
			arg1 = args[1].(coreentity.WorkShift)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MasterRepository_GetWorkShift_Call) Return(workShift *coreentity.WorkShift, err error) *MasterRepository_GetWorkShift_Call {
	_c.Call.Return(workShift, err)
	return _c
}

func (_c *MasterRepository_GetWorkShift_Call) RunAndReturn(run func(ctx context.Context, filter coreentity.WorkShift) (*coreentity.WorkShift, error)) *MasterRepository_GetWorkShift_Call {
	_c.Call.Return(run)
	return _c
}

// GetWorkShifts provides a mock function for the type MasterRepository
func (_mock *MasterRepository) GetWorkShifts(ctx context.Context, filter coreentity.WorkShiftListFilter) ([]coreentity.WorkShift, int, error) {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetWorkShifts")
	}

	var r0 []coreentity.WorkShift
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.WorkShiftListFilter) ([]coreentity.WorkShift, int, error)); ok {
		return returnFunc(ctx, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.WorkShiftListFilter) []coreentity.WorkShift); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]coreentity.WorkShift)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, coreentity.WorkShiftListFilter) int); ok {
		r1 = returnFunc(ctx, filter)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, coreentity.WorkShiftListFilter) error); ok {
		r2 = returnFunc(ctx, filter)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MasterRepository_GetWorkShifts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWorkShifts'
type MasterRepository_GetWorkShifts_Call struct {
	*mock.Call
}

// GetWorkShifts is a helper method to define mock.On call
//   - ctx context.Context
//   - filter coreentity.WorkShiftListFilter
func (_e *MasterRepository_Expecter) GetWorkShifts(ctx interface{}, filter interface{}) *MasterRepository_GetWorkShifts_Call {
	return &MasterRepository_GetWorkShifts_Call{Call: _e.mock.On("GetWorkShifts", ctx, filter)}
}

func (_c *MasterRepository_GetWorkShifts_Call) Run(run func(ctx context.Context, filter coreentity.WorkShiftListFilter)) *MasterRepository_GetWorkShifts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 coreentity.WorkShiftListFilter
		if args[1] != nil {
			arg1 = args[1].(coreentity.WorkShiftListFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MasterRepository_GetWorkShifts_Call) Return(workShifts []coreentity.WorkShift, n int, err error) *MasterRepository_GetWorkShifts_Call {
	_c.Call.Return(workShifts, n, err)
	return _c
}

func (_c *MasterRepository_GetWorkShifts_Call) RunAndReturn(run func(ctx context.Context, filter coreentity.WorkShiftListFilter) ([]coreentity.WorkShift, int, error)) *MasterRepository_GetWorkShifts_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateEmployee provides a mock function for the type MasterRepository
func (_mock *MasterRepository) UpdateEmployee(ctx context.Context, data coreentity.Employee) error {
	ret := _mock.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for UpdateEmployee")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.Employee) error); ok {
		r0 = returnFunc(ctx, data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MasterRepository_UpdateEmployee_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateEmployee'
type MasterRepository_UpdateEmployee_Call struct {
	*mock.Call
}

// UpdateEmployee is a helper method to define mock.On call
//   - ctx context.Context
//   - data coreentity.Employee
func (_e *MasterRepository_Expecter) UpdateEmployee(ctx interface{}, data interface{}) *MasterRepository_UpdateEmployee_Call {
	return &MasterRepository_UpdateEmployee_Call{Call: _e.mock.On("UpdateEmployee", ctx, data)}
}

func (_c *MasterRepository_UpdateEmployee_Call) Run(run func(ctx context.Context, data coreentity.Employee)) *MasterRepository_UpdateEmployee_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 coreentity.Employee
		if args[1] != nil {
			arg1 = args[1].(coreentity.Employee)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MasterRepository_UpdateEmployee_Call) Return(err error) *MasterRepository_UpdateEmployee_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MasterRepository_UpdateEmployee_Call) RunAndReturn(run func(ctx context.Context, data coreentity.Employee) error) *MasterRepository_UpdateEmployee_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateJobPosition provides a mock function for the type MasterRepository
func (_mock *MasterRepository) UpdateJobPosition(ctx context.Context, data coreentity.JobPosition) error {
	ret := _mock.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for UpdateJobPosition")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.JobPosition) error); ok {
		r0 = returnFunc(ctx, data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MasterRepository_UpdateJobPosition_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateJobPosition'
type MasterRepository_UpdateJobPosition_Call struct {
	*mock.Call
}

// UpdateJobPosition is a helper method to define mock.On call
//   - ctx context.Context
//   - data coreentity.JobPosition
func (_e *MasterRepository_Expecter) UpdateJobPosition(ctx interface{}, data interface{}) *MasterRepository_UpdateJobPosition_Call {
	return &MasterRepository_UpdateJobPosition_Call{Call: _e.mock.On("UpdateJobPosition", ctx, data)}
}

func (_c *MasterRepository_UpdateJobPosition_Call) Run(run func(ctx context.Context, data coreentity.JobPosition)) *MasterRepository_UpdateJobPosition_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 coreentity.JobPosition
		if args[1] != nil {
			arg1 = args[1].(coreentity.JobPosition)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MasterRepository_UpdateJobPosition_Call) Return(err error) *MasterRepository_UpdateJobPosition_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MasterRepository_UpdateJobPosition_Call) RunAndReturn(run func(ctx context.Context, data coreentity.JobPosition) error) *MasterRepository_UpdateJobPosition_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateOrgUnit provides a mock function for the type MasterRepository
func (_mock *MasterRepository) UpdateOrgUnit(ctx context.Context, data coreentity.OrgUnit) error {
	ret := _mock.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for UpdateOrgUnit")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.OrgUnit) error); ok {
		r0 = returnFunc(ctx, data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MasterRepository_UpdateOrgUnit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateOrgUnit'
type MasterRepository_UpdateOrgUnit_Call struct {
	*mock.Call
}

// UpdateOrgUnit is a helper method to define mock.On call
//   - ctx context.Context
//   - data coreentity.OrgUnit
func (_e *MasterRepository_Expecter) UpdateOrgUnit(ctx interface{}, data interface{}) *MasterRepository_UpdateOrgUnit_Call {
	return &MasterRepository_UpdateOrgUnit_Call{Call: _e.mock.On("UpdateOrgUnit", ctx, data)}
}

func (_c *MasterRepository_UpdateOrgUnit_Call) Run(run func(ctx context.Context, data coreentity.OrgUnit)) *MasterRepository_UpdateOrgUnit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 coreentity.OrgUnit
		if args[1] != nil {
			arg1 = args[1].(coreentity.OrgUnit)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MasterRepository_UpdateOrgUnit_Call) Return(err error) *MasterRepository_UpdateOrgUnit_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MasterRepository_UpdateOrgUnit_Call) RunAndReturn(run func(ctx context.Context, data coreentity.OrgUnit) error) *MasterRepository_UpdateOrgUnit_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateWorkLocation provides a mock function for the type MasterRepository
func (_mock *MasterRepository) UpdateWorkLocation(ctx context.Context, data coreentity.WorkLocation) error {
	ret := _mock.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for UpdateWorkLocation")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.WorkLocation) error); ok {
		r0 = returnFunc(ctx, data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MasterRepository_UpdateWorkLocation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateWorkLocation'
type MasterRepository_UpdateWorkLocation_Call struct {
	*mock.Call
}

// UpdateWorkLocation is a helper method to define mock.On call
//   - ctx context.Context
//   - data coreentity.WorkLocation
func (_e *MasterRepository_Expecter) UpdateWorkLocation(ctx interface{}, data interface{}) *MasterRepository_UpdateWorkLocation_Call {
	return &MasterRepository_UpdateWorkLocation_Call{Call: _e.mock.On("UpdateWorkLocation", ctx, data)}
}

func (_c *MasterRepository_UpdateWorkLocation_Call) Run(run func(ctx context.Context, data coreentity.WorkLocation)) *MasterRepository_UpdateWorkLocation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 coreentity.WorkLocation
		if args[1] != nil {
			arg1 = args[1].(coreentity.WorkLocation)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MasterRepository_UpdateWorkLocation_Call) Return(err error) *MasterRepository_UpdateWorkLocation_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MasterRepository_UpdateWorkLocation_Call) RunAndReturn(run func(ctx context.Context, data coreentity.WorkLocation) error) *MasterRepository_UpdateWorkLocation_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateWorkShift provides a mock function for the type MasterRepository
func (_mock *MasterRepository) UpdateWorkShift(ctx context.Context, data coreentity.WorkShift) error {
	ret := _mock.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for UpdateWorkShift")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.WorkShift) error); ok {
		r0 = returnFunc(ctx, data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MasterRepository_UpdateWorkShift_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateWorkShift'
type MasterRepository_UpdateWorkShift_Call struct {
	*mock.Call
}

// UpdateWorkShift is a helper method to define mock.On call
//   - ctx context.Context
//   - data coreentity.WorkShift
func (_e *MasterRepository_Expecter) UpdateWorkShift(ctx interface{}, data interface{}) *MasterRepository_UpdateWorkShift_Call {
	return &MasterRepository_UpdateWorkShift_Call{Call: _e.mock.On("UpdateWorkShift", ctx, data)}
}

func (_c *MasterRepository_UpdateWorkShift_Call) Run(run func(ctx context.Context, data coreentity.WorkShift)) *MasterRepository_UpdateWorkShift_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 coreentity.WorkShift
		if args[1] != nil {
			arg1 = args[1].(coreentity.WorkShift)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MasterRepository_UpdateWorkShift_Call) Return(err error) *MasterRepository_UpdateWorkShift_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MasterRepository_UpdateWorkShift_Call) RunAndReturn(run func(ctx context.Context, data coreentity.WorkShift) error) *MasterRepository_UpdateWorkShift_Call {
	_c.Call.Return(run)
	return _c
}
