// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"codebase-app/internal/entity/coreentity"
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMeRepository creates a new instance of MeRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMeRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MeRepository {
	mock := &MeRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MeRepository is an autogenerated mock type for the MeRepository type
type MeRepository struct {
	mock.Mock
}

type MeRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MeRepository) EXPECT() *MeRepository_Expecter {
	return &MeRepository_Expecter{mock: &_m.Mock}
}

// GetEmployeeByUserID provides a mock function for the type MeRepository
func (_mock *MeRepository) GetEmployeeByUserID(ctx context.Context, tenantID string, userID string) (*coreentity.Employee, error) {
	ret := _mock.Called(ctx, tenantID, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetEmployeeByUserID")
	}

	var r0 *coreentity.Employee
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*coreentity.Employee, error)); ok {
		return returnFunc(ctx, tenantID, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *coreentity.Employee); ok {
		r0 = returnFunc(ctx, tenantID, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*coreentity.Employee)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, tenantID, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MeRepository_GetEmployeeByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEmployeeByUserID'
type MeRepository_GetEmployeeByUserID_Call struct {
	*mock.Call
}

// GetEmployeeByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID string
//   - userID string
func (_e *MeRepository_Expecter) GetEmployeeByUserID(ctx interface{}, tenantID interface{}, userID interface{}) *MeRepository_GetEmployeeByUserID_Call {
	return &MeRepository_GetEmployeeByUserID_Call{Call: _e.mock.On("GetEmployeeByUserID", ctx, tenantID, userID)}
}

func (_c *MeRepository_GetEmployeeByUserID_Call) Run(run func(ctx context.Context, tenantID string, userID string)) *MeRepository_GetEmployeeByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MeRepository_GetEmployeeByUserID_Call) Return(employee *coreentity.Employee, err error) *MeRepository_GetEmployeeByUserID_Call {
	_c.Call.Return(employee, err)
	return _c
}

func (_c *MeRepository_GetEmployeeByUserID_Call) RunAndReturn(run func(ctx context.Context, tenantID string, userID string) (*coreentity.Employee, error)) *MeRepository_GetEmployeeByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// GetWorkShiftByUserID provides a mock function for the type MeRepository
func (_mock *MeRepository) GetWorkShiftByUserID(ctx context.Context, tenantID string, userID string) (*coreentity.WorkShift, error) {
	ret := _mock.Called(ctx, tenantID, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetWorkShiftByUserID")
	}

	var r0 *coreentity.WorkShift
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*coreentity.WorkShift, error)); ok {
		return returnFunc(ctx, tenantID, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *coreentity.WorkShift); ok {
		r0 = returnFunc(ctx, tenantID, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*coreentity.WorkShift)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, tenantID, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MeRepository_GetWorkShiftByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWorkShiftByUserID'
type MeRepository_GetWorkShiftByUserID_Call struct {
	*mock.Call
}

// GetWorkShiftByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID string
//   - userID string
func (_e *MeRepository_Expecter) GetWorkShiftByUserID(ctx interface{}, tenantID interface{}, userID interface{}) *MeRepository_GetWorkShiftByUserID_Call {
	return &MeRepository_GetWorkShiftByUserID_Call{Call: _e.mock.On("GetWorkShiftByUserID", ctx, tenantID, userID)}
}

func (_c *MeRepository_GetWorkShiftByUserID_Call) Run(run func(ctx context.Context, tenantID string, userID string)) *MeRepository_GetWorkShiftByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MeRepository_GetWorkShiftByUserID_Call) Return(workShift *coreentity.WorkShift, err error) *MeRepository_GetWorkShiftByUserID_Call {
	_c.Call.Return(workShift, err)
	return _c
}

func (_c *MeRepository_GetWorkShiftByUserID_Call) RunAndReturn(run func(ctx context.Context, tenantID string, userID string) (*coreentity.WorkShift, error)) *MeRepository_GetWorkShiftByUserID_Call {
	_c.Call.Return(run)
	return _c
}
