// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"codebase-app/internal/entity/coreentity"
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMessageQueueRepository creates a new instance of MessageQueueRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMessageQueueRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MessageQueueRepository {
	mock := &MessageQueueRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MessageQueueRepository is an autogenerated mock type for the MessageQueueRepository type
type MessageQueueRepository struct {
	mock.Mock
}

type MessageQueueRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MessageQueueRepository) EXPECT() *MessageQueueRepository_Expecter {
	return &MessageQueueRepository_Expecter{mock: &_m.Mock}
}

// CleanupProcessedMessages provides a mock function for the type MessageQueueRepository
func (_mock *MessageQueueRepository) CleanupProcessedMessages(ctx context.Context, req coreentity.CleanupProcessedMessageQueueReq) (*coreentity.CleanupProcessedMessageQueueResp, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CleanupProcessedMessages")
	}

	var r0 *coreentity.CleanupProcessedMessageQueueResp
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.CleanupProcessedMessageQueueReq) (*coreentity.CleanupProcessedMessageQueueResp, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.CleanupProcessedMessageQueueReq) *coreentity.CleanupProcessedMessageQueueResp); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*coreentity.CleanupProcessedMessageQueueResp)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, coreentity.CleanupProcessedMessageQueueReq) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MessageQueueRepository_CleanupProcessedMessages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CleanupProcessedMessages'
type MessageQueueRepository_CleanupProcessedMessages_Call struct {
	*mock.Call
}

// CleanupProcessedMessages is a helper method to define mock.On call
//   - ctx context.Context
//   - req coreentity.CleanupProcessedMessageQueueReq
func (_e *MessageQueueRepository_Expecter) CleanupProcessedMessages(ctx interface{}, req interface{}) *MessageQueueRepository_CleanupProcessedMessages_Call {
	return &MessageQueueRepository_CleanupProcessedMessages_Call{Call: _e.mock.On("CleanupProcessedMessages", ctx, req)}
}

func (_c *MessageQueueRepository_CleanupProcessedMessages_Call) Run(run func(ctx context.Context, req coreentity.CleanupProcessedMessageQueueReq)) *MessageQueueRepository_CleanupProcessedMessages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 coreentity.CleanupProcessedMessageQueueReq
		if args[1] != nil {
			arg1 = args[1].(coreentity.CleanupProcessedMessageQueueReq)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MessageQueueRepository_CleanupProcessedMessages_Call) Return(cleanupProcessedMessageQueueResp *coreentity.CleanupProcessedMessageQueueResp, err error) *MessageQueueRepository_CleanupProcessedMessages_Call {
	_c.Call.Return(cleanupProcessedMessageQueueResp, err)
	return _c
}

func (_c *MessageQueueRepository_CleanupProcessedMessages_Call) RunAndReturn(run func(ctx context.Context, req coreentity.CleanupProcessedMessageQueueReq) (*coreentity.CleanupProcessedMessageQueueResp, error)) *MessageQueueRepository_CleanupProcessedMessages_Call {
	_c.Call.Return(run)
	return _c
}
