// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"codebase-app/internal/entity/coreentity"
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewRbacRepository creates a new instance of RbacRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRbacRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *RbacRepository {
	mock := &RbacRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// RbacRepository is an autogenerated mock type for the RbacRepository type
type RbacRepository struct {
	mock.Mock
}

type RbacRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *RbacRepository) EXPECT() *RbacRepository_Expecter {
	return &RbacRepository_Expecter{mock: &_m.Mock}
}

// AssignPermission provides a mock function for the type RbacRepository
func (_mock *RbacRepository) AssignPermission(ctx context.Context, userID string, permissionID string) error {
	ret := _mock.Called(ctx, userID, permissionID)

	if len(ret) == 0 {
		panic("no return value specified for AssignPermission")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, userID, permissionID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// RbacRepository_AssignPermission_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AssignPermission'
type RbacRepository_AssignPermission_Call struct {
	*mock.Call
}

// AssignPermission is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - permissionID string
func (_e *RbacRepository_Expecter) AssignPermission(ctx interface{}, userID interface{}, permissionID interface{}) *RbacRepository_AssignPermission_Call {
	return &RbacRepository_AssignPermission_Call{Call: _e.mock.On("AssignPermission", ctx, userID, permissionID)}
}

func (_c *RbacRepository_AssignPermission_Call) Run(run func(ctx context.Context, userID string, permissionID string)) *RbacRepository_AssignPermission_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *RbacRepository_AssignPermission_Call) Return(err error) *RbacRepository_AssignPermission_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *RbacRepository_AssignPermission_Call) RunAndReturn(run func(ctx context.Context, userID string, permissionID string) error) *RbacRepository_AssignPermission_Call {
	_c.Call.Return(run)
	return _c
}

// AssignRole provides a mock function for the type RbacRepository
func (_mock *RbacRepository) AssignRole(ctx context.Context, data coreentity.UserRole) error {
	ret := _mock.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for AssignRole")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.UserRole) error); ok {
		r0 = returnFunc(ctx, data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// RbacRepository_AssignRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AssignRole'
type RbacRepository_AssignRole_Call struct {
	*mock.Call
}

// AssignRole is a helper method to define mock.On call
//   - ctx context.Context
//   - data coreentity.UserRole
func (_e *RbacRepository_Expecter) AssignRole(ctx interface{}, data interface{}) *RbacRepository_AssignRole_Call {
	return &RbacRepository_AssignRole_Call{Call: _e.mock.On("AssignRole", ctx, data)}
}

func (_c *RbacRepository_AssignRole_Call) Run(run func(ctx context.Context, data coreentity.UserRole)) *RbacRepository_AssignRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 coreentity.UserRole
		if args[1] != nil {
			arg1 = args[1].(coreentity.UserRole)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *RbacRepository_AssignRole_Call) Return(err error) *RbacRepository_AssignRole_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *RbacRepository_AssignRole_Call) RunAndReturn(run func(ctx context.Context, data coreentity.UserRole) error) *RbacRepository_AssignRole_Call {
	_c.Call.Return(run)
	return _c
}

// CreateRole provides a mock function for the type RbacRepository
func (_mock *RbacRepository) CreateRole(ctx context.Context, data coreentity.Role) (*coreentity.Role, error) {
	ret := _mock.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for CreateRole")
	}

	var r0 *coreentity.Role
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.Role) (*coreentity.Role, error)); ok {
		return returnFunc(ctx, data)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.Role) *coreentity.Role); ok {
		r0 = returnFunc(ctx, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*coreentity.Role)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, coreentity.Role) error); ok {
		r1 = returnFunc(ctx, data)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RbacRepository_CreateRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRole'
type RbacRepository_CreateRole_Call struct {
	*mock.Call
}

// CreateRole is a helper method to define mock.On call
//   - ctx context.Context
//   - data coreentity.Role
func (_e *RbacRepository_Expecter) CreateRole(ctx interface{}, data interface{}) *RbacRepository_CreateRole_Call {
	return &RbacRepository_CreateRole_Call{Call: _e.mock.On("CreateRole", ctx, data)}
}

func (_c *RbacRepository_CreateRole_Call) Run(run func(ctx context.Context, data coreentity.Role)) *RbacRepository_CreateRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 coreentity.Role
		if args[1] != nil {
			arg1 = args[1].(coreentity.Role)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *RbacRepository_CreateRole_Call) Return(role *coreentity.Role, err error) *RbacRepository_CreateRole_Call {
	_c.Call.Return(role, err)
	return _c
}

func (_c *RbacRepository_CreateRole_Call) RunAndReturn(run func(ctx context.Context, data coreentity.Role) (*coreentity.Role, error)) *RbacRepository_CreateRole_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteRole provides a mock function for the type RbacRepository
func (_mock *RbacRepository) DeleteRole(ctx context.Context, filter coreentity.RoleDeleteFilter) error {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for DeleteRole")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.RoleDeleteFilter) error); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// RbacRepository_DeleteRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteRole'
type RbacRepository_DeleteRole_Call struct {
	*mock.Call
}

// DeleteRole is a helper method to define mock.On call
//   - ctx context.Context
//   - filter coreentity.RoleDeleteFilter
func (_e *RbacRepository_Expecter) DeleteRole(ctx interface{}, filter interface{}) *RbacRepository_DeleteRole_Call {
	return &RbacRepository_DeleteRole_Call{Call: _e.mock.On("DeleteRole", ctx, filter)}
}

func (_c *RbacRepository_DeleteRole_Call) Run(run func(ctx context.Context, filter coreentity.RoleDeleteFilter)) *RbacRepository_DeleteRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 coreentity.RoleDeleteFilter
		if args[1] != nil {
			arg1 = args[1].(coreentity.RoleDeleteFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *RbacRepository_DeleteRole_Call) Return(err error) *RbacRepository_DeleteRole_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *RbacRepository_DeleteRole_Call) RunAndReturn(run func(ctx context.Context, filter coreentity.RoleDeleteFilter) error) *RbacRepository_DeleteRole_Call {
	_c.Call.Return(run)
	return _c
}

// GetPermissions provides a mock function for the type RbacRepository
func (_mock *RbacRepository) GetPermissions(ctx context.Context, filter coreentity.PermissionListFilter) ([]coreentity.Permission, int, error) {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetPermissions")
	}

	var r0 []coreentity.Permission
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.PermissionListFilter) ([]coreentity.Permission, int, error)); ok {
		return returnFunc(ctx, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.PermissionListFilter) []coreentity.Permission); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]coreentity.Permission)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, coreentity.PermissionListFilter) int); ok {
		r1 = returnFunc(ctx, filter)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, coreentity.PermissionListFilter) error); ok {
		r2 = returnFunc(ctx, filter)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// RbacRepository_GetPermissions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPermissions'
type RbacRepository_GetPermissions_Call struct {
	*mock.Call
}

// GetPermissions is a helper method to define mock.On call
//   - ctx context.Context
//   - filter coreentity.PermissionListFilter
func (_e *RbacRepository_Expecter) GetPermissions(ctx interface{}, filter interface{}) *RbacRepository_GetPermissions_Call {
	return &RbacRepository_GetPermissions_Call{Call: _e.mock.On("GetPermissions", ctx, filter)}
}

func (_c *RbacRepository_GetPermissions_Call) Run(run func(ctx context.Context, filter coreentity.PermissionListFilter)) *RbacRepository_GetPermissions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 coreentity.PermissionListFilter
		if args[1] != nil {
			arg1 = args[1].(coreentity.PermissionListFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *RbacRepository_GetPermissions_Call) Return(permissions []coreentity.Permission, n int, err error) *RbacRepository_GetPermissions_Call {
	_c.Call.Return(permissions, n, err)
	return _c
}

func (_c *RbacRepository_GetPermissions_Call) RunAndReturn(run func(ctx context.Context, filter coreentity.PermissionListFilter) ([]coreentity.Permission, int, error)) *RbacRepository_GetPermissions_Call {
	_c.Call.Return(run)
	return _c
}

// GetPermissionsByRoleID provides a mock function for the type RbacRepository
func (_mock *RbacRepository) GetPermissionsByRoleID(ctx context.Context, roleID string) ([]coreentity.Permission, error) {
	ret := _mock.Called(ctx, roleID)

	if len(ret) == 0 {
		panic("no return value specified for GetPermissionsByRoleID")
	}

	var r0 []coreentity.Permission
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]coreentity.Permission, error)); ok {
		return returnFunc(ctx, roleID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []coreentity.Permission); ok {
		r0 = returnFunc(ctx, roleID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]coreentity.Permission)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, roleID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RbacRepository_GetPermissionsByRoleID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPermissionsByRoleID'
type RbacRepository_GetPermissionsByRoleID_Call struct {
	*mock.Call
}

// GetPermissionsByRoleID is a helper method to define mock.On call
//   - ctx context.Context
//   - roleID string
func (_e *RbacRepository_Expecter) GetPermissionsByRoleID(ctx interface{}, roleID interface{}) *RbacRepository_GetPermissionsByRoleID_Call {
	return &RbacRepository_GetPermissionsByRoleID_Call{Call: _e.mock.On("GetPermissionsByRoleID", ctx, roleID)}
}

func (_c *RbacRepository_GetPermissionsByRoleID_Call) Run(run func(ctx context.Context, roleID string)) *RbacRepository_GetPermissionsByRoleID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *RbacRepository_GetPermissionsByRoleID_Call) Return(permissions []coreentity.Permission, err error) *RbacRepository_GetPermissionsByRoleID_Call {
	_c.Call.Return(permissions, err)
	return _c
}

func (_c *RbacRepository_GetPermissionsByRoleID_Call) RunAndReturn(run func(ctx context.Context, roleID string) ([]coreentity.Permission, error)) *RbacRepository_GetPermissionsByRoleID_Call {
	_c.Call.Return(run)
	return _c
}

// GetRoleByName provides a mock function for the type RbacRepository
func (_mock *RbacRepository) GetRoleByName(ctx context.Context, name string, tenantID string) (*coreentity.Role, error) {
	ret := _mock.Called(ctx, name, tenantID)

	if len(ret) == 0 {
		panic("no return value specified for GetRoleByName")
	}

	var r0 *coreentity.Role
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*coreentity.Role, error)); ok {
		return returnFunc(ctx, name, tenantID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *coreentity.Role); ok {
		r0 = returnFunc(ctx, name, tenantID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*coreentity.Role)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, name, tenantID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RbacRepository_GetRoleByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRoleByName'
type RbacRepository_GetRoleByName_Call struct {
	*mock.Call
}

// GetRoleByName is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - tenantID string
func (_e *RbacRepository_Expecter) GetRoleByName(ctx interface{}, name interface{}, tenantID interface{}) *RbacRepository_GetRoleByName_Call {
	return &RbacRepository_GetRoleByName_Call{Call: _e.mock.On("GetRoleByName", ctx, name, tenantID)}
}

func (_c *RbacRepository_GetRoleByName_Call) Run(run func(ctx context.Context, name string, tenantID string)) *RbacRepository_GetRoleByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *RbacRepository_GetRoleByName_Call) Return(role *coreentity.Role, err error) *RbacRepository_GetRoleByName_Call {
	_c.Call.Return(role, err)
	return _c
}

func (_c *RbacRepository_GetRoleByName_Call) RunAndReturn(run func(ctx context.Context, name string, tenantID string) (*coreentity.Role, error)) *RbacRepository_GetRoleByName_Call {
	_c.Call.Return(run)
	return _c
}

// GetRoleWithPermissions provides a mock function for the type RbacRepository
func (_mock *RbacRepository) GetRoleWithPermissions(ctx context.Context, roleID string, tenantID string) (*coreentity.Role, error) {
	ret := _mock.Called(ctx, roleID, tenantID)

	if len(ret) == 0 {
		panic("no return value specified for GetRoleWithPermissions")
	}

	var r0 *coreentity.Role
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*coreentity.Role, error)); ok {
		return returnFunc(ctx, roleID, tenantID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *coreentity.Role); ok {
		r0 = returnFunc(ctx, roleID, tenantID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*coreentity.Role)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, roleID, tenantID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RbacRepository_GetRoleWithPermissions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRoleWithPermissions'
type RbacRepository_GetRoleWithPermissions_Call struct {
	*mock.Call
}

// GetRoleWithPermissions is a helper method to define mock.On call
//   - ctx context.Context
//   - roleID string
//   - tenantID string
func (_e *RbacRepository_Expecter) GetRoleWithPermissions(ctx interface{}, roleID interface{}, tenantID interface{}) *RbacRepository_GetRoleWithPermissions_Call {
	return &RbacRepository_GetRoleWithPermissions_Call{Call: _e.mock.On("GetRoleWithPermissions", ctx, roleID, tenantID)}
}

func (_c *RbacRepository_GetRoleWithPermissions_Call) Run(run func(ctx context.Context, roleID string, tenantID string)) *RbacRepository_GetRoleWithPermissions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *RbacRepository_GetRoleWithPermissions_Call) Return(role *coreentity.Role, err error) *RbacRepository_GetRoleWithPermissions_Call {
	_c.Call.Return(role, err)
	return _c
}

func (_c *RbacRepository_GetRoleWithPermissions_Call) RunAndReturn(run func(ctx context.Context, roleID string, tenantID string) (*coreentity.Role, error)) *RbacRepository_GetRoleWithPermissions_Call {
	_c.Call.Return(run)
	return _c
}

// GetRoles provides a mock function for the type RbacRepository
func (_mock *RbacRepository) GetRoles(ctx context.Context, filter coreentity.RoleListFilter) ([]coreentity.Role, int, error) {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetRoles")
	}

	var r0 []coreentity.Role
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.RoleListFilter) ([]coreentity.Role, int, error)); ok {
		return returnFunc(ctx, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.RoleListFilter) []coreentity.Role); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]coreentity.Role)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, coreentity.RoleListFilter) int); ok {
		r1 = returnFunc(ctx, filter)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, coreentity.RoleListFilter) error); ok {
		r2 = returnFunc(ctx, filter)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// RbacRepository_GetRoles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRoles'
type RbacRepository_GetRoles_Call struct {
	*mock.Call
}

// GetRoles is a helper method to define mock.On call
//   - ctx context.Context
//   - filter coreentity.RoleListFilter
func (_e *RbacRepository_Expecter) GetRoles(ctx interface{}, filter interface{}) *RbacRepository_GetRoles_Call {
	return &RbacRepository_GetRoles_Call{Call: _e.mock.On("GetRoles", ctx, filter)}
}

func (_c *RbacRepository_GetRoles_Call) Run(run func(ctx context.Context, filter coreentity.RoleListFilter)) *RbacRepository_GetRoles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 coreentity.RoleListFilter
		if args[1] != nil {
			arg1 = args[1].(coreentity.RoleListFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *RbacRepository_GetRoles_Call) Return(roles []coreentity.Role, n int, err error) *RbacRepository_GetRoles_Call {
	_c.Call.Return(roles, n, err)
	return _c
}

func (_c *RbacRepository_GetRoles_Call) RunAndReturn(run func(ctx context.Context, filter coreentity.RoleListFilter) ([]coreentity.Role, int, error)) *RbacRepository_GetRoles_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserPermissions provides a mock function for the type RbacRepository
func (_mock *RbacRepository) GetUserPermissions(ctx context.Context, userID string) ([]coreentity.Permission, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserPermissions")
	}

	var r0 []coreentity.Permission
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]coreentity.Permission, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []coreentity.Permission); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]coreentity.Permission)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RbacRepository_GetUserPermissions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserPermissions'
type RbacRepository_GetUserPermissions_Call struct {
	*mock.Call
}

// GetUserPermissions is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *RbacRepository_Expecter) GetUserPermissions(ctx interface{}, userID interface{}) *RbacRepository_GetUserPermissions_Call {
	return &RbacRepository_GetUserPermissions_Call{Call: _e.mock.On("GetUserPermissions", ctx, userID)}
}

func (_c *RbacRepository_GetUserPermissions_Call) Run(run func(ctx context.Context, userID string)) *RbacRepository_GetUserPermissions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *RbacRepository_GetUserPermissions_Call) Return(permissions []coreentity.Permission, err error) *RbacRepository_GetUserPermissions_Call {
	_c.Call.Return(permissions, err)
	return _c
}

func (_c *RbacRepository_GetUserPermissions_Call) RunAndReturn(run func(ctx context.Context, userID string) ([]coreentity.Permission, error)) *RbacRepository_GetUserPermissions_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserRoles provides a mock function for the type RbacRepository
func (_mock *RbacRepository) GetUserRoles(ctx context.Context, filter coreentity.UserRoleFilter) ([]coreentity.Role, error) {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetUserRoles")
	}

	var r0 []coreentity.Role
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.UserRoleFilter) ([]coreentity.Role, error)); ok {
		return returnFunc(ctx, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.UserRoleFilter) []coreentity.Role); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]coreentity.Role)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, coreentity.UserRoleFilter) error); ok {
		r1 = returnFunc(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RbacRepository_GetUserRoles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserRoles'
type RbacRepository_GetUserRoles_Call struct {
	*mock.Call
}

// GetUserRoles is a helper method to define mock.On call
//   - ctx context.Context
//   - filter coreentity.UserRoleFilter
func (_e *RbacRepository_Expecter) GetUserRoles(ctx interface{}, filter interface{}) *RbacRepository_GetUserRoles_Call {
	return &RbacRepository_GetUserRoles_Call{Call: _e.mock.On("GetUserRoles", ctx, filter)}
}

func (_c *RbacRepository_GetUserRoles_Call) Run(run func(ctx context.Context, filter coreentity.UserRoleFilter)) *RbacRepository_GetUserRoles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 coreentity.UserRoleFilter
		if args[1] != nil {
			arg1 = args[1].(coreentity.UserRoleFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *RbacRepository_GetUserRoles_Call) Return(roles []coreentity.Role, err error) *RbacRepository_GetUserRoles_Call {
	_c.Call.Return(roles, err)
	return _c
}

func (_c *RbacRepository_GetUserRoles_Call) RunAndReturn(run func(ctx context.Context, filter coreentity.UserRoleFilter) ([]coreentity.Role, error)) *RbacRepository_GetUserRoles_Call {
	_c.Call.Return(run)
	return _c
}

// HasPermission provides a mock function for the type RbacRepository
func (_mock *RbacRepository) HasPermission(ctx context.Context, userID string, permission string) (bool, error) {
	ret := _mock.Called(ctx, userID, permission)

	if len(ret) == 0 {
		panic("no return value specified for HasPermission")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (bool, error)); ok {
		return returnFunc(ctx, userID, permission)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = returnFunc(ctx, userID, permission)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, userID, permission)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RbacRepository_HasPermission_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasPermission'
type RbacRepository_HasPermission_Call struct {
	*mock.Call
}

// HasPermission is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - permission string
func (_e *RbacRepository_Expecter) HasPermission(ctx interface{}, userID interface{}, permission interface{}) *RbacRepository_HasPermission_Call {
	return &RbacRepository_HasPermission_Call{Call: _e.mock.On("HasPermission", ctx, userID, permission)}
}

func (_c *RbacRepository_HasPermission_Call) Run(run func(ctx context.Context, userID string, permission string)) *RbacRepository_HasPermission_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *RbacRepository_HasPermission_Call) Return(b bool, err error) *RbacRepository_HasPermission_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *RbacRepository_HasPermission_Call) RunAndReturn(run func(ctx context.Context, userID string, permission string) (bool, error)) *RbacRepository_HasPermission_Call {
	_c.Call.Return(run)
	return _c
}

// RemovePermission provides a mock function for the type RbacRepository
func (_mock *RbacRepository) RemovePermission(ctx context.Context, userID string, permissionID string) error {
	ret := _mock.Called(ctx, userID, permissionID)

	if len(ret) == 0 {
		panic("no return value specified for RemovePermission")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, userID, permissionID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// RbacRepository_RemovePermission_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemovePermission'
type RbacRepository_RemovePermission_Call struct {
	*mock.Call
}

// RemovePermission is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - permissionID string
func (_e *RbacRepository_Expecter) RemovePermission(ctx interface{}, userID interface{}, permissionID interface{}) *RbacRepository_RemovePermission_Call {
	return &RbacRepository_RemovePermission_Call{Call: _e.mock.On("RemovePermission", ctx, userID, permissionID)}
}

func (_c *RbacRepository_RemovePermission_Call) Run(run func(ctx context.Context, userID string, permissionID string)) *RbacRepository_RemovePermission_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *RbacRepository_RemovePermission_Call) Return(err error) *RbacRepository_RemovePermission_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *RbacRepository_RemovePermission_Call) RunAndReturn(run func(ctx context.Context, userID string, permissionID string) error) *RbacRepository_RemovePermission_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveRole provides a mock function for the type RbacRepository
func (_mock *RbacRepository) RemoveRole(ctx context.Context, data coreentity.UserRole) error {
	ret := _mock.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for RemoveRole")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.UserRole) error); ok {
		r0 = returnFunc(ctx, data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// RbacRepository_RemoveRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveRole'
type RbacRepository_RemoveRole_Call struct {
	*mock.Call
}

// RemoveRole is a helper method to define mock.On call
//   - ctx context.Context
//   - data coreentity.UserRole
func (_e *RbacRepository_Expecter) RemoveRole(ctx interface{}, data interface{}) *RbacRepository_RemoveRole_Call {
	return &RbacRepository_RemoveRole_Call{Call: _e.mock.On("RemoveRole", ctx, data)}
}

func (_c *RbacRepository_RemoveRole_Call) Run(run func(ctx context.Context, data coreentity.UserRole)) *RbacRepository_RemoveRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 coreentity.UserRole
		if args[1] != nil {
			arg1 = args[1].(coreentity.UserRole)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *RbacRepository_RemoveRole_Call) Return(err error) *RbacRepository_RemoveRole_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *RbacRepository_RemoveRole_Call) RunAndReturn(run func(ctx context.Context, data coreentity.UserRole) error) *RbacRepository_RemoveRole_Call {
	_c.Call.Return(run)
	return _c
}

// SetRolePermissions provides a mock function for the type RbacRepository
func (_mock *RbacRepository) SetRolePermissions(ctx context.Context, roleID string, tenantID string, permissionIDs []string) error {
	ret := _mock.Called(ctx, roleID, tenantID, permissionIDs)

	if len(ret) == 0 {
		panic("no return value specified for SetRolePermissions")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, []string) error); ok {
		r0 = returnFunc(ctx, roleID, tenantID, permissionIDs)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// RbacRepository_SetRolePermissions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetRolePermissions'
type RbacRepository_SetRolePermissions_Call struct {
	*mock.Call
}

// SetRolePermissions is a helper method to define mock.On call
//   - ctx context.Context
//   - roleID string
//   - tenantID string
//   - permissionIDs []string
func (_e *RbacRepository_Expecter) SetRolePermissions(ctx interface{}, roleID interface{}, tenantID interface{}, permissionIDs interface{}) *RbacRepository_SetRolePermissions_Call {
	return &RbacRepository_SetRolePermissions_Call{Call: _e.mock.On("SetRolePermissions", ctx, roleID, tenantID, permissionIDs)}
}

func (_c *RbacRepository_SetRolePermissions_Call) Run(run func(ctx context.Context, roleID string, tenantID string, permissionIDs []string)) *RbacRepository_SetRolePermissions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []string
		if args[3] != nil {
			arg3 = args[3].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *RbacRepository_SetRolePermissions_Call) Return(err error) *RbacRepository_SetRolePermissions_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *RbacRepository_SetRolePermissions_Call) RunAndReturn(run func(ctx context.Context, roleID string, tenantID string, permissionIDs []string) error) *RbacRepository_SetRolePermissions_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateRole provides a mock function for the type RbacRepository
func (_mock *RbacRepository) UpdateRole(ctx context.Context, roleID string, tenantID string, permissionIDs []string) error {
	ret := _mock.Called(ctx, roleID, tenantID, permissionIDs)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRole")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, []string) error); ok {
		r0 = returnFunc(ctx, roleID, tenantID, permissionIDs)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// RbacRepository_UpdateRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateRole'
type RbacRepository_UpdateRole_Call struct {
	*mock.Call
}

// UpdateRole is a helper method to define mock.On call
//   - ctx context.Context
//   - roleID string
//   - tenantID string
//   - permissionIDs []string
func (_e *RbacRepository_Expecter) UpdateRole(ctx interface{}, roleID interface{}, tenantID interface{}, permissionIDs interface{}) *RbacRepository_UpdateRole_Call {
	return &RbacRepository_UpdateRole_Call{Call: _e.mock.On("UpdateRole", ctx, roleID, tenantID, permissionIDs)}
}

func (_c *RbacRepository_UpdateRole_Call) Run(run func(ctx context.Context, roleID string, tenantID string, permissionIDs []string)) *RbacRepository_UpdateRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []string
		if args[3] != nil {
			arg3 = args[3].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *RbacRepository_UpdateRole_Call) Return(err error) *RbacRepository_UpdateRole_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *RbacRepository_UpdateRole_Call) RunAndReturn(run func(ctx context.Context, roleID string, tenantID string, permissionIDs []string) error) *RbacRepository_UpdateRole_Call {
	_c.Call.Return(run)
	return _c
}
