// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"codebase-app/internal/entity/coreentity"
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewStorageRepository creates a new instance of StorageRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStorageRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *StorageRepository {
	mock := &StorageRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// StorageRepository is an autogenerated mock type for the StorageRepository type
type StorageRepository struct {
	mock.Mock
}

type StorageRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *StorageRepository) EXPECT() *StorageRepository_Expecter {
	return &StorageRepository_Expecter{mock: &_m.Mock}
}

// CreateFile provides a mock function for the type StorageRepository
func (_mock *StorageRepository) CreateFile(ctx context.Context, data coreentity.File) (*coreentity.File, error) {
	ret := _mock.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for CreateFile")
	}

	var r0 *coreentity.File
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.File) (*coreentity.File, error)); ok {
		return returnFunc(ctx, data)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.File) *coreentity.File); ok {
		r0 = returnFunc(ctx, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*coreentity.File)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, coreentity.File) error); ok {
		r1 = returnFunc(ctx, data)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// StorageRepository_CreateFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateFile'
type StorageRepository_CreateFile_Call struct {
	*mock.Call
}

// CreateFile is a helper method to define mock.On call
//   - ctx context.Context
//   - data coreentity.File
func (_e *StorageRepository_Expecter) CreateFile(ctx interface{}, data interface{}) *StorageRepository_CreateFile_Call {
	return &StorageRepository_CreateFile_Call{Call: _e.mock.On("CreateFile", ctx, data)}
}

func (_c *StorageRepository_CreateFile_Call) Run(run func(ctx context.Context, data coreentity.File)) *StorageRepository_CreateFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 coreentity.File
		if args[1] != nil {
			arg1 = args[1].(coreentity.File)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *StorageRepository_CreateFile_Call) Return(file *coreentity.File, err error) *StorageRepository_CreateFile_Call {
	_c.Call.Return(file, err)
	return _c
}

func (_c *StorageRepository_CreateFile_Call) RunAndReturn(run func(ctx context.Context, data coreentity.File) (*coreentity.File, error)) *StorageRepository_CreateFile_Call {
	_c.Call.Return(run)
	return _c
}

// CreateFileLink provides a mock function for the type StorageRepository
func (_mock *StorageRepository) CreateFileLink(ctx context.Context, req coreentity.CreateStorageFileLinkReq) (*coreentity.StorageFileLink, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateFileLink")
	}

	var r0 *coreentity.StorageFileLink
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.CreateStorageFileLinkReq) (*coreentity.StorageFileLink, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.CreateStorageFileLinkReq) *coreentity.StorageFileLink); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*coreentity.StorageFileLink)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, coreentity.CreateStorageFileLinkReq) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// StorageRepository_CreateFileLink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateFileLink'
type StorageRepository_CreateFileLink_Call struct {
	*mock.Call
}

// CreateFileLink is a helper method to define mock.On call
//   - ctx context.Context
//   - req coreentity.CreateStorageFileLinkReq
func (_e *StorageRepository_Expecter) CreateFileLink(ctx interface{}, req interface{}) *StorageRepository_CreateFileLink_Call {
	return &StorageRepository_CreateFileLink_Call{Call: _e.mock.On("CreateFileLink", ctx, req)}
}

func (_c *StorageRepository_CreateFileLink_Call) Run(run func(ctx context.Context, req coreentity.CreateStorageFileLinkReq)) *StorageRepository_CreateFileLink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 coreentity.CreateStorageFileLinkReq
		if args[1] != nil {
			arg1 = args[1].(coreentity.CreateStorageFileLinkReq)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *StorageRepository_CreateFileLink_Call) Return(storageFileLink *coreentity.StorageFileLink, err error) *StorageRepository_CreateFileLink_Call {
	_c.Call.Return(storageFileLink, err)
	return _c
}

func (_c *StorageRepository_CreateFileLink_Call) RunAndReturn(run func(ctx context.Context, req coreentity.CreateStorageFileLinkReq) (*coreentity.StorageFileLink, error)) *StorageRepository_CreateFileLink_Call {
	_c.Call.Return(run)
	return _c
}

// GetExpiredPendingFiles provides a mock function for the type StorageRepository
func (_mock *StorageRepository) GetExpiredPendingFiles(ctx context.Context, filter coreentity.ExpiredPendingFileFilter) ([]coreentity.File, error) {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetExpiredPendingFiles")
	}

	var r0 []coreentity.File
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.ExpiredPendingFileFilter) ([]coreentity.File, error)); ok {
		return returnFunc(ctx, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.ExpiredPendingFileFilter) []coreentity.File); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]coreentity.File)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, coreentity.ExpiredPendingFileFilter) error); ok {
		r1 = returnFunc(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// StorageRepository_GetExpiredPendingFiles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetExpiredPendingFiles'
type StorageRepository_GetExpiredPendingFiles_Call struct {
	*mock.Call
}

// GetExpiredPendingFiles is a helper method to define mock.On call
//   - ctx context.Context
//   - filter coreentity.ExpiredPendingFileFilter
func (_e *StorageRepository_Expecter) GetExpiredPendingFiles(ctx interface{}, filter interface{}) *StorageRepository_GetExpiredPendingFiles_Call {
	return &StorageRepository_GetExpiredPendingFiles_Call{Call: _e.mock.On("GetExpiredPendingFiles", ctx, filter)}
}

func (_c *StorageRepository_GetExpiredPendingFiles_Call) Run(run func(ctx context.Context, filter coreentity.ExpiredPendingFileFilter)) *StorageRepository_GetExpiredPendingFiles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 coreentity.ExpiredPendingFileFilter
		if args[1] != nil {
			arg1 = args[1].(coreentity.ExpiredPendingFileFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *StorageRepository_GetExpiredPendingFiles_Call) Return(files []coreentity.File, err error) *StorageRepository_GetExpiredPendingFiles_Call {
	_c.Call.Return(files, err)
	return _c
}

func (_c *StorageRepository_GetExpiredPendingFiles_Call) RunAndReturn(run func(ctx context.Context, filter coreentity.ExpiredPendingFileFilter) ([]coreentity.File, error)) *StorageRepository_GetExpiredPendingFiles_Call {
	_c.Call.Return(run)
	return _c
}

// GetFile provides a mock function for the type StorageRepository
func (_mock *StorageRepository) GetFile(ctx context.Context, filter coreentity.FileFilter) (*coreentity.File, error) {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetFile")
	}

	var r0 *coreentity.File
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.FileFilter) (*coreentity.File, error)); ok {
		return returnFunc(ctx, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.FileFilter) *coreentity.File); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*coreentity.File)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, coreentity.FileFilter) error); ok {
		r1 = returnFunc(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// StorageRepository_GetFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFile'
type StorageRepository_GetFile_Call struct {
	*mock.Call
}

// GetFile is a helper method to define mock.On call
//   - ctx context.Context
//   - filter coreentity.FileFilter
func (_e *StorageRepository_Expecter) GetFile(ctx interface{}, filter interface{}) *StorageRepository_GetFile_Call {
	return &StorageRepository_GetFile_Call{Call: _e.mock.On("GetFile", ctx, filter)}
}

func (_c *StorageRepository_GetFile_Call) Run(run func(ctx context.Context, filter coreentity.FileFilter)) *StorageRepository_GetFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 coreentity.FileFilter
		if args[1] != nil {
			arg1 = args[1].(coreentity.FileFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *StorageRepository_GetFile_Call) Return(file *coreentity.File, err error) *StorageRepository_GetFile_Call {
	_c.Call.Return(file, err)
	return _c
}

func (_c *StorageRepository_GetFile_Call) RunAndReturn(run func(ctx context.Context, filter coreentity.FileFilter) (*coreentity.File, error)) *StorageRepository_GetFile_Call {
	_c.Call.Return(run)
	return _c
}

// GetFileLink provides a mock function for the type StorageRepository
func (_mock *StorageRepository) GetFileLink(ctx context.Context, filter coreentity.StorageFileLinkFilter) (*coreentity.StorageFileLink, error) {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetFileLink")
	}

	var r0 *coreentity.StorageFileLink
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.StorageFileLinkFilter) (*coreentity.StorageFileLink, error)); ok {
		return returnFunc(ctx, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.StorageFileLinkFilter) *coreentity.StorageFileLink); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*coreentity.StorageFileLink)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, coreentity.StorageFileLinkFilter) error); ok {
		r1 = returnFunc(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// StorageRepository_GetFileLink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFileLink'
type StorageRepository_GetFileLink_Call struct {
	*mock.Call
}

// GetFileLink is a helper method to define mock.On call
//   - ctx context.Context
//   - filter coreentity.StorageFileLinkFilter
func (_e *StorageRepository_Expecter) GetFileLink(ctx interface{}, filter interface{}) *StorageRepository_GetFileLink_Call {
	return &StorageRepository_GetFileLink_Call{Call: _e.mock.On("GetFileLink", ctx, filter)}
}

func (_c *StorageRepository_GetFileLink_Call) Run(run func(ctx context.Context, filter coreentity.StorageFileLinkFilter)) *StorageRepository_GetFileLink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 coreentity.StorageFileLinkFilter
		if args[1] != nil {
			arg1 = args[1].(coreentity.StorageFileLinkFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *StorageRepository_GetFileLink_Call) Return(storageFileLink *coreentity.StorageFileLink, err error) *StorageRepository_GetFileLink_Call {
	_c.Call.Return(storageFileLink, err)
	return _c
}

func (_c *StorageRepository_GetFileLink_Call) RunAndReturn(run func(ctx context.Context, filter coreentity.StorageFileLinkFilter) (*coreentity.StorageFileLink, error)) *StorageRepository_GetFileLink_Call {
	_c.Call.Return(run)
	return _c
}

// MarkFileAttached provides a mock function for the type StorageRepository
func (_mock *StorageRepository) MarkFileAttached(ctx context.Context, tenantID string, id string) error {
	ret := _mock.Called(ctx, tenantID, id)

	if len(ret) == 0 {
		panic("no return value specified for MarkFileAttached")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, tenantID, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// StorageRepository_MarkFileAttached_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkFileAttached'
type StorageRepository_MarkFileAttached_Call struct {
	*mock.Call
}

// MarkFileAttached is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID string
//   - id string
func (_e *StorageRepository_Expecter) MarkFileAttached(ctx interface{}, tenantID interface{}, id interface{}) *StorageRepository_MarkFileAttached_Call {
	return &StorageRepository_MarkFileAttached_Call{Call: _e.mock.On("MarkFileAttached", ctx, tenantID, id)}
}

func (_c *StorageRepository_MarkFileAttached_Call) Run(run func(ctx context.Context, tenantID string, id string)) *StorageRepository_MarkFileAttached_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *StorageRepository_MarkFileAttached_Call) Return(err error) *StorageRepository_MarkFileAttached_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *StorageRepository_MarkFileAttached_Call) RunAndReturn(run func(ctx context.Context, tenantID string, id string) error) *StorageRepository_MarkFileAttached_Call {
	_c.Call.Return(run)
	return _c
}

// MarkFileDeleted provides a mock function for the type StorageRepository
func (_mock *StorageRepository) MarkFileDeleted(ctx context.Context, tenantID string, id string) error {
	ret := _mock.Called(ctx, tenantID, id)

	if len(ret) == 0 {
		panic("no return value specified for MarkFileDeleted")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, tenantID, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// StorageRepository_MarkFileDeleted_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkFileDeleted'
type StorageRepository_MarkFileDeleted_Call struct {
	*mock.Call
}

// MarkFileDeleted is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID string
//   - id string
func (_e *StorageRepository_Expecter) MarkFileDeleted(ctx interface{}, tenantID interface{}, id interface{}) *StorageRepository_MarkFileDeleted_Call {
	return &StorageRepository_MarkFileDeleted_Call{Call: _e.mock.On("MarkFileDeleted", ctx, tenantID, id)}
}

func (_c *StorageRepository_MarkFileDeleted_Call) Run(run func(ctx context.Context, tenantID string, id string)) *StorageRepository_MarkFileDeleted_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *StorageRepository_MarkFileDeleted_Call) Return(err error) *StorageRepository_MarkFileDeleted_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *StorageRepository_MarkFileDeleted_Call) RunAndReturn(run func(ctx context.Context, tenantID string, id string) error) *StorageRepository_MarkFileDeleted_Call {
	_c.Call.Return(run)
	return _c
}
