// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"codebase-app/internal/entity/coreentity"
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewUserInvitationRepository creates a new instance of UserInvitationRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserInvitationRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserInvitationRepository {
	mock := &UserInvitationRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// UserInvitationRepository is an autogenerated mock type for the UserInvitationRepository type
type UserInvitationRepository struct {
	mock.Mock
}

type UserInvitationRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *UserInvitationRepository) EXPECT() *UserInvitationRepository_Expecter {
	return &UserInvitationRepository_Expecter{mock: &_m.Mock}
}

// CreateInvitation provides a mock function for the type UserInvitationRepository
func (_mock *UserInvitationRepository) CreateInvitation(ctx context.Context, data coreentity.UserInvitation) (*coreentity.UserInvitation, error) {
	ret := _mock.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for CreateInvitation")
	}

	var r0 *coreentity.UserInvitation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.UserInvitation) (*coreentity.UserInvitation, error)); ok {
		return returnFunc(ctx, data)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.UserInvitation) *coreentity.UserInvitation); ok {
		r0 = returnFunc(ctx, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*coreentity.UserInvitation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, coreentity.UserInvitation) error); ok {
		r1 = returnFunc(ctx, data)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UserInvitationRepository_CreateInvitation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateInvitation'
type UserInvitationRepository_CreateInvitation_Call struct {
	*mock.Call
}

// CreateInvitation is a helper method to define mock.On call
//   - ctx context.Context
//   - data coreentity.UserInvitation
func (_e *UserInvitationRepository_Expecter) CreateInvitation(ctx interface{}, data interface{}) *UserInvitationRepository_CreateInvitation_Call {
	return &UserInvitationRepository_CreateInvitation_Call{Call: _e.mock.On("CreateInvitation", ctx, data)}
}

func (_c *UserInvitationRepository_CreateInvitation_Call) Run(run func(ctx context.Context, data coreentity.UserInvitation)) *UserInvitationRepository_CreateInvitation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 coreentity.UserInvitation
		if args[1] != nil {
			arg1 = args[1].(coreentity.UserInvitation)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserInvitationRepository_CreateInvitation_Call) Return(userInvitation *coreentity.UserInvitation, err error) *UserInvitationRepository_CreateInvitation_Call {
	_c.Call.Return(userInvitation, err)
	return _c
}

func (_c *UserInvitationRepository_CreateInvitation_Call) RunAndReturn(run func(ctx context.Context, data coreentity.UserInvitation) (*coreentity.UserInvitation, error)) *UserInvitationRepository_CreateInvitation_Call {
	_c.Call.Return(run)
	return _c
}

// ExistsActiveInvitation provides a mock function for the type UserInvitationRepository
func (_mock *UserInvitationRepository) ExistsActiveInvitation(ctx context.Context, tenantID string, email string, roleCode string, employeeID *string) (bool, error) {
	ret := _mock.Called(ctx, tenantID, email, roleCode, employeeID)

	if len(ret) == 0 {
		panic("no return value specified for ExistsActiveInvitation")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, *string) (bool, error)); ok {
		return returnFunc(ctx, tenantID, email, roleCode, employeeID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, *string) bool); ok {
		r0 = returnFunc(ctx, tenantID, email, roleCode, employeeID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string, *string) error); ok {
		r1 = returnFunc(ctx, tenantID, email, roleCode, employeeID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UserInvitationRepository_ExistsActiveInvitation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExistsActiveInvitation'
type UserInvitationRepository_ExistsActiveInvitation_Call struct {
	*mock.Call
}

// ExistsActiveInvitation is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID string
//   - email string
//   - roleCode string
//   - employeeID *string
func (_e *UserInvitationRepository_Expecter) ExistsActiveInvitation(ctx interface{}, tenantID interface{}, email interface{}, roleCode interface{}, employeeID interface{}) *UserInvitationRepository_ExistsActiveInvitation_Call {
	return &UserInvitationRepository_ExistsActiveInvitation_Call{Call: _e.mock.On("ExistsActiveInvitation", ctx, tenantID, email, roleCode, employeeID)}
}

func (_c *UserInvitationRepository_ExistsActiveInvitation_Call) Run(run func(ctx context.Context, tenantID string, email string, roleCode string, employeeID *string)) *UserInvitationRepository_ExistsActiveInvitation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 *string
		if args[4] != nil {
			arg4 = args[4].(*string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *UserInvitationRepository_ExistsActiveInvitation_Call) Return(b bool, err error) *UserInvitationRepository_ExistsActiveInvitation_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *UserInvitationRepository_ExistsActiveInvitation_Call) RunAndReturn(run func(ctx context.Context, tenantID string, email string, roleCode string, employeeID *string) (bool, error)) *UserInvitationRepository_ExistsActiveInvitation_Call {
	_c.Call.Return(run)
	return _c
}

// GetInvitationByID provides a mock function for the type UserInvitationRepository
func (_mock *UserInvitationRepository) GetInvitationByID(ctx context.Context, tenantID string, invitationID string) (*coreentity.UserInvitation, error) {
	ret := _mock.Called(ctx, tenantID, invitationID)

	if len(ret) == 0 {
		panic("no return value specified for GetInvitationByID")
	}

	var r0 *coreentity.UserInvitation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*coreentity.UserInvitation, error)); ok {
		return returnFunc(ctx, tenantID, invitationID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *coreentity.UserInvitation); ok {
		r0 = returnFunc(ctx, tenantID, invitationID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*coreentity.UserInvitation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, tenantID, invitationID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UserInvitationRepository_GetInvitationByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInvitationByID'
type UserInvitationRepository_GetInvitationByID_Call struct {
	*mock.Call
}

// GetInvitationByID is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID string
//   - invitationID string
func (_e *UserInvitationRepository_Expecter) GetInvitationByID(ctx interface{}, tenantID interface{}, invitationID interface{}) *UserInvitationRepository_GetInvitationByID_Call {
	return &UserInvitationRepository_GetInvitationByID_Call{Call: _e.mock.On("GetInvitationByID", ctx, tenantID, invitationID)}
}

func (_c *UserInvitationRepository_GetInvitationByID_Call) Run(run func(ctx context.Context, tenantID string, invitationID string)) *UserInvitationRepository_GetInvitationByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *UserInvitationRepository_GetInvitationByID_Call) Return(userInvitation *coreentity.UserInvitation, err error) *UserInvitationRepository_GetInvitationByID_Call {
	_c.Call.Return(userInvitation, err)
	return _c
}

func (_c *UserInvitationRepository_GetInvitationByID_Call) RunAndReturn(run func(ctx context.Context, tenantID string, invitationID string) (*coreentity.UserInvitation, error)) *UserInvitationRepository_GetInvitationByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetInvitationByTokenHash provides a mock function for the type UserInvitationRepository
func (_mock *UserInvitationRepository) GetInvitationByTokenHash(ctx context.Context, tokenHash string) (*coreentity.UserInvitation, error) {
	ret := _mock.Called(ctx, tokenHash)

	if len(ret) == 0 {
		panic("no return value specified for GetInvitationByTokenHash")
	}

	var r0 *coreentity.UserInvitation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*coreentity.UserInvitation, error)); ok {
		return returnFunc(ctx, tokenHash)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *coreentity.UserInvitation); ok {
		r0 = returnFunc(ctx, tokenHash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*coreentity.UserInvitation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, tokenHash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UserInvitationRepository_GetInvitationByTokenHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInvitationByTokenHash'
type UserInvitationRepository_GetInvitationByTokenHash_Call struct {
	*mock.Call
}

// GetInvitationByTokenHash is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenHash string
func (_e *UserInvitationRepository_Expecter) GetInvitationByTokenHash(ctx interface{}, tokenHash interface{}) *UserInvitationRepository_GetInvitationByTokenHash_Call {
	return &UserInvitationRepository_GetInvitationByTokenHash_Call{Call: _e.mock.On("GetInvitationByTokenHash", ctx, tokenHash)}
}

func (_c *UserInvitationRepository_GetInvitationByTokenHash_Call) Run(run func(ctx context.Context, tokenHash string)) *UserInvitationRepository_GetInvitationByTokenHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserInvitationRepository_GetInvitationByTokenHash_Call) Return(userInvitation *coreentity.UserInvitation, err error) *UserInvitationRepository_GetInvitationByTokenHash_Call {
	_c.Call.Return(userInvitation, err)
	return _c
}

func (_c *UserInvitationRepository_GetInvitationByTokenHash_Call) RunAndReturn(run func(ctx context.Context, tokenHash string) (*coreentity.UserInvitation, error)) *UserInvitationRepository_GetInvitationByTokenHash_Call {
	_c.Call.Return(run)
	return _c
}

// GetInvitations provides a mock function for the type UserInvitationRepository
func (_mock *UserInvitationRepository) GetInvitations(ctx context.Context, filter coreentity.UserInvitationListFilter) ([]coreentity.UserInvitation, int, error) {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetInvitations")
	}

	var r0 []coreentity.UserInvitation
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.UserInvitationListFilter) ([]coreentity.UserInvitation, int, error)); ok {
		return returnFunc(ctx, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.UserInvitationListFilter) []coreentity.UserInvitation); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]coreentity.UserInvitation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, coreentity.UserInvitationListFilter) int); ok {
		r1 = returnFunc(ctx, filter)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, coreentity.UserInvitationListFilter) error); ok {
		r2 = returnFunc(ctx, filter)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// UserInvitationRepository_GetInvitations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInvitations'
type UserInvitationRepository_GetInvitations_Call struct {
	*mock.Call
}

// GetInvitations is a helper method to define mock.On call
//   - ctx context.Context
//   - filter coreentity.UserInvitationListFilter
func (_e *UserInvitationRepository_Expecter) GetInvitations(ctx interface{}, filter interface{}) *UserInvitationRepository_GetInvitations_Call {
	return &UserInvitationRepository_GetInvitations_Call{Call: _e.mock.On("GetInvitations", ctx, filter)}
}

func (_c *UserInvitationRepository_GetInvitations_Call) Run(run func(ctx context.Context, filter coreentity.UserInvitationListFilter)) *UserInvitationRepository_GetInvitations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 coreentity.UserInvitationListFilter
		if args[1] != nil {
			arg1 = args[1].(coreentity.UserInvitationListFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserInvitationRepository_GetInvitations_Call) Return(userInvitations []coreentity.UserInvitation, n int, err error) *UserInvitationRepository_GetInvitations_Call {
	_c.Call.Return(userInvitations, n, err)
	return _c
}

func (_c *UserInvitationRepository_GetInvitations_Call) RunAndReturn(run func(ctx context.Context, filter coreentity.UserInvitationListFilter) ([]coreentity.UserInvitation, int, error)) *UserInvitationRepository_GetInvitations_Call {
	_c.Call.Return(run)
	return _c
}

// MarkInvitationAccepted provides a mock function for the type UserInvitationRepository
func (_mock *UserInvitationRepository) MarkInvitationAccepted(ctx context.Context, invitationID string) error {
	ret := _mock.Called(ctx, invitationID)

	if len(ret) == 0 {
		panic("no return value specified for MarkInvitationAccepted")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, invitationID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// UserInvitationRepository_MarkInvitationAccepted_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkInvitationAccepted'
type UserInvitationRepository_MarkInvitationAccepted_Call struct {
	*mock.Call
}

// MarkInvitationAccepted is a helper method to define mock.On call
//   - ctx context.Context
//   - invitationID string
func (_e *UserInvitationRepository_Expecter) MarkInvitationAccepted(ctx interface{}, invitationID interface{}) *UserInvitationRepository_MarkInvitationAccepted_Call {
	return &UserInvitationRepository_MarkInvitationAccepted_Call{Call: _e.mock.On("MarkInvitationAccepted", ctx, invitationID)}
}

func (_c *UserInvitationRepository_MarkInvitationAccepted_Call) Run(run func(ctx context.Context, invitationID string)) *UserInvitationRepository_MarkInvitationAccepted_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserInvitationRepository_MarkInvitationAccepted_Call) Return(err error) *UserInvitationRepository_MarkInvitationAccepted_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *UserInvitationRepository_MarkInvitationAccepted_Call) RunAndReturn(run func(ctx context.Context, invitationID string) error) *UserInvitationRepository_MarkInvitationAccepted_Call {
	_c.Call.Return(run)
	return _c
}

// ResendInvitation provides a mock function for the type UserInvitationRepository
func (_mock *UserInvitationRepository) ResendInvitation(ctx context.Context, data coreentity.UserInvitation) error {
	ret := _mock.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for ResendInvitation")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.UserInvitation) error); ok {
		r0 = returnFunc(ctx, data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// UserInvitationRepository_ResendInvitation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResendInvitation'
type UserInvitationRepository_ResendInvitation_Call struct {
	*mock.Call
}

// ResendInvitation is a helper method to define mock.On call
//   - ctx context.Context
//   - data coreentity.UserInvitation
func (_e *UserInvitationRepository_Expecter) ResendInvitation(ctx interface{}, data interface{}) *UserInvitationRepository_ResendInvitation_Call {
	return &UserInvitationRepository_ResendInvitation_Call{Call: _e.mock.On("ResendInvitation", ctx, data)}
}

func (_c *UserInvitationRepository_ResendInvitation_Call) Run(run func(ctx context.Context, data coreentity.UserInvitation)) *UserInvitationRepository_ResendInvitation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 coreentity.UserInvitation
		if args[1] != nil {
			arg1 = args[1].(coreentity.UserInvitation)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserInvitationRepository_ResendInvitation_Call) Return(err error) *UserInvitationRepository_ResendInvitation_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *UserInvitationRepository_ResendInvitation_Call) RunAndReturn(run func(ctx context.Context, data coreentity.UserInvitation) error) *UserInvitationRepository_ResendInvitation_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeInvitation provides a mock function for the type UserInvitationRepository
func (_mock *UserInvitationRepository) RevokeInvitation(ctx context.Context, tenantID string, invitationID string) error {
	ret := _mock.Called(ctx, tenantID, invitationID)

	if len(ret) == 0 {
		panic("no return value specified for RevokeInvitation")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, tenantID, invitationID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// UserInvitationRepository_RevokeInvitation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeInvitation'
type UserInvitationRepository_RevokeInvitation_Call struct {
	*mock.Call
}

// RevokeInvitation is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID string
//   - invitationID string
func (_e *UserInvitationRepository_Expecter) RevokeInvitation(ctx interface{}, tenantID interface{}, invitationID interface{}) *UserInvitationRepository_RevokeInvitation_Call {
	return &UserInvitationRepository_RevokeInvitation_Call{Call: _e.mock.On("RevokeInvitation", ctx, tenantID, invitationID)}
}

func (_c *UserInvitationRepository_RevokeInvitation_Call) Run(run func(ctx context.Context, tenantID string, invitationID string)) *UserInvitationRepository_RevokeInvitation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *UserInvitationRepository_RevokeInvitation_Call) Return(err error) *UserInvitationRepository_RevokeInvitation_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *UserInvitationRepository_RevokeInvitation_Call) RunAndReturn(run func(ctx context.Context, tenantID string, invitationID string) error) *UserInvitationRepository_RevokeInvitation_Call {
	_c.Call.Return(run)
	return _c
}
