// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"codebase-app/internal/entity/coreentity"
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewUserRepository creates a new instance of UserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserRepository {
	mock := &UserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// UserRepository is an autogenerated mock type for the UserRepository type
type UserRepository struct {
	mock.Mock
}

type UserRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *UserRepository) EXPECT() *UserRepository_Expecter {
	return &UserRepository_Expecter{mock: &_m.Mock}
}

// CreateUser provides a mock function for the type UserRepository
func (_mock *UserRepository) CreateUser(ctx context.Context, data coreentity.User) (*coreentity.User, error) {
	ret := _mock.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 *coreentity.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.User) (*coreentity.User, error)); ok {
		return returnFunc(ctx, data)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.User) *coreentity.User); ok {
		r0 = returnFunc(ctx, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*coreentity.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, coreentity.User) error); ok {
		r1 = returnFunc(ctx, data)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UserRepository_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type UserRepository_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - data coreentity.User
func (_e *UserRepository_Expecter) CreateUser(ctx interface{}, data interface{}) *UserRepository_CreateUser_Call {
	return &UserRepository_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, data)}
}

func (_c *UserRepository_CreateUser_Call) Run(run func(ctx context.Context, data coreentity.User)) *UserRepository_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 coreentity.User
		if args[1] != nil {
			arg1 = args[1].(coreentity.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserRepository_CreateUser_Call) Return(user *coreentity.User, err error) *UserRepository_CreateUser_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *UserRepository_CreateUser_Call) RunAndReturn(run func(ctx context.Context, data coreentity.User) (*coreentity.User, error)) *UserRepository_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// CreateUserActionToken provides a mock function for the type UserRepository
func (_mock *UserRepository) CreateUserActionToken(ctx context.Context, token coreentity.UserActionToken) error {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for CreateUserActionToken")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.UserActionToken) error); ok {
		r0 = returnFunc(ctx, token)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// UserRepository_CreateUserActionToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUserActionToken'
type UserRepository_CreateUserActionToken_Call struct {
	*mock.Call
}

// CreateUserActionToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token coreentity.UserActionToken
func (_e *UserRepository_Expecter) CreateUserActionToken(ctx interface{}, token interface{}) *UserRepository_CreateUserActionToken_Call {
	return &UserRepository_CreateUserActionToken_Call{Call: _e.mock.On("CreateUserActionToken", ctx, token)}
}

func (_c *UserRepository_CreateUserActionToken_Call) Run(run func(ctx context.Context, token coreentity.UserActionToken)) *UserRepository_CreateUserActionToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 coreentity.UserActionToken
		if args[1] != nil {
			arg1 = args[1].(coreentity.UserActionToken)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserRepository_CreateUserActionToken_Call) Return(err error) *UserRepository_CreateUserActionToken_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *UserRepository_CreateUserActionToken_Call) RunAndReturn(run func(ctx context.Context, token coreentity.UserActionToken) error) *UserRepository_CreateUserActionToken_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteUser provides a mock function for the type UserRepository
func (_mock *UserRepository) DeleteUser(ctx context.Context, filter coreentity.UserDeleteFilter) error {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.UserDeleteFilter) error); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// UserRepository_DeleteUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUser'
type UserRepository_DeleteUser_Call struct {
	*mock.Call
}

// DeleteUser is a helper method to define mock.On call
//   - ctx context.Context
//   - filter coreentity.UserDeleteFilter
func (_e *UserRepository_Expecter) DeleteUser(ctx interface{}, filter interface{}) *UserRepository_DeleteUser_Call {
	return &UserRepository_DeleteUser_Call{Call: _e.mock.On("DeleteUser", ctx, filter)}
}

func (_c *UserRepository_DeleteUser_Call) Run(run func(ctx context.Context, filter coreentity.UserDeleteFilter)) *UserRepository_DeleteUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 coreentity.UserDeleteFilter
		if args[1] != nil {
			arg1 = args[1].(coreentity.UserDeleteFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserRepository_DeleteUser_Call) Return(err error) *UserRepository_DeleteUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *UserRepository_DeleteUser_Call) RunAndReturn(run func(ctx context.Context, filter coreentity.UserDeleteFilter) error) *UserRepository_DeleteUser_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteUserActionTokensByPurpose provides a mock function for the type UserRepository
func (_mock *UserRepository) DeleteUserActionTokensByPurpose(ctx context.Context, userID string, purpose string) error {
	ret := _mock.Called(ctx, userID, purpose)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUserActionTokensByPurpose")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, userID, purpose)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// UserRepository_DeleteUserActionTokensByPurpose_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUserActionTokensByPurpose'
type UserRepository_DeleteUserActionTokensByPurpose_Call struct {
	*mock.Call
}

// DeleteUserActionTokensByPurpose is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - purpose string
func (_e *UserRepository_Expecter) DeleteUserActionTokensByPurpose(ctx interface{}, userID interface{}, purpose interface{}) *UserRepository_DeleteUserActionTokensByPurpose_Call {
	return &UserRepository_DeleteUserActionTokensByPurpose_Call{Call: _e.mock.On("DeleteUserActionTokensByPurpose", ctx, userID, purpose)}
}

func (_c *UserRepository_DeleteUserActionTokensByPurpose_Call) Run(run func(ctx context.Context, userID string, purpose string)) *UserRepository_DeleteUserActionTokensByPurpose_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *UserRepository_DeleteUserActionTokensByPurpose_Call) Return(err error) *UserRepository_DeleteUserActionTokensByPurpose_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *UserRepository_DeleteUserActionTokensByPurpose_Call) RunAndReturn(run func(ctx context.Context, userID string, purpose string) error) *UserRepository_DeleteUserActionTokensByPurpose_Call {
	_c.Call.Return(run)
	return _c
}

// ExistsActiveUserByEmailAndTenant provides a mock function for the type UserRepository
func (_mock *UserRepository) ExistsActiveUserByEmailAndTenant(ctx context.Context, email string, tenantID string) (bool, error) {
	ret := _mock.Called(ctx, email, tenantID)

	if len(ret) == 0 {
		panic("no return value specified for ExistsActiveUserByEmailAndTenant")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (bool, error)); ok {
		return returnFunc(ctx, email, tenantID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = returnFunc(ctx, email, tenantID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, email, tenantID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UserRepository_ExistsActiveUserByEmailAndTenant_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExistsActiveUserByEmailAndTenant'
type UserRepository_ExistsActiveUserByEmailAndTenant_Call struct {
	*mock.Call
}

// ExistsActiveUserByEmailAndTenant is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - tenantID string
func (_e *UserRepository_Expecter) ExistsActiveUserByEmailAndTenant(ctx interface{}, email interface{}, tenantID interface{}) *UserRepository_ExistsActiveUserByEmailAndTenant_Call {
	return &UserRepository_ExistsActiveUserByEmailAndTenant_Call{Call: _e.mock.On("ExistsActiveUserByEmailAndTenant", ctx, email, tenantID)}
}

func (_c *UserRepository_ExistsActiveUserByEmailAndTenant_Call) Run(run func(ctx context.Context, email string, tenantID string)) *UserRepository_ExistsActiveUserByEmailAndTenant_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *UserRepository_ExistsActiveUserByEmailAndTenant_Call) Return(b bool, err error) *UserRepository_ExistsActiveUserByEmailAndTenant_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *UserRepository_ExistsActiveUserByEmailAndTenant_Call) RunAndReturn(run func(ctx context.Context, email string, tenantID string) (bool, error)) *UserRepository_ExistsActiveUserByEmailAndTenant_Call {
	_c.Call.Return(run)
	return _c
}

// ExistsActiveUserByEmailAndTenantExcludeUser provides a mock function for the type UserRepository
func (_mock *UserRepository) ExistsActiveUserByEmailAndTenantExcludeUser(ctx context.Context, email string, tenantID string, excludeUserID string) (bool, error) {
	ret := _mock.Called(ctx, email, tenantID, excludeUserID)

	if len(ret) == 0 {
		panic("no return value specified for ExistsActiveUserByEmailAndTenantExcludeUser")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) (bool, error)); ok {
		return returnFunc(ctx, email, tenantID, excludeUserID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) bool); ok {
		r0 = returnFunc(ctx, email, tenantID, excludeUserID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = returnFunc(ctx, email, tenantID, excludeUserID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UserRepository_ExistsActiveUserByEmailAndTenantExcludeUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExistsActiveUserByEmailAndTenantExcludeUser'
type UserRepository_ExistsActiveUserByEmailAndTenantExcludeUser_Call struct {
	*mock.Call
}

// ExistsActiveUserByEmailAndTenantExcludeUser is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - tenantID string
//   - excludeUserID string
func (_e *UserRepository_Expecter) ExistsActiveUserByEmailAndTenantExcludeUser(ctx interface{}, email interface{}, tenantID interface{}, excludeUserID interface{}) *UserRepository_ExistsActiveUserByEmailAndTenantExcludeUser_Call {
	return &UserRepository_ExistsActiveUserByEmailAndTenantExcludeUser_Call{Call: _e.mock.On("ExistsActiveUserByEmailAndTenantExcludeUser", ctx, email, tenantID, excludeUserID)}
}

func (_c *UserRepository_ExistsActiveUserByEmailAndTenantExcludeUser_Call) Run(run func(ctx context.Context, email string, tenantID string, excludeUserID string)) *UserRepository_ExistsActiveUserByEmailAndTenantExcludeUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *UserRepository_ExistsActiveUserByEmailAndTenantExcludeUser_Call) Return(b bool, err error) *UserRepository_ExistsActiveUserByEmailAndTenantExcludeUser_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *UserRepository_ExistsActiveUserByEmailAndTenantExcludeUser_Call) RunAndReturn(run func(ctx context.Context, email string, tenantID string, excludeUserID string) (bool, error)) *UserRepository_ExistsActiveUserByEmailAndTenantExcludeUser_Call {
	_c.Call.Return(run)
	return _c
}

// ExistsTenantByCode provides a mock function for the type UserRepository
func (_mock *UserRepository) ExistsTenantByCode(ctx context.Context, code string) (bool, error) {
	ret := _mock.Called(ctx, code)

	if len(ret) == 0 {
		panic("no return value specified for ExistsTenantByCode")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return returnFunc(ctx, code)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, code)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, code)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UserRepository_ExistsTenantByCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExistsTenantByCode'
type UserRepository_ExistsTenantByCode_Call struct {
	*mock.Call
}

// ExistsTenantByCode is a helper method to define mock.On call
//   - ctx context.Context
//   - code string
func (_e *UserRepository_Expecter) ExistsTenantByCode(ctx interface{}, code interface{}) *UserRepository_ExistsTenantByCode_Call {
	return &UserRepository_ExistsTenantByCode_Call{Call: _e.mock.On("ExistsTenantByCode", ctx, code)}
}

func (_c *UserRepository_ExistsTenantByCode_Call) Run(run func(ctx context.Context, code string)) *UserRepository_ExistsTenantByCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserRepository_ExistsTenantByCode_Call) Return(b bool, err error) *UserRepository_ExistsTenantByCode_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *UserRepository_ExistsTenantByCode_Call) RunAndReturn(run func(ctx context.Context, code string) (bool, error)) *UserRepository_ExistsTenantByCode_Call {
	_c.Call.Return(run)
	return _c
}

// FindActiveUserByEmailAndTenant provides a mock function for the type UserRepository
func (_mock *UserRepository) FindActiveUserByEmailAndTenant(ctx context.Context, email string, tenantCode string) (*coreentity.User, error) {
	ret := _mock.Called(ctx, email, tenantCode)

	if len(ret) == 0 {
		panic("no return value specified for FindActiveUserByEmailAndTenant")
	}

	var r0 *coreentity.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*coreentity.User, error)); ok {
		return returnFunc(ctx, email, tenantCode)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *coreentity.User); ok {
		r0 = returnFunc(ctx, email, tenantCode)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*coreentity.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, email, tenantCode)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UserRepository_FindActiveUserByEmailAndTenant_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindActiveUserByEmailAndTenant'
type UserRepository_FindActiveUserByEmailAndTenant_Call struct {
	*mock.Call
}

// FindActiveUserByEmailAndTenant is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - tenantCode string
func (_e *UserRepository_Expecter) FindActiveUserByEmailAndTenant(ctx interface{}, email interface{}, tenantCode interface{}) *UserRepository_FindActiveUserByEmailAndTenant_Call {
	return &UserRepository_FindActiveUserByEmailAndTenant_Call{Call: _e.mock.On("FindActiveUserByEmailAndTenant", ctx, email, tenantCode)}
}

func (_c *UserRepository_FindActiveUserByEmailAndTenant_Call) Run(run func(ctx context.Context, email string, tenantCode string)) *UserRepository_FindActiveUserByEmailAndTenant_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *UserRepository_FindActiveUserByEmailAndTenant_Call) Return(user *coreentity.User, err error) *UserRepository_FindActiveUserByEmailAndTenant_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *UserRepository_FindActiveUserByEmailAndTenant_Call) RunAndReturn(run func(ctx context.Context, email string, tenantCode string) (*coreentity.User, error)) *UserRepository_FindActiveUserByEmailAndTenant_Call {
	_c.Call.Return(run)
	return _c
}

// FindActiveUserByEmailAndTenantID provides a mock function for the type UserRepository
func (_mock *UserRepository) FindActiveUserByEmailAndTenantID(ctx context.Context, email string, tenantID string) (*coreentity.User, error) {
	ret := _mock.Called(ctx, email, tenantID)

	if len(ret) == 0 {
		panic("no return value specified for FindActiveUserByEmailAndTenantID")
	}

	var r0 *coreentity.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*coreentity.User, error)); ok {
		return returnFunc(ctx, email, tenantID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *coreentity.User); ok {
		r0 = returnFunc(ctx, email, tenantID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*coreentity.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, email, tenantID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UserRepository_FindActiveUserByEmailAndTenantID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindActiveUserByEmailAndTenantID'
type UserRepository_FindActiveUserByEmailAndTenantID_Call struct {
	*mock.Call
}

// FindActiveUserByEmailAndTenantID is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - tenantID string
func (_e *UserRepository_Expecter) FindActiveUserByEmailAndTenantID(ctx interface{}, email interface{}, tenantID interface{}) *UserRepository_FindActiveUserByEmailAndTenantID_Call {
	return &UserRepository_FindActiveUserByEmailAndTenantID_Call{Call: _e.mock.On("FindActiveUserByEmailAndTenantID", ctx, email, tenantID)}
}

func (_c *UserRepository_FindActiveUserByEmailAndTenantID_Call) Run(run func(ctx context.Context, email string, tenantID string)) *UserRepository_FindActiveUserByEmailAndTenantID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *UserRepository_FindActiveUserByEmailAndTenantID_Call) Return(user *coreentity.User, err error) *UserRepository_FindActiveUserByEmailAndTenantID_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *UserRepository_FindActiveUserByEmailAndTenantID_Call) RunAndReturn(run func(ctx context.Context, email string, tenantID string) (*coreentity.User, error)) *UserRepository_FindActiveUserByEmailAndTenantID_Call {
	_c.Call.Return(run)
	return _c
}

// FindActiveUserByIDAndTenant provides a mock function for the type UserRepository
func (_mock *UserRepository) FindActiveUserByIDAndTenant(ctx context.Context, userID string, tenantID string) (*coreentity.User, error) {
	ret := _mock.Called(ctx, userID, tenantID)

	if len(ret) == 0 {
		panic("no return value specified for FindActiveUserByIDAndTenant")
	}

	var r0 *coreentity.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*coreentity.User, error)); ok {
		return returnFunc(ctx, userID, tenantID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *coreentity.User); ok {
		r0 = returnFunc(ctx, userID, tenantID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*coreentity.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, userID, tenantID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UserRepository_FindActiveUserByIDAndTenant_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindActiveUserByIDAndTenant'
type UserRepository_FindActiveUserByIDAndTenant_Call struct {
	*mock.Call
}

// FindActiveUserByIDAndTenant is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - tenantID string
func (_e *UserRepository_Expecter) FindActiveUserByIDAndTenant(ctx interface{}, userID interface{}, tenantID interface{}) *UserRepository_FindActiveUserByIDAndTenant_Call {
	return &UserRepository_FindActiveUserByIDAndTenant_Call{Call: _e.mock.On("FindActiveUserByIDAndTenant", ctx, userID, tenantID)}
}

func (_c *UserRepository_FindActiveUserByIDAndTenant_Call) Run(run func(ctx context.Context, userID string, tenantID string)) *UserRepository_FindActiveUserByIDAndTenant_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *UserRepository_FindActiveUserByIDAndTenant_Call) Return(user *coreentity.User, err error) *UserRepository_FindActiveUserByIDAndTenant_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *UserRepository_FindActiveUserByIDAndTenant_Call) RunAndReturn(run func(ctx context.Context, userID string, tenantID string) (*coreentity.User, error)) *UserRepository_FindActiveUserByIDAndTenant_Call {
	_c.Call.Return(run)
	return _c
}

// GetRoleByName provides a mock function for the type UserRepository
func (_mock *UserRepository) GetRoleByName(ctx context.Context, roleName string, tenantID string) (*coreentity.Role, error) {
	ret := _mock.Called(ctx, roleName, tenantID)

	if len(ret) == 0 {
		panic("no return value specified for GetRoleByName")
	}

	var r0 *coreentity.Role
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*coreentity.Role, error)); ok {
		return returnFunc(ctx, roleName, tenantID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *coreentity.Role); ok {
		r0 = returnFunc(ctx, roleName, tenantID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*coreentity.Role)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, roleName, tenantID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UserRepository_GetRoleByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRoleByName'
type UserRepository_GetRoleByName_Call struct {
	*mock.Call
}

// GetRoleByName is a helper method to define mock.On call
//   - ctx context.Context
//   - roleName string
//   - tenantID string
func (_e *UserRepository_Expecter) GetRoleByName(ctx interface{}, roleName interface{}, tenantID interface{}) *UserRepository_GetRoleByName_Call {
	return &UserRepository_GetRoleByName_Call{Call: _e.mock.On("GetRoleByName", ctx, roleName, tenantID)}
}

func (_c *UserRepository_GetRoleByName_Call) Run(run func(ctx context.Context, roleName string, tenantID string)) *UserRepository_GetRoleByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *UserRepository_GetRoleByName_Call) Return(role *coreentity.Role, err error) *UserRepository_GetRoleByName_Call {
	_c.Call.Return(role, err)
	return _c
}

func (_c *UserRepository_GetRoleByName_Call) RunAndReturn(run func(ctx context.Context, roleName string, tenantID string) (*coreentity.Role, error)) *UserRepository_GetRoleByName_Call {
	_c.Call.Return(run)
	return _c
}

// GetTenantPreferredLanguage provides a mock function for the type UserRepository
func (_mock *UserRepository) GetTenantPreferredLanguage(ctx context.Context, tenantID string) (string, error) {
	ret := _mock.Called(ctx, tenantID)

	if len(ret) == 0 {
		panic("no return value specified for GetTenantPreferredLanguage")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, tenantID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, tenantID)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, tenantID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UserRepository_GetTenantPreferredLanguage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTenantPreferredLanguage'
type UserRepository_GetTenantPreferredLanguage_Call struct {
	*mock.Call
}

// GetTenantPreferredLanguage is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID string
func (_e *UserRepository_Expecter) GetTenantPreferredLanguage(ctx interface{}, tenantID interface{}) *UserRepository_GetTenantPreferredLanguage_Call {
	return &UserRepository_GetTenantPreferredLanguage_Call{Call: _e.mock.On("GetTenantPreferredLanguage", ctx, tenantID)}
}

func (_c *UserRepository_GetTenantPreferredLanguage_Call) Run(run func(ctx context.Context, tenantID string)) *UserRepository_GetTenantPreferredLanguage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserRepository_GetTenantPreferredLanguage_Call) Return(s string, err error) *UserRepository_GetTenantPreferredLanguage_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *UserRepository_GetTenantPreferredLanguage_Call) RunAndReturn(run func(ctx context.Context, tenantID string) (string, error)) *UserRepository_GetTenantPreferredLanguage_Call {
	_c.Call.Return(run)
	return _c
}

// GetUser provides a mock function for the type UserRepository
func (_mock *UserRepository) GetUser(ctx context.Context, filter coreentity.User) (*coreentity.User, error) {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetUser")
	}

	var r0 *coreentity.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.User) (*coreentity.User, error)); ok {
		return returnFunc(ctx, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.User) *coreentity.User); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*coreentity.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, coreentity.User) error); ok {
		r1 = returnFunc(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UserRepository_GetUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUser'
type UserRepository_GetUser_Call struct {
	*mock.Call
}

// GetUser is a helper method to define mock.On call
//   - ctx context.Context
//   - filter coreentity.User
func (_e *UserRepository_Expecter) GetUser(ctx interface{}, filter interface{}) *UserRepository_GetUser_Call {
	return &UserRepository_GetUser_Call{Call: _e.mock.On("GetUser", ctx, filter)}
}

func (_c *UserRepository_GetUser_Call) Run(run func(ctx context.Context, filter coreentity.User)) *UserRepository_GetUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 coreentity.User
		if args[1] != nil {
			arg1 = args[1].(coreentity.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserRepository_GetUser_Call) Return(user *coreentity.User, err error) *UserRepository_GetUser_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *UserRepository_GetUser_Call) RunAndReturn(run func(ctx context.Context, filter coreentity.User) (*coreentity.User, error)) *UserRepository_GetUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetUsers provides a mock function for the type UserRepository
func (_mock *UserRepository) GetUsers(ctx context.Context, filter coreentity.UserListFilter) ([]coreentity.User, int, error) {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetUsers")
	}

	var r0 []coreentity.User
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.UserListFilter) ([]coreentity.User, int, error)); ok {
		return returnFunc(ctx, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.UserListFilter) []coreentity.User); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]coreentity.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, coreentity.UserListFilter) int); ok {
		r1 = returnFunc(ctx, filter)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, coreentity.UserListFilter) error); ok {
		r2 = returnFunc(ctx, filter)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// UserRepository_GetUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUsers'
type UserRepository_GetUsers_Call struct {
	*mock.Call
}

// GetUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - filter coreentity.UserListFilter
func (_e *UserRepository_Expecter) GetUsers(ctx interface{}, filter interface{}) *UserRepository_GetUsers_Call {
	return &UserRepository_GetUsers_Call{Call: _e.mock.On("GetUsers", ctx, filter)}
}

func (_c *UserRepository_GetUsers_Call) Run(run func(ctx context.Context, filter coreentity.UserListFilter)) *UserRepository_GetUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 coreentity.UserListFilter
		if args[1] != nil {
			arg1 = args[1].(coreentity.UserListFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserRepository_GetUsers_Call) Return(users []coreentity.User, n int, err error) *UserRepository_GetUsers_Call {
	_c.Call.Return(users, n, err)
	return _c
}

func (_c *UserRepository_GetUsers_Call) RunAndReturn(run func(ctx context.Context, filter coreentity.UserListFilter) ([]coreentity.User, int, error)) *UserRepository_GetUsers_Call {
	_c.Call.Return(run)
	return _c
}

// GetValidUserActionToken provides a mock function for the type UserRepository
func (_mock *UserRepository) GetValidUserActionToken(ctx context.Context, tokenHash string, purpose string) (*coreentity.UserActionToken, error) {
	ret := _mock.Called(ctx, tokenHash, purpose)

	if len(ret) == 0 {
		panic("no return value specified for GetValidUserActionToken")
	}

	var r0 *coreentity.UserActionToken
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*coreentity.UserActionToken, error)); ok {
		return returnFunc(ctx, tokenHash, purpose)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *coreentity.UserActionToken); ok {
		r0 = returnFunc(ctx, tokenHash, purpose)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*coreentity.UserActionToken)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, tokenHash, purpose)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UserRepository_GetValidUserActionToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetValidUserActionToken'
type UserRepository_GetValidUserActionToken_Call struct {
	*mock.Call
}

// GetValidUserActionToken is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenHash string
//   - purpose string
func (_e *UserRepository_Expecter) GetValidUserActionToken(ctx interface{}, tokenHash interface{}, purpose interface{}) *UserRepository_GetValidUserActionToken_Call {
	return &UserRepository_GetValidUserActionToken_Call{Call: _e.mock.On("GetValidUserActionToken", ctx, tokenHash, purpose)}
}

func (_c *UserRepository_GetValidUserActionToken_Call) Run(run func(ctx context.Context, tokenHash string, purpose string)) *UserRepository_GetValidUserActionToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *UserRepository_GetValidUserActionToken_Call) Return(userActionToken *coreentity.UserActionToken, err error) *UserRepository_GetValidUserActionToken_Call {
	_c.Call.Return(userActionToken, err)
	return _c
}

func (_c *UserRepository_GetValidUserActionToken_Call) RunAndReturn(run func(ctx context.Context, tokenHash string, purpose string) (*coreentity.UserActionToken, error)) *UserRepository_GetValidUserActionToken_Call {
	_c.Call.Return(run)
	return _c
}

// InitializeTenant provides a mock function for the type UserRepository
func (_mock *UserRepository) InitializeTenant(ctx context.Context, tenantID string, companyName string, preferredLanguage string) (string, error) {
	ret := _mock.Called(ctx, tenantID, companyName, preferredLanguage)

	if len(ret) == 0 {
		panic("no return value specified for InitializeTenant")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) (string, error)); ok {
		return returnFunc(ctx, tenantID, companyName, preferredLanguage)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) string); ok {
		r0 = returnFunc(ctx, tenantID, companyName, preferredLanguage)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = returnFunc(ctx, tenantID, companyName, preferredLanguage)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UserRepository_InitializeTenant_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InitializeTenant'
type UserRepository_InitializeTenant_Call struct {
	*mock.Call
}

// InitializeTenant is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID string
//   - companyName string
//   - preferredLanguage string
func (_e *UserRepository_Expecter) InitializeTenant(ctx interface{}, tenantID interface{}, companyName interface{}, preferredLanguage interface{}) *UserRepository_InitializeTenant_Call {
	return &UserRepository_InitializeTenant_Call{Call: _e.mock.On("InitializeTenant", ctx, tenantID, companyName, preferredLanguage)}
}

func (_c *UserRepository_InitializeTenant_Call) Run(run func(ctx context.Context, tenantID string, companyName string, preferredLanguage string)) *UserRepository_InitializeTenant_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *UserRepository_InitializeTenant_Call) Return(s string, err error) *UserRepository_InitializeTenant_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *UserRepository_InitializeTenant_Call) RunAndReturn(run func(ctx context.Context, tenantID string, companyName string, preferredLanguage string) (string, error)) *UserRepository_InitializeTenant_Call {
	_c.Call.Return(run)
	return _c
}

// InsertTenant provides a mock function for the type UserRepository
func (_mock *UserRepository) InsertTenant(ctx context.Context, tenant coreentity.Tenant) (string, error) {
	ret := _mock.Called(ctx, tenant)

	if len(ret) == 0 {
		panic("no return value specified for InsertTenant")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.Tenant) (string, error)); ok {
		return returnFunc(ctx, tenant)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.Tenant) string); ok {
		r0 = returnFunc(ctx, tenant)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, coreentity.Tenant) error); ok {
		r1 = returnFunc(ctx, tenant)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UserRepository_InsertTenant_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertTenant'
type UserRepository_InsertTenant_Call struct {
	*mock.Call
}

// InsertTenant is a helper method to define mock.On call
//   - ctx context.Context
//   - tenant coreentity.Tenant
func (_e *UserRepository_Expecter) InsertTenant(ctx interface{}, tenant interface{}) *UserRepository_InsertTenant_Call {
	return &UserRepository_InsertTenant_Call{Call: _e.mock.On("InsertTenant", ctx, tenant)}
}

func (_c *UserRepository_InsertTenant_Call) Run(run func(ctx context.Context, tenant coreentity.Tenant)) *UserRepository_InsertTenant_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 coreentity.Tenant
		if args[1] != nil {
			arg1 = args[1].(coreentity.Tenant)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserRepository_InsertTenant_Call) Return(s string, err error) *UserRepository_InsertTenant_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *UserRepository_InsertTenant_Call) RunAndReturn(run func(ctx context.Context, tenant coreentity.Tenant) (string, error)) *UserRepository_InsertTenant_Call {
	_c.Call.Return(run)
	return _c
}

// InsertUser provides a mock function for the type UserRepository
func (_mock *UserRepository) InsertUser(ctx context.Context, user coreentity.User) (string, error) {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for InsertUser")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.User) (string, error)); ok {
		return returnFunc(ctx, user)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.User) string); ok {
		r0 = returnFunc(ctx, user)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, coreentity.User) error); ok {
		r1 = returnFunc(ctx, user)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UserRepository_InsertUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertUser'
type UserRepository_InsertUser_Call struct {
	*mock.Call
}

// InsertUser is a helper method to define mock.On call
//   - ctx context.Context
//   - user coreentity.User
func (_e *UserRepository_Expecter) InsertUser(ctx interface{}, user interface{}) *UserRepository_InsertUser_Call {
	return &UserRepository_InsertUser_Call{Call: _e.mock.On("InsertUser", ctx, user)}
}

func (_c *UserRepository_InsertUser_Call) Run(run func(ctx context.Context, user coreentity.User)) *UserRepository_InsertUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 coreentity.User
		if args[1] != nil {
			arg1 = args[1].(coreentity.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserRepository_InsertUser_Call) Return(s string, err error) *UserRepository_InsertUser_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *UserRepository_InsertUser_Call) RunAndReturn(run func(ctx context.Context, user coreentity.User) (string, error)) *UserRepository_InsertUser_Call {
	_c.Call.Return(run)
	return _c
}

// MarkUserActionTokenUsed provides a mock function for the type UserRepository
func (_mock *UserRepository) MarkUserActionTokenUsed(ctx context.Context, tokenID string) error {
	ret := _mock.Called(ctx, tokenID)

	if len(ret) == 0 {
		panic("no return value specified for MarkUserActionTokenUsed")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, tokenID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// UserRepository_MarkUserActionTokenUsed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkUserActionTokenUsed'
type UserRepository_MarkUserActionTokenUsed_Call struct {
	*mock.Call
}

// MarkUserActionTokenUsed is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenID string
func (_e *UserRepository_Expecter) MarkUserActionTokenUsed(ctx interface{}, tokenID interface{}) *UserRepository_MarkUserActionTokenUsed_Call {
	return &UserRepository_MarkUserActionTokenUsed_Call{Call: _e.mock.On("MarkUserActionTokenUsed", ctx, tokenID)}
}

func (_c *UserRepository_MarkUserActionTokenUsed_Call) Run(run func(ctx context.Context, tokenID string)) *UserRepository_MarkUserActionTokenUsed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserRepository_MarkUserActionTokenUsed_Call) Return(err error) *UserRepository_MarkUserActionTokenUsed_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *UserRepository_MarkUserActionTokenUsed_Call) RunAndReturn(run func(ctx context.Context, tokenID string) error) *UserRepository_MarkUserActionTokenUsed_Call {
	_c.Call.Return(run)
	return _c
}

// MarkUserEmailVerified provides a mock function for the type UserRepository
func (_mock *UserRepository) MarkUserEmailVerified(ctx context.Context, userID string) error {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for MarkUserEmailVerified")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// UserRepository_MarkUserEmailVerified_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkUserEmailVerified'
type UserRepository_MarkUserEmailVerified_Call struct {
	*mock.Call
}

// MarkUserEmailVerified is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *UserRepository_Expecter) MarkUserEmailVerified(ctx interface{}, userID interface{}) *UserRepository_MarkUserEmailVerified_Call {
	return &UserRepository_MarkUserEmailVerified_Call{Call: _e.mock.On("MarkUserEmailVerified", ctx, userID)}
}

func (_c *UserRepository_MarkUserEmailVerified_Call) Run(run func(ctx context.Context, userID string)) *UserRepository_MarkUserEmailVerified_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserRepository_MarkUserEmailVerified_Call) Return(err error) *UserRepository_MarkUserEmailVerified_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *UserRepository_MarkUserEmailVerified_Call) RunAndReturn(run func(ctx context.Context, userID string) error) *UserRepository_MarkUserEmailVerified_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUser provides a mock function for the type UserRepository
func (_mock *UserRepository) UpdateUser(ctx context.Context, data coreentity.User) error {
	ret := _mock.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.User) error); ok {
		r0 = returnFunc(ctx, data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// UserRepository_UpdateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUser'
type UserRepository_UpdateUser_Call struct {
	*mock.Call
}

// UpdateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - data coreentity.User
func (_e *UserRepository_Expecter) UpdateUser(ctx interface{}, data interface{}) *UserRepository_UpdateUser_Call {
	return &UserRepository_UpdateUser_Call{Call: _e.mock.On("UpdateUser", ctx, data)}
}

func (_c *UserRepository_UpdateUser_Call) Run(run func(ctx context.Context, data coreentity.User)) *UserRepository_UpdateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 coreentity.User
		if args[1] != nil {
			arg1 = args[1].(coreentity.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserRepository_UpdateUser_Call) Return(err error) *UserRepository_UpdateUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *UserRepository_UpdateUser_Call) RunAndReturn(run func(ctx context.Context, data coreentity.User) error) *UserRepository_UpdateUser_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUserEmail provides a mock function for the type UserRepository
func (_mock *UserRepository) UpdateUserEmail(ctx context.Context, userID string, tenantID string, email string) error {
	ret := _mock.Called(ctx, userID, tenantID, email)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUserEmail")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = returnFunc(ctx, userID, tenantID, email)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// UserRepository_UpdateUserEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUserEmail'
type UserRepository_UpdateUserEmail_Call struct {
	*mock.Call
}

// UpdateUserEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - tenantID string
//   - email string
func (_e *UserRepository_Expecter) UpdateUserEmail(ctx interface{}, userID interface{}, tenantID interface{}, email interface{}) *UserRepository_UpdateUserEmail_Call {
	return &UserRepository_UpdateUserEmail_Call{Call: _e.mock.On("UpdateUserEmail", ctx, userID, tenantID, email)}
}

func (_c *UserRepository_UpdateUserEmail_Call) Run(run func(ctx context.Context, userID string, tenantID string, email string)) *UserRepository_UpdateUserEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *UserRepository_UpdateUserEmail_Call) Return(err error) *UserRepository_UpdateUserEmail_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *UserRepository_UpdateUserEmail_Call) RunAndReturn(run func(ctx context.Context, userID string, tenantID string, email string) error) *UserRepository_UpdateUserEmail_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUserPassword provides a mock function for the type UserRepository
func (_mock *UserRepository) UpdateUserPassword(ctx context.Context, userID string, tenantID string, hashedPassword string) error {
	ret := _mock.Called(ctx, userID, tenantID, hashedPassword)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUserPassword")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = returnFunc(ctx, userID, tenantID, hashedPassword)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// UserRepository_UpdateUserPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUserPassword'
type UserRepository_UpdateUserPassword_Call struct {
	*mock.Call
}

// UpdateUserPassword is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - tenantID string
//   - hashedPassword string
func (_e *UserRepository_Expecter) UpdateUserPassword(ctx interface{}, userID interface{}, tenantID interface{}, hashedPassword interface{}) *UserRepository_UpdateUserPassword_Call {
	return &UserRepository_UpdateUserPassword_Call{Call: _e.mock.On("UpdateUserPassword", ctx, userID, tenantID, hashedPassword)}
}

func (_c *UserRepository_UpdateUserPassword_Call) Run(run func(ctx context.Context, userID string, tenantID string, hashedPassword string)) *UserRepository_UpdateUserPassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *UserRepository_UpdateUserPassword_Call) Return(err error) *UserRepository_UpdateUserPassword_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *UserRepository_UpdateUserPassword_Call) RunAndReturn(run func(ctx context.Context, userID string, tenantID string, hashedPassword string) error) *UserRepository_UpdateUserPassword_Call {
	_c.Call.Return(run)
	return _c
}
