// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"codebase-app/internal/entity/coreentity"
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewWorkShiftRepository creates a new instance of WorkShiftRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWorkShiftRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *WorkShiftRepository {
	mock := &WorkShiftRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// WorkShiftRepository is an autogenerated mock type for the WorkShiftRepository type
type WorkShiftRepository struct {
	mock.Mock
}

type WorkShiftRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *WorkShiftRepository) EXPECT() *WorkShiftRepository_Expecter {
	return &WorkShiftRepository_Expecter{mock: &_m.Mock}
}

// CreateWorkShift provides a mock function for the type WorkShiftRepository
func (_mock *WorkShiftRepository) CreateWorkShift(ctx context.Context, data coreentity.WorkShift) (*coreentity.WorkShift, error) {
	ret := _mock.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for CreateWorkShift")
	}

	var r0 *coreentity.WorkShift
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.WorkShift) (*coreentity.WorkShift, error)); ok {
		return returnFunc(ctx, data)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.WorkShift) *coreentity.WorkShift); ok {
		r0 = returnFunc(ctx, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*coreentity.WorkShift)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, coreentity.WorkShift) error); ok {
		r1 = returnFunc(ctx, data)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// WorkShiftRepository_CreateWorkShift_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateWorkShift'
type WorkShiftRepository_CreateWorkShift_Call struct {
	*mock.Call
}

// CreateWorkShift is a helper method to define mock.On call
//   - ctx context.Context
//   - data coreentity.WorkShift
func (_e *WorkShiftRepository_Expecter) CreateWorkShift(ctx interface{}, data interface{}) *WorkShiftRepository_CreateWorkShift_Call {
	return &WorkShiftRepository_CreateWorkShift_Call{Call: _e.mock.On("CreateWorkShift", ctx, data)}
}

func (_c *WorkShiftRepository_CreateWorkShift_Call) Run(run func(ctx context.Context, data coreentity.WorkShift)) *WorkShiftRepository_CreateWorkShift_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 coreentity.WorkShift
		if args[1] != nil {
			arg1 = args[1].(coreentity.WorkShift)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *WorkShiftRepository_CreateWorkShift_Call) Return(workShift *coreentity.WorkShift, err error) *WorkShiftRepository_CreateWorkShift_Call {
	_c.Call.Return(workShift, err)
	return _c
}

func (_c *WorkShiftRepository_CreateWorkShift_Call) RunAndReturn(run func(ctx context.Context, data coreentity.WorkShift) (*coreentity.WorkShift, error)) *WorkShiftRepository_CreateWorkShift_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteWorkShift provides a mock function for the type WorkShiftRepository
func (_mock *WorkShiftRepository) DeleteWorkShift(ctx context.Context, filter coreentity.WorkShiftDeleteFilter) error {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for DeleteWorkShift")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.WorkShiftDeleteFilter) error); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// WorkShiftRepository_DeleteWorkShift_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteWorkShift'
type WorkShiftRepository_DeleteWorkShift_Call struct {
	*mock.Call
}

// DeleteWorkShift is a helper method to define mock.On call
//   - ctx context.Context
//   - filter coreentity.WorkShiftDeleteFilter
func (_e *WorkShiftRepository_Expecter) DeleteWorkShift(ctx interface{}, filter interface{}) *WorkShiftRepository_DeleteWorkShift_Call {
	return &WorkShiftRepository_DeleteWorkShift_Call{Call: _e.mock.On("DeleteWorkShift", ctx, filter)}
}

func (_c *WorkShiftRepository_DeleteWorkShift_Call) Run(run func(ctx context.Context, filter coreentity.WorkShiftDeleteFilter)) *WorkShiftRepository_DeleteWorkShift_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 coreentity.WorkShiftDeleteFilter
		if args[1] != nil {
			arg1 = args[1].(coreentity.WorkShiftDeleteFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *WorkShiftRepository_DeleteWorkShift_Call) Return(err error) *WorkShiftRepository_DeleteWorkShift_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *WorkShiftRepository_DeleteWorkShift_Call) RunAndReturn(run func(ctx context.Context, filter coreentity.WorkShiftDeleteFilter) error) *WorkShiftRepository_DeleteWorkShift_Call {
	_c.Call.Return(run)
	return _c
}

// GetWorkShift provides a mock function for the type WorkShiftRepository
func (_mock *WorkShiftRepository) GetWorkShift(ctx context.Context, filter coreentity.WorkShift) (*coreentity.WorkShift, error) {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetWorkShift")
	}

	var r0 *coreentity.WorkShift
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.WorkShift) (*coreentity.WorkShift, error)); ok {
		return returnFunc(ctx, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.WorkShift) *coreentity.WorkShift); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*coreentity.WorkShift)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, coreentity.WorkShift) error); ok {
		r1 = returnFunc(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// WorkShiftRepository_GetWorkShift_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWorkShift'
type WorkShiftRepository_GetWorkShift_Call struct {
	*mock.Call
}

// GetWorkShift is a helper method to define mock.On call
//   - ctx context.Context
//   - filter coreentity.WorkShift
func (_e *WorkShiftRepository_Expecter) GetWorkShift(ctx interface{}, filter interface{}) *WorkShiftRepository_GetWorkShift_Call {
	return &WorkShiftRepository_GetWorkShift_Call{Call: _e.mock.On("GetWorkShift", ctx, filter)}
}

func (_c *WorkShiftRepository_GetWorkShift_Call) Run(run func(ctx context.Context, filter coreentity.WorkShift)) *WorkShiftRepository_GetWorkShift_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 coreentity.WorkShift
		if args[1] != nil {
			arg1 = args[1].(coreentity.WorkShift)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *WorkShiftRepository_GetWorkShift_Call) Return(workShift *coreentity.WorkShift, err error) *WorkShiftRepository_GetWorkShift_Call {
	_c.Call.Return(workShift, err)
	return _c
}

func (_c *WorkShiftRepository_GetWorkShift_Call) RunAndReturn(run func(ctx context.Context, filter coreentity.WorkShift) (*coreentity.WorkShift, error)) *WorkShiftRepository_GetWorkShift_Call {
	_c.Call.Return(run)
	return _c
}

// GetWorkShifts provides a mock function for the type WorkShiftRepository
func (_mock *WorkShiftRepository) GetWorkShifts(ctx context.Context, filter coreentity.WorkShiftListFilter) ([]coreentity.WorkShift, int, error) {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetWorkShifts")
	}

	var r0 []coreentity.WorkShift
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.WorkShiftListFilter) ([]coreentity.WorkShift, int, error)); ok {
		return returnFunc(ctx, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.WorkShiftListFilter) []coreentity.WorkShift); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]coreentity.WorkShift)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, coreentity.WorkShiftListFilter) int); ok {
		r1 = returnFunc(ctx, filter)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, coreentity.WorkShiftListFilter) error); ok {
		r2 = returnFunc(ctx, filter)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// WorkShiftRepository_GetWorkShifts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWorkShifts'
type WorkShiftRepository_GetWorkShifts_Call struct {
	*mock.Call
}

// GetWorkShifts is a helper method to define mock.On call
//   - ctx context.Context
//   - filter coreentity.WorkShiftListFilter
func (_e *WorkShiftRepository_Expecter) GetWorkShifts(ctx interface{}, filter interface{}) *WorkShiftRepository_GetWorkShifts_Call {
	return &WorkShiftRepository_GetWorkShifts_Call{Call: _e.mock.On("GetWorkShifts", ctx, filter)}
}

func (_c *WorkShiftRepository_GetWorkShifts_Call) Run(run func(ctx context.Context, filter coreentity.WorkShiftListFilter)) *WorkShiftRepository_GetWorkShifts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 coreentity.WorkShiftListFilter
		if args[1] != nil {
			arg1 = args[1].(coreentity.WorkShiftListFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *WorkShiftRepository_GetWorkShifts_Call) Return(workShifts []coreentity.WorkShift, n int, err error) *WorkShiftRepository_GetWorkShifts_Call {
	_c.Call.Return(workShifts, n, err)
	return _c
}

func (_c *WorkShiftRepository_GetWorkShifts_Call) RunAndReturn(run func(ctx context.Context, filter coreentity.WorkShiftListFilter) ([]coreentity.WorkShift, int, error)) *WorkShiftRepository_GetWorkShifts_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateWorkShift provides a mock function for the type WorkShiftRepository
func (_mock *WorkShiftRepository) UpdateWorkShift(ctx context.Context, data coreentity.WorkShift) error {
	ret := _mock.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for UpdateWorkShift")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, coreentity.WorkShift) error); ok {
		r0 = returnFunc(ctx, data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// WorkShiftRepository_UpdateWorkShift_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateWorkShift'
type WorkShiftRepository_UpdateWorkShift_Call struct {
	*mock.Call
}

// UpdateWorkShift is a helper method to define mock.On call
//   - ctx context.Context
//   - data coreentity.WorkShift
func (_e *WorkShiftRepository_Expecter) UpdateWorkShift(ctx interface{}, data interface{}) *WorkShiftRepository_UpdateWorkShift_Call {
	return &WorkShiftRepository_UpdateWorkShift_Call{Call: _e.mock.On("UpdateWorkShift", ctx, data)}
}

func (_c *WorkShiftRepository_UpdateWorkShift_Call) Run(run func(ctx context.Context, data coreentity.WorkShift)) *WorkShiftRepository_UpdateWorkShift_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 coreentity.WorkShift
		if args[1] != nil {
			arg1 = args[1].(coreentity.WorkShift)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *WorkShiftRepository_UpdateWorkShift_Call) Return(err error) *WorkShiftRepository_UpdateWorkShift_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *WorkShiftRepository_UpdateWorkShift_Call) RunAndReturn(run func(ctx context.Context, data coreentity.WorkShift) error) *WorkShiftRepository_UpdateWorkShift_Call {
	_c.Call.Return(run)
	return _c
}
